Repository labex-labs/scenarios, pull requests merged in 2023-05, with the labels that each got.

#622 challenge-find-edges
  opencv/challenge-find-edges/assets/apply_edge_detection.py
  opencv/challenge-find-edges/assets/canny_edges_image.jpg
  opencv/challenge-find-edges/assets/combine_edges_image.jpg
  opencv/challenge-find-edges/assets/fine_tune_and_save_result.py
  opencv/challenge-find-edges/assets/gray_image.jpg
  opencv/challenge-find-edges/assets/image_example.jpg
  opencv/challenge-find-edges/assets/image_test.jpg
  opencv/challenge-find-edges/assets/log_edges_image.jpg
  opencv/challenge-find-edges/assets/read_and_preprocess_image.py
  opencv/challenge-find-edges/assets/test_apply_edge_detection.py
  opencv/challenge-find-edges/assets/test_fine_tune_and_save_result.py
  opencv/challenge-find-edges/assets/test_read_and_preprocess_image.py
  opencv/challenge-find-edges/finish.md
  opencv/challenge-find-edges/index.json
  opencv/challenge-find-edges/intro.md
  opencv/challenge-find-edges/setup.sh
  opencv/challenge-find-edges/solutions/apply_edge_detection.py
  opencv/challenge-find-edges/solutions/fine_tune_and_save_result.py
  opencv/challenge-find-edges/solutions/read_and_preprocess_image.py
  opencv/challenge-find-edges/step1.md
  opencv/challenge-find-edges/step2.md
  opencv/challenge-find-edges/step3.md
  opencv/challenge-find-edges/verify1.sh
  opencv/challenge-find-edges/verify2.sh
  opencv/challenge-find-edges/verify3.sh
Labels: Test Completed, Major Repair

#621 add challeng-currency-exchange
  python/challenge-currency-exchange/assets/currency_conversion.py
  python/challenge-currency-exchange/assets/currency_conversion_test.py
  python/challenge-currency-exchange/assets/get_exchange_rate.py
  python/challenge-currency-exchange/assets/get_exchange_rate_test.py
  python/challenge-currency-exchange/assets/usd.json
  python/challenge-currency-exchange/finish.md
  python/challenge-currency-exchange/index.json
  python/challenge-currency-exchange/intro.md
  python/challenge-currency-exchange/setup.sh
  python/challenge-currency-exchange/solutions/currency_conversion.py
  python/challenge-currency-exchange/solutions/get_exchange_rate.py
  python/challenge-currency-exchange/step1.md
  python/challenge-currency-exchange/step2.md
  python/challenge-currency-exchange/verify1.sh
  python/challenge-currency-exchange/verify2.sh
Labels: Test Completed, No Repair

#626 lab-getting-started-with-videos
  opencv/lab-getting-started-with-videos/assets/download_video.jpg
  opencv/lab-getting-started-with-videos/assets/read_video.py
  opencv/lab-getting-started-with-videos/assets/run_python_file_button.jpg
  opencv/lab-getting-started-with-videos/assets/video.mp4
  opencv/lab-getting-started-with-videos/assets/write_video.py
  opencv/lab-getting-started-with-videos/finish.md
  opencv/lab-getting-started-with-videos/index.json
  opencv/lab-getting-started-with-videos/intro.md
  opencv/lab-getting-started-with-videos/setup.sh
  opencv/lab-getting-started-with-videos/step1.md
  opencv/lab-getting-started-with-videos/step2.md
  opencv/lab-getting-started-with-videos/verify1.sh
  opencv/lab-getting-started-with-videos/verify2.sh
Labels: Test Completed, Major Repair

#641 add: lab-running-containers-in-pods
  kubernetes/lab-running-containers-in-pods/finish.md
  kubernetes/lab-running-containers-in-pods/index.json
  kubernetes/lab-running-containers-in-pods/intro.md
  kubernetes/lab-running-containers-in-pods/setup.sh
  kubernetes/lab-running-containers-in-pods/step1.md
  kubernetes/lab-running-containers-in-pods/step2.md
  kubernetes/lab-running-containers-in-pods/step3.md
  kubernetes/lab-running-containers-in-pods/step4.md
  kubernetes/lab-running-containers-in-pods/step5.md
  kubernetes/lab-running-containers-in-pods/verify1-1.sh
  kubernetes/lab-running-containers-in-pods/verify1-2.sh
  kubernetes/lab-running-containers-in-pods/verify2-1.sh
  kubernetes/lab-running-containers-in-pods/verify2-2.sh
  kubernetes/lab-running-containers-in-pods/verify3-1.sh
  kubernetes/lab-running-containers-in-pods/verify3-2.sh
  kubernetes/lab-running-containers-in-pods/verify4-1.sh
  kubernetes/lab-running-containers-in-pods/verify4-2.sh
  kubernetes/lab-running-containers-in-pods/verify5-1.sh
  kubernetes/lab-running-containers-in-pods/verify5-2.sh
  kubernetes/lab-running-containers-in-pods/verify5-3.sh
Labels: Test Completed, No Repair

#644 Add lab scheduing with node selectors
  kubernetes/lab-scheduing-with-node-selectors/finish.md
  kubernetes/lab-scheduing-with-node-selectors/index.json
  kubernetes/lab-scheduing-with-node-selectors/intro.md
  kubernetes/lab-scheduing-with-node-selectors/setup.sh
  kubernetes/lab-scheduing-with-node-selectors/step1.md
  kubernetes/lab-scheduing-with-node-selectors/step2.md
  kubernetes/lab-scheduing-with-node-selectors/step3.md
  kubernetes/lab-scheduing-with-node-selectors/verify1-1.sh
  kubernetes/lab-scheduing-with-node-selectors/verify1-2.sh
  kubernetes/lab-scheduing-with-node-selectors/verify2-1.sh
  kubernetes/lab-scheduing-with-node-selectors/verify2-2.sh
  kubernetes/lab-scheduing-with-node-selectors/verify2-3.sh
  kubernetes/lab-scheduing-with-node-selectors/verify3-1.sh
  kubernetes/lab-scheduing-with-node-selectors/verify3-2.sh
  kubernetes/lab-scheduing-with-node-selectors/verify3-3.sh
Labels: Test Completed, No Repair

#646 Add challenge docker network with compose
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-1-1.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-1-2.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-1-3.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-1-4.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-2-1.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-2-2.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-2-3.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-2-4.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-3-1.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-3-2.png
  docker/challenge-docker-network-with-compose/assets/challenge-docker-network-with-compose-3-3.png
  docker/challenge-docker-network-with-compose/finish.md
  docker/challenge-docker-network-with-compose/index.json
  docker/challenge-docker-network-with-compose/intro.md
  docker/challenge-docker-network-with-compose/setup.sh
  docker/challenge-docker-network-with-compose/solutions/step1-solution.md
  docker/challenge-docker-network-with-compose/solutions/step2-solution.md
  docker/challenge-docker-network-with-compose/solutions/step3-solution.md
  docker/challenge-docker-network-with-compose/step1.md
  docker/challenge-docker-network-with-compose/step2.md
  docker/challenge-docker-network-with-compose/step3.md
  docker/challenge-docker-network-with-compose/verify1-1.sh
  docker/challenge-docker-network-with-compose/verify1-2.sh
  docker/challenge-docker-network-with-compose/verify1-3.sh
  docker/challenge-docker-network-with-compose/verify1-4.sh
  docker/challenge-docker-network-with-compose/verify2-1.sh
  docker/challenge-docker-network-with-compose/verify2-2.sh
  docker/challenge-docker-network-with-compose/verify2-3.sh
  docker/challenge-docker-network-with-compose/verify2-4.sh
  docker/challenge-docker-network-with-compose/verify3-1.sh
  docker/challenge-docker-network-with-compose/verify3-2.sh
  docker/challenge-docker-network-with-compose/verify3-3.sh
Labels: Test Completed, Minor Repair

#651 add challenge-real-time-data-processing-system
  python/challenge-real-time-data-processing-system/assets/data_generator.py
  python/challenge-real-time-data-processing-system/assets/data_generator_test.py
  python/challenge-real-time-data-processing-system/assets/data_generator_test_by_system.py
  python/challenge-real-time-data-processing-system/assets/data_processor.py
  python/challenge-real-time-data-processing-system/assets/data_processor_test.py
  python/challenge-real-time-data-processing-system/assets/data_processor_test_by_system.py
  python/challenge-real-time-data-processing-system/assets/main_function.py
  python/challenge-real-time-data-processing-system/assets/main_function_test_by_system.py
  python/challenge-real-time-data-processing-system/finish.md
  python/challenge-real-time-data-processing-system/index.json
  python/challenge-real-time-data-processing-system/intro.md
  python/challenge-real-time-data-processing-system/setup.sh
  python/challenge-real-time-data-processing-system/solutions/data_generator.py
  python/challenge-real-time-data-processing-system/solutions/data_processor.py
  python/challenge-real-time-data-processing-system/solutions/main_function.py
  python/challenge-real-time-data-processing-system/step1.md
  python/challenge-real-time-data-processing-system/step2.md
  python/challenge-real-time-data-processing-system/step3.md
  python/challenge-real-time-data-processing-system/verify1.sh
  python/challenge-real-time-data-processing-system/verify2.sh
  python/challenge-real-time-data-processing-system/verify3.sh
Labels: Test Completed, Major Repair

#643 Add lab kubernetes dashboard
  kubernetes/lab-kubernetes-dashboard/assets/lab-kubernetes-dashboard-3-1.png
  kubernetes/lab-kubernetes-dashboard/assets/lab-kubernetes-dashboard-3-2.png
  kubernetes/lab-kubernetes-dashboard/assets/lab-kubernetes-dashboard-3-3.png
  kubernetes/lab-kubernetes-dashboard/finish.md
  kubernetes/lab-kubernetes-dashboard/index.json
  kubernetes/lab-kubernetes-dashboard/intro.md
  kubernetes/lab-kubernetes-dashboard/setup.sh
  kubernetes/lab-kubernetes-dashboard/step1.md
  kubernetes/lab-kubernetes-dashboard/step2.md
  kubernetes/lab-kubernetes-dashboard/step3.md
  kubernetes/lab-kubernetes-dashboard/verify1-1.sh
  kubernetes/lab-kubernetes-dashboard/verify1-2.sh
  kubernetes/lab-kubernetes-dashboard/verify2.sh
  kubernetes/lab-kubernetes-dashboard/verify3-1.sh
  kubernetes/lab-kubernetes-dashboard/verify3-2.sh
  kubernetes/lab-kubernetes-dashboard/verify3-3.sh
  kubernetes/lab-kubernetes-dashboard/verify3-4.sh
Labels: Test Completed, Minor Repair

#675 Add challenge docker network tutorial
  docker/challenge-docker-network-tutorial/assets/challenge-docker-network-tutorial-1.png
  docker/challenge-docker-network-tutorial/assets/challenge-docker-network-tutorial-2.png
  docker/challenge-docker-network-tutorial/assets/challenge-docker-network-tutorial-3.png
  docker/challenge-docker-network-tutorial/assets/challenge-docker-network-tutorial-4-1.png
  docker/challenge-docker-network-tutorial/assets/challenge-docker-network-tutorial-4-2.png
  docker/challenge-docker-network-tutorial/assets/challenge-docker-network-tutorial-5.png
  docker/challenge-docker-network-tutorial/assets/challenge-docker-network-tutorial-6.png
  docker/challenge-docker-network-tutorial/finish.md
  docker/challenge-docker-network-tutorial/index.json
  docker/challenge-docker-network-tutorial/intro.md
  docker/challenge-docker-network-tutorial/setup.sh
  docker/challenge-docker-network-tutorial/solutions/step1-solution.md
  docker/challenge-docker-network-tutorial/solutions/step2-solution.md
  docker/challenge-docker-network-tutorial/solutions/step3-solution.md
  docker/challenge-docker-network-tutorial/solutions/step4-solution.md
  docker/challenge-docker-network-tutorial/solutions/step5-solution.md
  docker/challenge-docker-network-tutorial/solutions/step6-solution.md
  docker/challenge-docker-network-tutorial/step1.md
  docker/challenge-docker-network-tutorial/step2.md
  docker/challenge-docker-network-tutorial/step3.md
  docker/challenge-docker-network-tutorial/step4.md
  docker/challenge-docker-network-tutorial/step5.md
  docker/challenge-docker-network-tutorial/step6.md
  docker/challenge-docker-network-tutorial/verify1-1.sh
  docker/challenge-docker-network-tutorial/verify1-2.sh
  docker/challenge-docker-network-tutorial/verify2.sh
  docker/challenge-docker-network-tutorial/verify3.sh
  docker/challenge-docker-network-tutorial/verify4-1.sh
  docker/challenge-docker-network-tutorial/verify4-2.sh
  docker/challenge-docker-network-tutorial/verify4-3.sh
  docker/challenge-docker-network-tutorial/verify5-1.sh
  docker/challenge-docker-network-tutorial/verify5-2.sh
  docker/challenge-docker-network-tutorial/verify6-1.sh
  docker/challenge-docker-network-tutorial/verify6-2.sh
Labels: Test Completed, No Repair

#673 Add challenge docker multi stage build
  docker/challenge-docker-multi-stage-build/assets/challenge-docker-multi-stage-build-1-1.png
  docker/challenge-docker-multi-stage-build/assets/challenge-docker-multi-stage-build-1-2.png
  docker/challenge-docker-multi-stage-build/assets/challenge-docker-multi-stage-build-2.png
  docker/challenge-docker-multi-stage-build/assets/challenge-docker-multi-stage-build-3-1.png
  docker/challenge-docker-multi-stage-build/assets/challenge-docker-multi-stage-build-3-2.png
  docker/challenge-docker-multi-stage-build/finish.md
  docker/challenge-docker-multi-stage-build/index.json
  docker/challenge-docker-multi-stage-build/intro.md
  docker/challenge-docker-multi-stage-build/setup.sh
  docker/challenge-docker-multi-stage-build/solutions/step1-solution.md
  docker/challenge-docker-multi-stage-build/solutions/step2-solution.md
  docker/challenge-docker-multi-stage-build/solutions/step3-solution.md
  docker/challenge-docker-multi-stage-build/step1.md
  docker/challenge-docker-multi-stage-build/step2.md
  docker/challenge-docker-multi-stage-build/step3.md
  docker/challenge-docker-multi-stage-build/verify1-1.sh
  docker/challenge-docker-multi-stage-build/verify1-2.sh
  docker/challenge-docker-multi-stage-build/verify1-3.sh
  docker/challenge-docker-multi-stage-build/verify2-1.sh
  docker/challenge-docker-multi-stage-build/verify2-2.sh
  docker/challenge-docker-multi-stage-build/verify3.sh
Labels: Test Completed, No Repair

#672 Add challenge connect to running container
  docker/challenge-connect-to-running-container/assets/challenge-connect-to-running-container-1.png
  docker/challenge-connect-to-running-container/assets/challenge-connect-to-running-container-2.png
  docker/challenge-connect-to-running-container/assets/challenge-connect-to-running-container-3.png
  docker/challenge-connect-to-running-container/assets/challenge-connect-to-running-container-4-1.png
  docker/challenge-connect-to-running-container/assets/challenge-connect-to-running-container-4-2.png
  docker/challenge-connect-to-running-container/assets/challenge-connect-to-running-container-4-3.png
  docker/challenge-connect-to-running-container/finish.md
  docker/challenge-connect-to-running-container/index.json
  docker/challenge-connect-to-running-container/intro.md
  docker/challenge-connect-to-running-container/setup.sh
  docker/challenge-connect-to-running-container/solutions/step1-solution.md
  docker/challenge-connect-to-running-container/solutions/step2-solution.md
  docker/challenge-connect-to-running-container/solutions/step3-solution.md
  docker/challenge-connect-to-running-container/solutions/step4-solution.md
  docker/challenge-connect-to-running-container/step1.md
  docker/challenge-connect-to-running-container/step2.md
  docker/challenge-connect-to-running-container/step3.md
  docker/challenge-connect-to-running-container/step4.md
  docker/challenge-connect-to-running-container/verify1.sh
  docker/challenge-connect-to-running-container/verify2.sh
  docker/challenge-connect-to-running-container/verify3.sh
  docker/challenge-connect-to-running-container/verify4-1.sh
  docker/challenge-connect-to-running-container/verify4-2.sh
  docker/challenge-connect-to-running-container/verify4-3.sh
Labels: Test Completed, No Repair

#671 Add challenge file copy for containers
  docker/challenge-file-copy-for-containers/assets/challenge-file-copy-for-containers-1-1.png
  docker/challenge-file-copy-for-containers/assets/challenge-file-copy-for-containers-1-2.png
  docker/challenge-file-copy-for-containers/assets/challenge-file-copy-for-containers-1-3.png
  docker/challenge-file-copy-for-containers/assets/challenge-file-copy-for-containers-2-1.png
  docker/challenge-file-copy-for-containers/assets/challenge-file-copy-for-containers-2-2.png
  docker/challenge-file-copy-for-containers/assets/challenge-file-copy-for-containers-2-3.png
  docker/challenge-file-copy-for-containers/assets/challenge-file-copy-for-containers-3-1.png
  docker/challenge-file-copy-for-containers/assets/challenge-file-copy-for-containers-3-2.png
  docker/challenge-file-copy-for-containers/assets/challenge-file-copy-for-containers-3-3.png
  docker/challenge-file-copy-for-containers/finish.md
  docker/challenge-file-copy-for-containers/index.json
  docker/challenge-file-copy-for-containers/intro.md
  docker/challenge-file-copy-for-containers/setup.sh
  docker/challenge-file-copy-for-containers/solutions/step1-solution.md
  docker/challenge-file-copy-for-containers/solutions/step2-solution.md
  docker/challenge-file-copy-for-containers/solutions/step3-solution.md
  docker/challenge-file-copy-for-containers/step1.md
  docker/challenge-file-copy-for-containers/step2.md
  docker/challenge-file-copy-for-containers/step3.md
  docker/challenge-file-copy-for-containers/verify1-1.sh
  docker/challenge-file-copy-for-containers/verify1-2.sh
  docker/challenge-file-copy-for-containers/verify1-3.sh
  docker/challenge-file-copy-for-containers/verify2-1.sh
  docker/challenge-file-copy-for-containers/verify2-2.sh
  docker/challenge-file-copy-for-containers/verify2-3.sh
  docker/challenge-file-copy-for-containers/verify3-1.sh
  docker/challenge-file-copy-for-containers/verify3-2.sh
  docker/challenge-file-copy-for-containers/verify3-3.sh
Labels: Test Completed, No Repair

#642 Lab networking pods with service
  kubernetes/lab-networking-pods-with-services/finish.md
  kubernetes/lab-networking-pods-with-services/index.json
  kubernetes/lab-networking-pods-with-services/intro.md
  kubernetes/lab-networking-pods-with-services/setup.sh
  kubernetes/lab-networking-pods-with-services/step1.md
  kubernetes/lab-networking-pods-with-services/step2.md
  kubernetes/lab-networking-pods-with-services/step3.md
  kubernetes/lab-networking-pods-with-services/step4.md
  kubernetes/lab-networking-pods-with-services/step5.md
  kubernetes/lab-networking-pods-with-services/verify1.sh
  kubernetes/lab-networking-pods-with-services/verify2.sh
  kubernetes/lab-networking-pods-with-services/verify3-1.sh
  kubernetes/lab-networking-pods-with-services/verify3-2.sh
  kubernetes/lab-networking-pods-with-services/verify4.sh
  kubernetes/lab-networking-pods-with-services/verify5-1.sh
  kubernetes/lab-networking-pods-with-services/verify5-2.sh
Labels: Test Completed, No Repair

#681 add challenge-docker-create-command
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-1-1.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-1-2.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-1-3.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-2-1.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-2-2.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-3-1.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-3-2.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-4-1.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-4-2.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-5-1.png
  docker/challenge-docker-create-command/assets/challenge-docker-create-command-5-2.png
  docker/challenge-docker-create-command/finish.md
  docker/challenge-docker-create-command/index.json
  docker/challenge-docker-create-command/intro.md
  docker/challenge-docker-create-command/setup.sh
  docker/challenge-docker-create-command/solutions/step1-solution.md
  docker/challenge-docker-create-command/solutions/step2-solution.md
  docker/challenge-docker-create-command/solutions/step3-solution.md
  docker/challenge-docker-create-command/solutions/step4-solution.md
  docker/challenge-docker-create-command/solutions/step5-solution.md
  docker/challenge-docker-create-command/step1.md
  docker/challenge-docker-create-command/step2.md
  docker/challenge-docker-create-command/step3.md
  docker/challenge-docker-create-command/step4.md
  docker/challenge-docker-create-command/step5.md
  docker/challenge-docker-create-command/verify1.sh
  docker/challenge-docker-create-command/verify2.sh
  docker/challenge-docker-create-command/verify3-1.sh
  docker/challenge-docker-create-command/verify3-2.sh
  docker/challenge-docker-create-command/verify3-3.sh
  docker/challenge-docker-create-command/verify4.sh
  docker/challenge-docker-create-command/verify5.sh
Labels: Test Completed, Minor Repair

#645 Add lab kubernetes limit range
  kubernetes/lab-kubernetes-limit-range/finish.md
  kubernetes/lab-kubernetes-limit-range/index.json
  kubernetes/lab-kubernetes-limit-range/intro.md
  kubernetes/lab-kubernetes-limit-range/setup.sh
  kubernetes/lab-kubernetes-limit-range/step1.md
  kubernetes/lab-kubernetes-limit-range/step2.md
  kubernetes/lab-kubernetes-limit-range/step3.md
  kubernetes/lab-kubernetes-limit-range/step4.md
  kubernetes/lab-kubernetes-limit-range/verify1-1.sh
  kubernetes/lab-kubernetes-limit-range/verify1-2.sh
  kubernetes/lab-kubernetes-limit-range/verify1-3.sh
  kubernetes/lab-kubernetes-limit-range/verify2-1.sh
  kubernetes/lab-kubernetes-limit-range/verify2-2.sh
  kubernetes/lab-kubernetes-limit-range/verify2-3.sh
  kubernetes/lab-kubernetes-limit-range/verify3-1.sh
  kubernetes/lab-kubernetes-limit-range/verify3-2.sh
  kubernetes/lab-kubernetes-limit-range/verify4-1.sh
  kubernetes/lab-kubernetes-limit-range/verify4-2.sh
Labels: Test Completed, Minor Repair

#631 Add challenge-basic-tqdm-usage
  python/challenge-basic-tqdm-usage/assets/function_runner.py
  python/challenge-basic-tqdm-usage/assets/function_runner_test.py
  python/challenge-basic-tqdm-usage/assets/list_length_updater.py
  python/challenge-basic-tqdm-usage/assets/list_length_updater_test.py
  python/challenge-basic-tqdm-usage/assets/range_progress.py
  python/challenge-basic-tqdm-usage/assets/range_progress_test.py
  python/challenge-basic-tqdm-usage/finish.md
  python/challenge-basic-tqdm-usage/index.json
  python/challenge-basic-tqdm-usage/intro.md
  python/challenge-basic-tqdm-usage/setup.sh
  python/challenge-basic-tqdm-usage/solutions/step1-solution.md
  python/challenge-basic-tqdm-usage/solutions/step2-solution.md
  python/challenge-basic-tqdm-usage/solutions/step3-solution.md
  python/challenge-basic-tqdm-usage/step1.md
  python/challenge-basic-tqdm-usage/step2.md
  python/challenge-basic-tqdm-usage/step3.md
  python/challenge-basic-tqdm-usage/verify1.sh
  python/challenge-basic-tqdm-usage/verify2.sh
  python/challenge-basic-tqdm-usage/verify3.sh
Labels: Test Completed, Minor Repair

#630 Add lab kubernetes resource quota
  kubernetes/lab-kubernetes-resource-quota/finish.md
  kubernetes/lab-kubernetes-resource-quota/index.json
  kubernetes/lab-kubernetes-resource-quota/intro.md
  kubernetes/lab-kubernetes-resource-quota/setup.sh
  kubernetes/lab-kubernetes-resource-quota/step1.md
  kubernetes/lab-kubernetes-resource-quota/step2.md
  kubernetes/lab-kubernetes-resource-quota/step3.md
  kubernetes/lab-kubernetes-resource-quota/step4.md
  kubernetes/lab-kubernetes-resource-quota/verify1-1.sh
  kubernetes/lab-kubernetes-resource-quota/verify1-2.sh
  kubernetes/lab-kubernetes-resource-quota/verify1-3.sh
  kubernetes/lab-kubernetes-resource-quota/verify2-1.sh
  kubernetes/lab-kubernetes-resource-quota/verify2-2.sh
  kubernetes/lab-kubernetes-resource-quota/verify2-3.sh
  kubernetes/lab-kubernetes-resource-quota/verify3-1.sh
  kubernetes/lab-kubernetes-resource-quota/verify3-2.sh
  kubernetes/lab-kubernetes-resource-quota/verify4-1.sh
  kubernetes/lab-kubernetes-resource-quota/verify4-2.sh
Labels: Test Completed, Minor Repair

#640 challenge-file-system-operations-with-os-module
  python/challenge-file-system-operations-with-os-module/assets/batch_file_renamer.py
  python/challenge-file-system-operations-with-os-module/assets/batch_file_renamer_test.py
  python/challenge-file-system-operations-with-os-module/assets/disk_space_analyzer.py
  python/challenge-file-system-operations-with-os-module/assets/disk_space_analyzer_test.py
  python/challenge-file-system-operations-with-os-module/assets/duplicate_file_finder.py
  python/challenge-file-system-operations-with-os-module/assets/duplicate_file_finder_test.py
  python/challenge-file-system-operations-with-os-module/assets/file_extension_statistics.py
  python/challenge-file-system-operations-with-os-module/assets/file_extension_statistics_test.py
  python/challenge-file-system-operations-with-os-module/assets/file_search_engine.py
  python/challenge-file-system-operations-with-os-module/assets/file_search_engine_test.py
  python/challenge-file-system-operations-with-os-module/finish.md
  python/challenge-file-system-operations-with-os-module/index.json
  python/challenge-file-system-operations-with-os-module/intro.md
  python/challenge-file-system-operations-with-os-module/setup.sh
  python/challenge-file-system-operations-with-os-module/solutions/batch_file_renamer.py
  python/challenge-file-system-operations-with-os-module/solutions/disk_space_analyzer.py
  python/challenge-file-system-operations-with-os-module/solutions/duplicate_file_finder.py
  python/challenge-file-system-operations-with-os-module/solutions/file_extension_statistics.py
  python/challenge-file-system-operations-with-os-module/solutions/file_search_engine.py
  python/challenge-file-system-operations-with-os-module/step1.md
  python/challenge-file-system-operations-with-os-module/step2.md
  python/challenge-file-system-operations-with-os-module/step3.md
  python/challenge-file-system-operations-with-os-module/step4.md
  python/challenge-file-system-operations-with-os-module/step5.md
  python/challenge-file-system-operations-with-os-module/verify1.sh
  python/challenge-file-system-operations-with-os-module/verify2.sh
  python/challenge-file-system-operations-with-os-module/verify3.sh
  python/challenge-file-system-operations-with-os-module/verify4.sh
  python/challenge-file-system-operations-with-os-module/verify5.sh
Labels: Test Completed, Major Repair

#684 add challenge-flexible-card in css
  css/challenge-flexible-card/assets/.puppeteerrc.cjs
  css/challenge-flexible-card/assets/finished.png
  css/challenge-flexible-card/assets/flexible_card.css
  css/challenge-flexible-card/assets/flexible_card.html
  css/challenge-flexible-card/assets/test_flexible_card.js
  css/challenge-flexible-card/assets/unfinished.png
  css/challenge-flexible-card/finish.md
  css/challenge-flexible-card/index.json
  css/challenge-flexible-card/intro.md
  css/challenge-flexible-card/setup.sh
  css/challenge-flexible-card/solutions/flexible_card.css
  css/challenge-flexible-card/step1.md
  css/challenge-flexible-card/verify0.sh
  css/challenge-flexible-card/verify1.sh
Labels: Test Completed, Minor Repair

#669 add Challenge docker search command
  docker/challenge-docker-search-command/assets/challenge-docker-search-command-1-1.png
  docker/challenge-docker-search-command/assets/challenge-docker-search-command-2-1.png
  docker/challenge-docker-search-command/assets/challenge-docker-search-command-3-1.png
  docker/challenge-docker-search-command/assets/challenge-docker-search-command-4-1.png
  docker/challenge-docker-search-command/finish.md
  docker/challenge-docker-search-command/index.json
  docker/challenge-docker-search-command/intro.md
  docker/challenge-docker-search-command/setup.sh
  docker/challenge-docker-search-command/solutions/step1-solution.md
  docker/challenge-docker-search-command/solutions/step2-solution.md
  docker/challenge-docker-search-command/solutions/step3-solution.md
  docker/challenge-docker-search-command/solutions/step4-solution.md
  docker/challenge-docker-search-command/step1.md
  docker/challenge-docker-search-command/step2.md
  docker/challenge-docker-search-command/step3.md
  docker/challenge-docker-search-command/step4.md
  docker/challenge-docker-search-command/verify1.sh
  docker/challenge-docker-search-command/verify2.sh
  docker/challenge-docker-search-command/verify3.sh
  docker/challenge-docker-search-command/verify4.sh
Labels: Test Completed, Minor Repair

#692 Add challenge docker lifecycle management
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-1-1.png
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-1-4.png
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-2-1.png
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-2-2.png
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-2-3.png
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-3-1.png
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-3-2.png
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-3-3.png
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-4-1.png
  docker/challenge-docker-lifecycle-management/assets/challenge-docker-lifecycle-management-4-2.png
  docker/challenge-docker-lifecycle-management/finish.md
  docker/challenge-docker-lifecycle-management/index.json
  docker/challenge-docker-lifecycle-management/intro.md
  docker/challenge-docker-lifecycle-management/setup.sh
  docker/challenge-docker-lifecycle-management/solutions/step1-solution.md
  docker/challenge-docker-lifecycle-management/solutions/step2-solution.md
  docker/challenge-docker-lifecycle-management/solutions/step3-solution.md
  docker/challenge-docker-lifecycle-management/solutions/step4-solution.md
  docker/challenge-docker-lifecycle-management/step1.md
  docker/challenge-docker-lifecycle-management/step2.md
  docker/challenge-docker-lifecycle-management/step3.md
  docker/challenge-docker-lifecycle-management/step4.md
  docker/challenge-docker-lifecycle-management/verify1-1.sh
  docker/challenge-docker-lifecycle-management/verify1-2.sh
  docker/challenge-docker-lifecycle-management/verify1-3.sh
  docker/challenge-docker-lifecycle-management/verify1-4.sh
  docker/challenge-docker-lifecycle-management/verify2-1.sh
  docker/challenge-docker-lifecycle-management/verify2-2.sh
  docker/challenge-docker-lifecycle-management/verify3-1.sh
  docker/challenge-docker-lifecycle-management/verify3-2.sh
  docker/challenge-docker-lifecycle-management/verify3-3.sh
  docker/challenge-docker-lifecycle-management/verify4-1.sh
  docker/challenge-docker-lifecycle-management/verify4-2.sh
  docker/challenge-docker-lifecycle-management/verify4-3.sh
Labels: Test Completed, No Repair

#709 Add challenge configuring apps with secrets
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-1-1.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-1-2.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-1-3.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-2-1.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-2-2.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-2-3.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-3-1.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-3-2.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-4-1.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-4-2.png
  kubernetes/challenge-configuring-apps-with-secrets/assets/challenge-configuring-apps-with-secrets-5.png
  kubernetes/challenge-configuring-apps-with-secrets/finish.md
  kubernetes/challenge-configuring-apps-with-secrets/index.json
  kubernetes/challenge-configuring-apps-with-secrets/intro.md
  kubernetes/challenge-configuring-apps-with-secrets/setup.sh
  kubernetes/challenge-configuring-apps-with-secrets/solutions/step1-solution.md
  kubernetes/challenge-configuring-apps-with-secrets/solutions/step2-solution.md
  kubernetes/challenge-configuring-apps-with-secrets/solutions/step3-solution.md
  kubernetes/challenge-configuring-apps-with-secrets/solutions/step4-solution.md
  kubernetes/challenge-configuring-apps-with-secrets/solutions/step5-solution.md
  kubernetes/challenge-configuring-apps-with-secrets/step1.md
  kubernetes/challenge-configuring-apps-with-secrets/step2.md
  kubernetes/challenge-configuring-apps-with-secrets/step3.md
  kubernetes/challenge-configuring-apps-with-secrets/step4.md
  kubernetes/challenge-configuring-apps-with-secrets/step5.md
  kubernetes/challenge-configuring-apps-with-secrets/verify1-1.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify1-2.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify1-3.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify2-1.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify2-2.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify2-3.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify3-1.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify3-2.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify4-1.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify4-2.sh
  kubernetes/challenge-configuring-apps-with-secrets/verify5.sh
Labels: Test Completed, No Repair

#700 Add challenge running containers in pods
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-1-1.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-1-2.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-2-1.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-2-2.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-3-1.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-3-2.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-4-1.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-4-2.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-4-3.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-5-1.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-5-2.png
  kubernetes/challenge-running-containers-in-pods/assets/challenge-running-containers-in-pods-5-3.png
  kubernetes/challenge-running-containers-in-pods/finish.md
  kubernetes/challenge-running-containers-in-pods/index.json
  kubernetes/challenge-running-containers-in-pods/intro.md
  kubernetes/challenge-running-containers-in-pods/setup.sh
  kubernetes/challenge-running-containers-in-pods/solutions/step1-solution.md
  kubernetes/challenge-running-containers-in-pods/solutions/step2-solution.md
  kubernetes/challenge-running-containers-in-pods/solutions/step3-solution.md
  kubernetes/challenge-running-containers-in-pods/solutions/step4-solution.md
  kubernetes/challenge-running-containers-in-pods/solutions/step5-solution.md
  kubernetes/challenge-running-containers-in-pods/step1.md
  kubernetes/challenge-running-containers-in-pods/step2.md
  kubernetes/challenge-running-containers-in-pods/step3.md
  kubernetes/challenge-running-containers-in-pods/step4.md
  kubernetes/challenge-running-containers-in-pods/step5.md
  kubernetes/challenge-running-containers-in-pods/verify1-1.sh
  kubernetes/challenge-running-containers-in-pods/verify1-2.sh
  kubernetes/challenge-running-containers-in-pods/verify2-1.sh
  kubernetes/challenge-running-containers-in-pods/verify2-2.sh
  kubernetes/challenge-running-containers-in-pods/verify3-1.sh
  kubernetes/challenge-running-containers-in-pods/verify3-2.sh
  kubernetes/challenge-running-containers-in-pods/verify4-1.sh
  kubernetes/challenge-running-containers-in-pods/verify4-2.sh
  kubernetes/challenge-running-containers-in-pods/verify4-3.sh
  kubernetes/challenge-running-containers-in-pods/verify5-1.sh
  kubernetes/challenge-running-containers-in-pods/verify5-2.sh
  kubernetes/challenge-running-containers-in-pods/verify5-3.sh
Labels: Test Completed, No Repair

#708 Add challenge manage kubernetes deployment
  kubernetes/challenge-manage-kubernetes-deployment/assets/challenge-manage-kubernetes-deployment-1-1.png
  kubernetes/challenge-manage-kubernetes-deployment/assets/challenge-manage-kubernetes-deployment-1-2.png
  kubernetes/challenge-manage-kubernetes-deployment/assets/challenge-manage-kubernetes-deployment-2.png
  kubernetes/challenge-manage-kubernetes-deployment/assets/challenge-manage-kubernetes-deployment-3-1.png
  kubernetes/challenge-manage-kubernetes-deployment/assets/challenge-manage-kubernetes-deployment-3-2.png
  kubernetes/challenge-manage-kubernetes-deployment/assets/challenge-manage-kubernetes-deployment-4-1.png
  kubernetes/challenge-manage-kubernetes-deployment/assets/challenge-manage-kubernetes-deployment-4-2.png
  kubernetes/challenge-manage-kubernetes-deployment/assets/challenge-manage-kubernetes-deployment-5.png
  kubernetes/challenge-manage-kubernetes-deployment/finish.md
  kubernetes/challenge-manage-kubernetes-deployment/index.json
  kubernetes/challenge-manage-kubernetes-deployment/intro.md
  kubernetes/challenge-manage-kubernetes-deployment/setup.sh
  kubernetes/challenge-manage-kubernetes-deployment/solutions/step1-solution.md
  kubernetes/challenge-manage-kubernetes-deployment/solutions/step2-solution.md
  kubernetes/challenge-manage-kubernetes-deployment/solutions/step3-solution.md
  kubernetes/challenge-manage-kubernetes-deployment/solutions/step4-solution.md
  kubernetes/challenge-manage-kubernetes-deployment/solutions/step5-solution.md
  kubernetes/challenge-manage-kubernetes-deployment/step1.md
  kubernetes/challenge-manage-kubernetes-deployment/step2.md
  kubernetes/challenge-manage-kubernetes-deployment/step3.md
  kubernetes/challenge-manage-kubernetes-deployment/step4.md
  kubernetes/challenge-manage-kubernetes-deployment/step5.md
  kubernetes/challenge-manage-kubernetes-deployment/verify1-1.sh
  kubernetes/challenge-manage-kubernetes-deployment/verify1-2.sh
  kubernetes/challenge-manage-kubernetes-deployment/verify1-3.sh
  kubernetes/challenge-manage-kubernetes-deployment/verify2-1.sh
  kubernetes/challenge-manage-kubernetes-deployment/verify2-2.sh
  kubernetes/challenge-manage-kubernetes-deployment/verify3-1.sh
  kubernetes/challenge-manage-kubernetes-deployment/verify3-2.sh
  kubernetes/challenge-manage-kubernetes-deployment/verify4-1.sh
  kubernetes/challenge-manage-kubernetes-deployment/verify4-2.sh
  kubernetes/challenge-manage-kubernetes-deployment/verify5.sh
Labels: Test Completed, No Repair

#663 finish the regular-expressions-mastery challenge
  python/challenge-regular-expressions-mastery/assets/counting_occurrences.py
  python/challenge-regular-expressions-mastery/assets/counting_occurrences_test.py
  python/challenge-regular-expressions-mastery/assets/email_obfuscation.py
  python/challenge-regular-expressions-mastery/assets/email_obfuscation_test.py
  python/challenge-regular-expressions-mastery/assets/extracting_information.py
  python/challenge-regular-expressions-mastery/assets/extracting_information_test.py
  python/challenge-regular-expressions-mastery/assets/extracting_url.py
  python/challenge-regular-expressions-mastery/assets/extracting_url_test.py
  python/challenge-regular-expressions-mastery/assets/password_validator.py
  python/challenge-regular-expressions-mastery/assets/password_validator_test.py
  python/challenge-regular-expressions-mastery/assets/web_log_analysis.py
  python/challenge-regular-expressions-mastery/assets/web_log_analysis_test.py
  python/challenge-regular-expressions-mastery/finish.md
  python/challenge-regular-expressions-mastery/index.json
  python/challenge-regular-expressions-mastery/intro.md
  python/challenge-regular-expressions-mastery/setup.sh
  python/challenge-regular-expressions-mastery/solutions/counting_occurrences.py
  python/challenge-regular-expressions-mastery/solutions/email_obfuscation.py
  python/challenge-regular-expressions-mastery/solutions/extracting_information.py
  python/challenge-regular-expressions-mastery/solutions/extracting_url.py
  python/challenge-regular-expressions-mastery/solutions/password_validator.py
  python/challenge-regular-expressions-mastery/solutions/web_log_analysis.py
  python/challenge-regular-expressions-mastery/step1.md
  python/challenge-regular-expressions-mastery/step2.md
  python/challenge-regular-expressions-mastery/step3.md
  python/challenge-regular-expressions-mastery/step4.md
  python/challenge-regular-expressions-mastery/step5.md
  python/challenge-regular-expressions-mastery/step6.md
  python/challenge-regular-expressions-mastery/verify1.sh
  python/challenge-regular-expressions-mastery/verify2.sh
  python/challenge-regular-expressions-mastery/verify3.sh
  python/challenge-regular-expressions-mastery/verify4.sh
  python/challenge-regular-expressions-mastery/verify5.sh
  python/challenge-regular-expressions-mastery/verify6.sh
Labels: Test Completed, Major Repair

#689 Add challenge deploy containerized applications
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-1-1.png
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-1-3.png
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-1-4.png
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-2-1.png
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-2-4.png
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-2-5.png
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-3-1.png
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-3-4.png
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-3-5.png
  docker/challenge-deploy-containerized-applications/assets/challenge-deploy-containerized-applications-3-6.png
  docker/challenge-deploy-containerized-applications/finish.md
  docker/challenge-deploy-containerized-applications/index.json
  docker/challenge-deploy-containerized-applications/intro.md
  docker/challenge-deploy-containerized-applications/setup.sh
  docker/challenge-deploy-containerized-applications/solutions/step1-solution.md
  docker/challenge-deploy-containerized-applications/solutions/step2-solution.md
  docker/challenge-deploy-containerized-applications/solutions/step3-solution.md
  docker/challenge-deploy-containerized-applications/step1.md
  docker/challenge-deploy-containerized-applications/step2.md
  docker/challenge-deploy-containerized-applications/step3.md
  docker/challenge-deploy-containerized-applications/verify1-1.sh
  docker/challenge-deploy-containerized-applications/verify1-2.sh
  docker/challenge-deploy-containerized-applications/verify1-3.sh
  docker/challenge-deploy-containerized-applications/verify1-4.sh
  docker/challenge-deploy-containerized-applications/verify2-1.sh
  docker/challenge-deploy-containerized-applications/verify2-2.sh
  docker/challenge-deploy-containerized-applications/verify2-3.sh
  docker/challenge-deploy-containerized-applications/verify2-4.sh
  docker/challenge-deploy-containerized-applications/verify2-5.sh
  docker/challenge-deploy-containerized-applications/verify3-1.sh
  docker/challenge-deploy-containerized-applications/verify3-2.sh
  docker/challenge-deploy-containerized-applications/verify3-3.sh
  docker/challenge-deploy-containerized-applications/verify3-4.sh
  docker/challenge-deploy-containerized-applications/verify3-5.sh
  docker/challenge-deploy-containerized-applications/verify3-6.sh
Labels: Test Completed

#691 Add challenge package and run applications
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-1-1.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-1-3.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-2-1.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-2-5.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-2-6.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-2-7.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-3-1.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-3-2.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-3-3.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-3-4.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-3-5.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-3-6.png
  docker/challenge-package-and-run-applications/assets/challenge-package-and-run-applications-3-7.png
  docker/challenge-package-and-run-applications/finish.md
  docker/challenge-package-and-run-applications/index.json
  docker/challenge-package-and-run-applications/intro.md
  docker/challenge-package-and-run-applications/setup.sh
  docker/challenge-package-and-run-applications/solutions/step1-solution.md
  docker/challenge-package-and-run-applications/solutions/step2-solution.md
  docker/challenge-package-and-run-applications/solutions/step3-solution.md
  docker/challenge-package-and-run-applications/step1.md
  docker/challenge-package-and-run-applications/step2.md
  docker/challenge-package-and-run-applications/step3.md
  docker/challenge-package-and-run-applications/verify1.sh
  docker/challenge-package-and-run-applications/verify2-1.sh
  docker/challenge-package-and-run-applications/verify2-2.sh
  docker/challenge-package-and-run-applications/verify2-3.sh
  docker/challenge-package-and-run-applications/verify2-4.sh
  docker/challenge-package-and-run-applications/verify2-5.sh
  docker/challenge-package-and-run-applications/verify2-6.sh
  docker/challenge-package-and-run-applications/verify3-1.sh
  docker/challenge-package-and-run-applications/verify3-2.sh
  docker/challenge-package-and-run-applications/verify3-3.sh
  docker/challenge-package-and-run-applications/verify3-4.sh
  docker/challenge-package-and-run-applications/verify3-5.sh
  docker/challenge-package-and-run-applications/verify3-6.sh
Labels: Test Completed

#647 Add lab docker local network
  docker/lab-docker-local-network/finish.md
  docker/lab-docker-local-network/index.json
  docker/lab-docker-local-network/intro.md
  docker/lab-docker-local-network/setup.sh
  docker/lab-docker-local-network/step1.md
  docker/lab-docker-local-network/step2.md
  docker/lab-docker-local-network/step3.md
  docker/lab-docker-local-network/verify1-1.sh
  docker/lab-docker-local-network/verify1-2.sh
  docker/lab-docker-local-network/verify1-3.sh
  docker/lab-docker-local-network/verify1-4.sh
  docker/lab-docker-local-network/verify2-1.sh
  docker/lab-docker-local-network/verify2-2.sh
  docker/lab-docker-local-network/verify2-3.sh
  docker/lab-docker-local-network/verify2-4.sh
  docker/lab-docker-local-network/verify3-1.sh
  docker/lab-docker-local-network/verify3-2.sh
  docker/lab-docker-local-network/verify3-3.sh
Labels: Test Completed

#694 add challenge-dataframe-combiner
  pandas/challenge-dataframe-combiner/assets/concatenating_dataframes.py
  pandas/challenge-dataframe-combiner/assets/concatenating_dataframes_test.py
  pandas/challenge-dataframe-combiner/assets/create_dataframe.py
  pandas/challenge-dataframe-combiner/assets/create_dataframe_test.py
  pandas/challenge-dataframe-combiner/assets/joining_dataframes.py
  pandas/challenge-dataframe-combiner/assets/joining_dataframes_test.py
  pandas/challenge-dataframe-combiner/assets/merging_dataframes.py
  pandas/challenge-dataframe-combiner/assets/merging_dataframes_test.py
  pandas/challenge-dataframe-combiner/finish.md
  pandas/challenge-dataframe-combiner/index.json
  pandas/challenge-dataframe-combiner/intro.md
  pandas/challenge-dataframe-combiner/setup.sh
  pandas/challenge-dataframe-combiner/solutions/concatenating_dataframes.py
  pandas/challenge-dataframe-combiner/solutions/create_dataframe.py
  pandas/challenge-dataframe-combiner/solutions/joining_dataframes.py
  pandas/challenge-dataframe-combiner/solutions/merging_dataframes.py
  pandas/challenge-dataframe-combiner/step1.md
  pandas/challenge-dataframe-combiner/step2.md
  pandas/challenge-dataframe-combiner/step3.md
  pandas/challenge-dataframe-combiner/step4.md
  pandas/challenge-dataframe-combiner/verify1.sh
  pandas/challenge-dataframe-combiner/verify2.sh
  pandas/challenge-dataframe-combiner/verify3.sh
  pandas/challenge-dataframe-combiner/verify4.sh
Labels: Test Completed, Minor Repair

#764 Add challenge deploying local docker registry
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-1-1.png
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-1-2.png
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-1-3.png
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-1-4.png
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-2-1.png
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-2-2.png
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-2-3.png
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-3-1.png
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-3-2.png
  docker/challenge-deploying-local-docker-registry/assets/challenge-deploying-local-docker-registry-3-3.png
  docker/challenge-deploying-local-docker-registry/finish.md
  docker/challenge-deploying-local-docker-registry/index.json
  docker/challenge-deploying-local-docker-registry/intro.md
  docker/challenge-deploying-local-docker-registry/setup.sh
  docker/challenge-deploying-local-docker-registry/solutions/step1-solution.md
  docker/challenge-deploying-local-docker-registry/solutions/step2-solution.md
  docker/challenge-deploying-local-docker-registry/solutions/step3-solution.md
  docker/challenge-deploying-local-docker-registry/step1.md
  docker/challenge-deploying-local-docker-registry/step2.md
  docker/challenge-deploying-local-docker-registry/step3.md
  docker/challenge-deploying-local-docker-registry/verify1-1.sh
  docker/challenge-deploying-local-docker-registry/verify1-2.sh
  docker/challenge-deploying-local-docker-registry/verify1-3.sh
  docker/challenge-deploying-local-docker-registry/verify1-4.sh
  docker/challenge-deploying-local-docker-registry/verify2-1.sh
  docker/challenge-deploying-local-docker-registry/verify2-2.sh
  docker/challenge-deploying-local-docker-registry/verify2-3.sh
  docker/challenge-deploying-local-docker-registry/verify3-1.sh
  docker/challenge-deploying-local-docker-registry/verify3-2.sh
  docker/challenge-deploying-local-docker-registry/verify3-3.sh
Labels: Test Completed, No Repair

#775 Add challenge-fruit-arrangement in css
  css/challenge-fruit-arrangement/assets/.puppeteerrc.cjs
  css/challenge-fruit-arrangement/assets/1.png
  css/challenge-fruit-arrangement/assets/2.png
  css/challenge-fruit-arrangement/assets/314482target.png
  css/challenge-fruit-arrangement/assets/finished.png
  css/challenge-fruit-arrangement/assets/index.css
  css/challenge-fruit-arrangement/assets/index.html
  css/challenge-fruit-arrangement/assets/test_fruit_arrangement.js
  css/challenge-fruit-arrangement/assets/unfinished.png
  css/challenge-fruit-arrangement/finish.md
  css/challenge-fruit-arrangement/index.json
  css/challenge-fruit-arrangement/intro.md
  css/challenge-fruit-arrangement/setup.sh
  css/challenge-fruit-arrangement/solutions/index.css
  css/challenge-fruit-arrangement/step1.md
  css/challenge-fruit-arrangement/verify0.sh
  css/challenge-fruit-arrangement/verify1-1.sh
  css/challenge-fruit-arrangement/verify1-2.sh
Labels: Test Completed, Minor Repair

#769 Add challenge-fresh-vegetables in css
  css/challenge-fresh-vegetables/assets/.puppeteerrc.cjs
  css/challenge-fresh-vegetables/assets/box1Target.png
  css/challenge-fresh-vegetables/assets/box2Target.png
  css/challenge-fresh-vegetables/assets/box3Target.png
  css/challenge-fresh-vegetables/assets/cabbage.svg
  css/challenge-fresh-vegetables/assets/carrot.svg
  css/challenge-fresh-vegetables/assets/chili.svg
  css/challenge-fresh-vegetables/assets/finished.png
  css/challenge-fresh-vegetables/assets/index.html
  css/challenge-fresh-vegetables/assets/style.css
  css/challenge-fresh-vegetables/assets/test_fresh_vegetables.js
  css/challenge-fresh-vegetables/assets/unfinished.png
  css/challenge-fresh-vegetables/finish.md
  css/challenge-fresh-vegetables/index.json
  css/challenge-fresh-vegetables/intro.md
  css/challenge-fresh-vegetables/setup.sh
  css/challenge-fresh-vegetables/solutions/style.css
  css/challenge-fresh-vegetables/step1.md
  css/challenge-fresh-vegetables/verify0.sh
  css/challenge-fresh-vegetables/verify1-1.sh
  css/challenge-fresh-vegetables/verify1-2.sh
Labels: Test Completed, Minor Repair

#767 Add challenge-unfold-your-fan in css
  css/challenge-unfold-your-fan/assets/.puppeteerrc.cjs
  css/challenge-unfold-your-fan/assets/effect.gif
  css/challenge-unfold-your-fan/assets/index.html
  css/challenge-unfold-your-fan/assets/style.css
  css/challenge-unfold-your-fan/assets/test_unfold_your_fan.js
  css/challenge-unfold-your-fan/assets/unfinished.png
  css/challenge-unfold-your-fan/finish.md
  css/challenge-unfold-your-fan/index.json
  css/challenge-unfold-your-fan/intro.md
  css/challenge-unfold-your-fan/setup.sh
  css/challenge-unfold-your-fan/solutions/style.css
  css/challenge-unfold-your-fan/step1.md
  css/challenge-unfold-your-fan/verify0.sh
  css/challenge-unfold-your-fan/verify1-1.sh
  css/challenge-unfold-your-fan/verify1-2.sh
Labels: Test Completed, Minor Repair

#777 Add challenge-fruit-platter in css
  css/challenge-fruit-platter/assets/.puppeteerrc.cjs
  css/challenge-fruit-platter/assets/apple.svg
  css/challenge-fruit-platter/assets/banana.svg
  css/challenge-fruit-platter/assets/blueplate.svg
  css/challenge-fruit-platter/assets/finished.png
  css/challenge-fruit-platter/assets/fruitTarget.png
  css/challenge-fruit-platter/assets/index.html
  css/challenge-fruit-platter/assets/pear.svg
  css/challenge-fruit-platter/assets/redplate.svg
  css/challenge-fruit-platter/assets/style.css
  css/challenge-fruit-platter/assets/test_fruit_platter.js
  css/challenge-fruit-platter/assets/unfinished.png
  css/challenge-fruit-platter/assets/yellowplate.svg
  css/challenge-fruit-platter/finish.md
  css/challenge-fruit-platter/index.json
  css/challenge-fruit-platter/intro.md
  css/challenge-fruit-platter/setup.sh
  css/challenge-fruit-platter/solutions/style.css
  css/challenge-fruit-platter/step1.md
  css/challenge-fruit-platter/verify0.sh
  css/challenge-fruit-platter/verify1-1.sh
  css/challenge-fruit-platter/verify1-2.sh
Labels: Test Completed, Minor Repair

#780 Add challenge-colour-changeable-light in es6
  es6/challenge-colour-changeable-light/assets/.puppeteerrc.cjs
  es6/challenge-colour-changeable-light/assets/effect.gif
  es6/challenge-colour-changeable-light/assets/greenlight.svg
  es6/challenge-colour-changeable-light/assets/index.html
  es6/challenge-colour-changeable-light/assets/light.svg
  es6/challenge-colour-changeable-light/assets/redlight.svg
  es6/challenge-colour-changeable-light/assets/test_colour_changeable_light.js
  es6/challenge-colour-changeable-light/assets/trafficlights.js
  es6/challenge-colour-changeable-light/assets/unfinished.png
  es6/challenge-colour-changeable-light/finish.md
  es6/challenge-colour-changeable-light/index.json
  es6/challenge-colour-changeable-light/intro.md
  es6/challenge-colour-changeable-light/setup.sh
  es6/challenge-colour-changeable-light/solutions/trafficlights.js
  es6/challenge-colour-changeable-light/step1.md
  es6/challenge-colour-changeable-light/verify0.sh
  es6/challenge-colour-changeable-light/verify1-1.sh
  es6/challenge-colour-changeable-light/verify1-2.sh
Labels: Test Completed, Minor Repair

#778 Add challenge deploying jenkins application
  docker/challenge-deploying-jenkins-application/assets/challenge-deploying-jenkins-application-1.png
  docker/challenge-deploying-jenkins-application/assets/challenge-deploying-jenkins-application-2.png
  docker/challenge-deploying-jenkins-application/assets/challenge-deploying-jenkins-application-3-2.png
  docker/challenge-deploying-jenkins-application/assets/challenge-deploying-jenkins-application-3-3.png
  docker/challenge-deploying-jenkins-application/finish.md
  docker/challenge-deploying-jenkins-application/index.json
  docker/challenge-deploying-jenkins-application/intro.md
  docker/challenge-deploying-jenkins-application/setup.sh
  docker/challenge-deploying-jenkins-application/solutions/step1-solution.md
  docker/challenge-deploying-jenkins-application/solutions/step2-solution.md
  docker/challenge-deploying-jenkins-application/solutions/step3-solution.md
  docker/challenge-deploying-jenkins-application/step1.md
  docker/challenge-deploying-jenkins-application/step2.md
  docker/challenge-deploying-jenkins-application/step3.md
  docker/challenge-deploying-jenkins-application/verify1.sh
  docker/challenge-deploying-jenkins-application/verify2.sh
  docker/challenge-deploying-jenkins-application/verify3.sh
Labels: Test Completed, Minor Repair

#770 Add challenge run pods with jobs and cronjobs
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/assets/challenge-run-pods-with-jobs-and-cronjobs-12.png
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/assets/challenge-run-pods-with-jobs-and-cronjobs-13.png
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/assets/challenge-run-pods-with-jobs-and-cronjobs-14.png
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/assets/challenge-run-pods-with-jobs-and-cronjobs-22.png
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/assets/challenge-run-pods-with-jobs-and-cronjobs-23.png
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/assets/challenge-run-pods-with-jobs-and-cronjobs-24.png
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/assets/challenge-run-pods-with-jobs-and-cronjobs-32.png
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/assets/challenge-run-pods-with-jobs-and-cronjobs-33.png
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/assets/challenge-run-pods-with-jobs-and-cronjobs-34.png
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/finish.md
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/index.json
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/intro.md
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/setup.sh
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/solutions/step1-solution.md
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/solutions/step2-solution.md
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/solutions/step3-solution.md
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/step1.md
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/step2.md
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/step3.md
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/verify1-1.sh
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/verify1-2.sh
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/verify1-3.sh
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/verify2-1.sh
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/verify2-3.sh
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/verify3-1.sh
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/verify3-2.sh
  kubernetes/challenge-run-pods-with-jobs-and-cronjobs/verify3-3.sh
Labels: Test Completed, Minor Repair

#765 Add challenge running pod with daemonsets
  kubernetes/challenge-running-pod-with-daemonsets/assets/challenge-running-pod-with-daemonsets-1.png
  kubernetes/challenge-running-pod-with-daemonsets/assets/challenge-running-pod-with-daemonsets-2.png
  kubernetes/challenge-running-pod-with-daemonsets/assets/challenge-running-pod-with-daemonsets-3-3.png
  kubernetes/challenge-running-pod-with-daemonsets/assets/challenge-running-pod-with-daemonsets-3.png
  kubernetes/challenge-running-pod-with-daemonsets/assets/challenge-running-pod-with-daemonsets-4.png
  kubernetes/challenge-running-pod-with-daemonsets/assets/challenge-running-pod-with-daemonsets-5-1.png
  kubernetes/challenge-running-pod-with-daemonsets/finish.md
  kubernetes/challenge-running-pod-with-daemonsets/index.json
  kubernetes/challenge-running-pod-with-daemonsets/intro.md
  kubernetes/challenge-running-pod-with-daemonsets/setup.sh
  kubernetes/challenge-running-pod-with-daemonsets/solutions/step1-solution.md
  kubernetes/challenge-running-pod-with-daemonsets/solutions/step2-solution.md
  kubernetes/challenge-running-pod-with-daemonsets/solutions/step3-solution.md
  kubernetes/challenge-running-pod-with-daemonsets/solutions/step4-solution.md
  kubernetes/challenge-running-pod-with-daemonsets/solutions/step5-solution.md
  kubernetes/challenge-running-pod-with-daemonsets/step1.md
  kubernetes/challenge-running-pod-with-daemonsets/step2.md
  kubernetes/challenge-running-pod-with-daemonsets/step3.md
  kubernetes/challenge-running-pod-with-daemonsets/step4.md
  kubernetes/challenge-running-pod-with-daemonsets/step5.md
  kubernetes/challenge-running-pod-with-daemonsets/verify1.sh
  kubernetes/challenge-running-pod-with-daemonsets/verify2.sh
  kubernetes/challenge-running-pod-with-daemonsets/verify3-1.sh
  kubernetes/challenge-running-pod-with-daemonsets/verify3-2.sh
  kubernetes/challenge-running-pod-with-daemonsets/verify4.sh
  kubernetes/challenge-running-pod-with-daemonsets/verify5.sh
Labels: Test Completed, Minor Repair

#790 Add challenge-gradient-background-generator in js
  js/challenge-gradient-background-generator/assets/.puppeteerrc.cjs
  js/challenge-gradient-background-generator/assets/finished.gif
  js/challenge-gradient-background-generator/assets/index.html
  js/challenge-gradient-background-generator/assets/index.js
  js/challenge-gradient-background-generator/assets/styles.css
  js/challenge-gradient-background-generator/assets/test_gradient_background.js
  js/challenge-gradient-background-generator/assets/unfinished.png
  js/challenge-gradient-background-generator/finish.md
  js/challenge-gradient-background-generator/index.json
  js/challenge-gradient-background-generator/intro.md
  js/challenge-gradient-background-generator/setup.sh
  js/challenge-gradient-background-generator/solutions/index.js
  js/challenge-gradient-background-generator/step1.md
  js/challenge-gradient-background-generator/verify0.sh
  js/challenge-gradient-background-generator/verify1-1.sh
  js/challenge-gradient-background-generator/verify1-2.sh
Labels: Test Completed

#794 Add challenge-flex-dice-layout in css
  css/challenge-flex-dice-layout/assets/.puppeteerrc.cjs
  css/challenge-flex-dice-layout/assets/157483target.png
  css/challenge-flex-dice-layout/assets/finished.png
  css/challenge-flex-dice-layout/assets/index.html
  css/challenge-flex-dice-layout/assets/reference.png
  css/challenge-flex-dice-layout/assets/test_flex_dice_layout.js
  css/challenge-flex-dice-layout/assets/unfinished.png
  css/challenge-flex-dice-layout/finish.md
  css/challenge-flex-dice-layout/index.json
  css/challenge-flex-dice-layout/intro.md
  css/challenge-flex-dice-layout/setup.sh
  css/challenge-flex-dice-layout/solutions/index.html
  css/challenge-flex-dice-layout/step1.md
  css/challenge-flex-dice-layout/verify0.sh
  css/challenge-flex-dice-layout/verify1-1.sh
  css/challenge-flex-dice-layout/verify1-2.sh
  css/challenge-flex-dice-layout/verify1-3.sh
Labels: Test Completed

#798 Add challenge-draw-a-koala in css
  css/challenge-draw-a-koala/assets/.puppeteerrc.cjs
  css/challenge-draw-a-koala/assets/example.png
  css/challenge-draw-a-koala/assets/finished.png
  css/challenge-draw-a-koala/assets/index.html
  css/challenge-draw-a-koala/assets/reference.png
  css/challenge-draw-a-koala/assets/styles.css
  css/challenge-draw-a-koala/assets/test_draw_a_koala.js
  css/challenge-draw-a-koala/assets/unfinished.png
  css/challenge-draw-a-koala/finish.md
  css/challenge-draw-a-koala/index.json
  css/challenge-draw-a-koala/intro.md
  css/challenge-draw-a-koala/setup.sh
  css/challenge-draw-a-koala/solutions/styles.css
  css/challenge-draw-a-koala/step1.md
  css/challenge-draw-a-koala/verify0.sh
  css/challenge-draw-a-koala/verify1-1.sh
  css/challenge-draw-a-koala/verify1-2.sh
Labels: Test Completed

#720 Challenge mount
  linux/challenge-mount/assets/mount.sh
  linux/challenge-mount/finish.md
  linux/challenge-mount/index.json
  linux/challenge-mount/intro.md
  linux/challenge-mount/setup.sh
  linux/challenge-mount/solutions/mount.sh
  linux/challenge-mount/step1.md
  linux/challenge-mount/verify1.sh
Labels: Test Completed, Minor Repair

#739 Challenge user search
  linux/challenge-user-search/assets/userSearch.sh
  linux/challenge-user-search/finish.md
  linux/challenge-user-search/index.json
  linux/challenge-user-search/intro.md
  linux/challenge-user-search/setup.sh
  linux/challenge-user-search/solutions/userSearch.sh
  linux/challenge-user-search/step1.md
  linux/challenge-user-search/verify1.sh
Labels: Test Completed

#738 Challenge user id
  linux/challenge-user-id/assets/userId.sh
  linux/challenge-user-id/finish.md
  linux/challenge-user-id/index.json
  linux/challenge-user-id/intro.md
  linux/challenge-user-id/setup.sh
  linux/challenge-user-id/solutions/userId.sh
  linux/challenge-user-id/step1.md
  linux/challenge-user-id/verify1.sh
Labels: Test Completed

#736 Challenge system information
  linux/challenge-system-information/assets/sysInfo.sh
  linux/challenge-system-information/finish.md
  linux/challenge-system-information/index.json
  linux/challenge-system-information/intro.md
  linux/challenge-system-information/setup.sh
  linux/challenge-system-information/solutions/sysInfo.sh
  linux/challenge-system-information/step1.md
  linux/challenge-system-information/verify1.sh
Labels: Test Completed

#734 Challenge string conversion
  linux/challenge-string-conversion/assets/input_file.txt
  linux/challenge-string-conversion/assets/stringConv.sh
  linux/challenge-string-conversion/finish.md
  linux/challenge-string-conversion/index.json
  linux/challenge-string-conversion/intro.md
  linux/challenge-string-conversion/setup.sh
  linux/challenge-string-conversion/solutions/stringConv.sh
  linux/challenge-string-conversion/step1.md
  linux/challenge-string-conversion/verify1.sh
Labels: Test Completed

#733 Challenge sort
  linux/challenge-sort/assets/sort.sh
  linux/challenge-sort/finish.md
  linux/challenge-sort/index.json
  linux/challenge-sort/intro.md
  linux/challenge-sort/setup.sh
  linux/challenge-sort/solutions/sort.sh
  linux/challenge-sort/step1.md
  linux/challenge-sort/verify1.sh
Labels: Test Completed

#732 Challenge say hello
  linux/challenge-say-hello/assets/sayHello.sh
  linux/challenge-say-hello/finish.md
  linux/challenge-say-hello/index.json
  linux/challenge-say-hello/intro.md
  linux/challenge-say-hello/setup.sh
  linux/challenge-say-hello/solutions/sayHello.sh
  linux/challenge-say-hello/step1.md
  linux/challenge-say-hello/verify1.sh
Labels: Test Completed

#731 Challenge right angle triangle pattern
  linux/challenge-right-angle-triangle-pattern/assets/pattern1.sh
  linux/challenge-right-angle-triangle-pattern/finish.md
  linux/challenge-right-angle-triangle-pattern/index.json
  linux/challenge-right-angle-triangle-pattern/intro.md
  linux/challenge-right-angle-triangle-pattern/setup.sh
  linux/challenge-right-angle-triangle-pattern/solutions/pattern1.sh
  linux/challenge-right-angle-triangle-pattern/step1.md
  linux/challenge-right-angle-triangle-pattern/verify1.sh
Labels: Test Completed

#730 Challenge reverse numbers
  linux/challenge-reverse-numbers/assets/reverse.sh
  linux/challenge-reverse-numbers/finish.md
  linux/challenge-reverse-numbers/index.json
  linux/challenge-reverse-numbers/intro.md
  linux/challenge-reverse-numbers/setup.sh
  linux/challenge-reverse-numbers/solutions/reverse.sh
  linux/challenge-reverse-numbers/step1.md
  linux/challenge-reverse-numbers/verify1.sh
Labels: Test Completed

#728 Challenge recursive function
  linux/challenge-recursive-function/assets/recFunction.sh
  linux/challenge-recursive-function/finish.md
  linux/challenge-recursive-function/index.json
  linux/challenge-recursive-function/intro.md
  linux/challenge-recursive-function/setup.sh
  linux/challenge-recursive-function/solutions/recFunction.sh
  linux/challenge-recursive-function/step1.md
  linux/challenge-recursive-function/verify1.sh
Labels: Test Completed

#727 Challenge arithematic on operator
  linux/challenge-arithematic-on-operator/assets/arithematicOnOperator.sh
  linux/challenge-arithematic-on-operator/finish.md
  linux/challenge-arithematic-on-operator/index.json
  linux/challenge-arithematic-on-operator/intro.md
  linux/challenge-arithematic-on-operator/setup.sh
  linux/challenge-arithematic-on-operator/solutions/arithematicOnOperator.sh
  linux/challenge-arithematic-on-operator/step1.md
  linux/challenge-arithematic-on-operator/verify1.sh
Labels: Test Completed

#726 Challenge chess boards
  linux/challenge-chess-board/assets/1-1.PNG
  linux/challenge-chess-board/assets/chessBoard.sh
  linux/challenge-chess-board/finish.md
  linux/challenge-chess-board/index.json
  linux/challenge-chess-board/intro.md
  linux/challenge-chess-board/setup.sh
  linux/challenge-chess-board/solutions/chessBoard.sh
  linux/challenge-chess-board/step1.md
  linux/challenge-chess-board/verify1.sh
Labels: Test Completed

#725 Challenge random passwords
  linux/challenge-random-passwords/assets/randPasswd.sh
  linux/challenge-random-passwords/finish.md
  linux/challenge-random-passwords/index.json
  linux/challenge-random-passwords/intro.md
  linux/challenge-random-passwords/setup.sh
  linux/challenge-random-passwords/solutions/randPasswd.sh
  linux/challenge-random-passwords/step1.md
  linux/challenge-random-passwords/verify1.sh
Labels: Test Completed

#724 Challenge print lines
  linux/challenge-print-lines/assets/inputFile.txt
  linux/challenge-print-lines/assets/printLines.sh
  linux/challenge-print-lines/finish.md
  linux/challenge-print-lines/index.json
  linux/challenge-print-lines/intro.md
  linux/challenge-print-lines/setup.sh
  linux/challenge-print-lines/solutions/printLines.sh
  linux/challenge-print-lines/step1.md
  linux/challenge-print-lines/verify1.sh
Labels: Test Completed

#723 Challenge print equilateral triangle pattern
  linux/challenge-print-equilateral-triangle-pattern/assets/pattern2.sh
  linux/challenge-print-equilateral-triangle-pattern/finish.md
  linux/challenge-print-equilateral-triangle-pattern/index.json
  linux/challenge-print-equilateral-triangle-pattern/intro.md
  linux/challenge-print-equilateral-triangle-pattern/setup.sh
  linux/challenge-print-equilateral-triangle-pattern/solutions/pattern2.sh
  linux/challenge-print-equilateral-triangle-pattern/step1.md
  linux/challenge-print-equilateral-triangle-pattern/verify1.sh
Labels: Test Completed

#722 Challenge path count
  linux/challenge-path-count/assets/pathCount.sh
  linux/challenge-path-count/finish.md
  linux/challenge-path-count/index.json
  linux/challenge-path-count/intro.md
  linux/challenge-path-count/setup.sh
  linux/challenge-path-count/solutions/pathCount.sh
  linux/challenge-path-count/step1.md
  linux/challenge-path-count/verify1.sh
Labels: Test Completed

#719 Challenge long and short
  linux/challenge-long-and-short/assets/longAndShort.sh
  linux/challenge-long-and-short/finish.md
  linux/challenge-long-and-short/index.json
  linux/challenge-long-and-short/intro.md
  linux/challenge-long-and-short/setup.sh
  linux/challenge-long-and-short/solutions/longAndShort.sh
  linux/challenge-long-and-short/step1.md
  linux/challenge-long-and-short/verify1.sh
Labels: Test Completed

#718 Challenge free space
  linux/challenge-free-space/assets/freeSpace.sh
  linux/challenge-free-space/finish.md
  linux/challenge-free-space/index.json
  linux/challenge-free-space/intro.md
  linux/challenge-free-space/setup.sh
  linux/challenge-free-space/solutions/freeSpace.sh
  linux/challenge-free-space/step1.md
  linux/challenge-free-space/verify1.sh
Labels: Test Completed

#717 Challenge file information
  linux/challenge-file-information/assets/fileInfo.sh
  linux/challenge-file-information/finish.md
  linux/challenge-file-information/index.json
  linux/challenge-file-information/intro.md
  linux/challenge-file-information/setup.sh
  linux/challenge-file-information/solutions/fileInfo.sh
  linux/challenge-file-information/step1.md
  linux/challenge-file-information/verify1.sh
Labels: Test Completed

#716 Challenge fibonacci
  linux/challenge-fibonacci/assets/fibonacci.sh
  linux/challenge-fibonacci/finish.md
  linux/challenge-fibonacci/index.json
  linux/challenge-fibonacci/intro.md
  linux/challenge-fibonacci/setup.sh
  linux/challenge-fibonacci/solutions/fibonacci.sh
  linux/challenge-fibonacci/step1.md
  linux/challenge-fibonacci/verify1.sh
Labels: Test Completed

#714 Challenge directories lists
  linux/challenge-directories-lists/assets/dirList.sh
  linux/challenge-directories-lists/finish.md
  linux/challenge-directories-lists/index.json
  linux/challenge-directories-lists/intro.md
  linux/challenge-directories-lists/setup.sh
  linux/challenge-directories-lists/solutions/dirList.sh
  linux/challenge-directories-lists/step1.md
  linux/challenge-directories-lists/verify1.sh
Labels: Test Completed

#711 Challenge compare integers
  linux/challenge-compare-integers/assets/compareIntegers.sh
  linux/challenge-compare-integers/finish.md
  linux/challenge-compare-integers/index.json
  linux/challenge-compare-integers/intro.md
  linux/challenge-compare-integers/setup.sh
  linux/challenge-compare-integers/solutions/compareIntegers.sh
  linux/challenge-compare-integers/step1.md
  linux/challenge-compare-integers/verify1.sh
Labels: Test Completed

#710 Challenge adding two numbers
  linux/challenge-adding-two-numbers/assets/add2No.sh
  linux/challenge-adding-two-numbers/finish.md
  linux/challenge-adding-two-numbers/index.json
  linux/challenge-adding-two-numbers/intro.md
  linux/challenge-adding-two-numbers/setup.sh
  linux/challenge-adding-two-numbers/solutions/add2No.sh
  linux/challenge-adding-two-numbers/step1.md
  linux/challenge-adding-two-numbers/verify1.sh
Labels: Test Completed
