Repository labex-labs/scenarios, pull requests merged in 2023-04, with the labels that each got.

#269 lab-basic-magic-methods-in-python
  python/lab-basic-magic-methods/assets/compare_example.py
  python/lab-basic-magic-methods/assets/del_example.py
  python/lab-basic-magic-methods/assets/init_repr_example.py
  python/lab-basic-magic-methods/assets/person.py
  python/lab-basic-magic-methods/finish.md
  python/lab-basic-magic-methods/index.json
  python/lab-basic-magic-methods/intro.md
  python/lab-basic-magic-methods/setup.sh
  python/lab-basic-magic-methods/step1.md
  python/lab-basic-magic-methods/step2.md
  python/lab-basic-magic-methods/step3.md
  python/lab-basic-magic-methods/verify1-1.sh
  python/lab-basic-magic-methods/verify1-2.sh
  python/lab-basic-magic-methods/verify1-3.sh
  python/lab-basic-magic-methods/verify1-4.sh
  python/lab-basic-magic-methods/verify1-5.sh
  python/lab-basic-magic-methods/verify2-1.sh
  python/lab-basic-magic-methods/verify2-2.sh
  python/lab-basic-magic-methods/verify2-3.sh
  python/lab-basic-magic-methods/verify2-4.sh
  python/lab-basic-magic-methods/verify3-1.sh
  python/lab-basic-magic-methods/verify3-2.sh
  python/lab-basic-magic-methods/verify3-3.sh
Labels: Test Completed, No Repair

#291 Lab python arithmetic with custom numeric magic methods
  python/lab-custom-numeric-magic-methods/assets/binary_example.py
  python/lab-custom-numeric-magic-methods/assets/binary_example_test.py
  python/lab-custom-numeric-magic-methods/assets/inplace_example1.py
  python/lab-custom-numeric-magic-methods/assets/inplace_example2.py
  python/lab-custom-numeric-magic-methods/assets/inplace_example_test.py
  python/lab-custom-numeric-magic-methods/assets/number.py
  python/lab-custom-numeric-magic-methods/assets/unary_example.py
  python/lab-custom-numeric-magic-methods/assets/unary_example_test.py
  python/lab-custom-numeric-magic-methods/finish.md
  python/lab-custom-numeric-magic-methods/index.json
  python/lab-custom-numeric-magic-methods/intro.md
  python/lab-custom-numeric-magic-methods/setup.sh
  python/lab-custom-numeric-magic-methods/step1.md
  python/lab-custom-numeric-magic-methods/step2.md
  python/lab-custom-numeric-magic-methods/step3.md
  python/lab-custom-numeric-magic-methods/verify1.sh
  python/lab-custom-numeric-magic-methods/verify2.sh
  python/lab-custom-numeric-magic-methods/verify3.sh
Labels: Test Completed

#325 lab-sequence-magic-methods #299
  python/lab-sequence-magic-methods/assets/item_access_example.py
  python/lab-sequence-magic-methods/assets/item_access_example_test.py
  python/lab-sequence-magic-methods/assets/iteration_example.py
  python/lab-sequence-magic-methods/assets/iteration_example_test.py
  python/lab-sequence-magic-methods/assets/length_containment_example.py
  python/lab-sequence-magic-methods/assets/length_containment_example_test.py
  python/lab-sequence-magic-methods/assets/sequence.py
  python/lab-sequence-magic-methods/finish.md
  python/lab-sequence-magic-methods/index.json
  python/lab-sequence-magic-methods/intro.md
  python/lab-sequence-magic-methods/setup.sh
  python/lab-sequence-magic-methods/step1.md
  python/lab-sequence-magic-methods/step2.md
  python/lab-sequence-magic-methods/step3.md
  python/lab-sequence-magic-methods/verify1.sh
  python/lab-sequence-magic-methods/verify2.sh
  python/lab-sequence-magic-methods/verify3.sh
Labels: Test Completed

#274 Challenge delete and move files
  linux/challenge-delete-and-move-files/assets/mytextfile.txt
  linux/challenge-delete-and-move-files/finish.md
  linux/challenge-delete-and-move-files/index.json
  linux/challenge-delete-and-move-files/intro.md
  linux/challenge-delete-and-move-files/setup.sh
  linux/challenge-delete-and-move-files/solution/solution.md
  linux/challenge-delete-and-move-files/step1.md
  linux/challenge-delete-and-move-files/step2.md
  linux/challenge-delete-and-move-files/step3.md
  linux/challenge-delete-and-move-files/verify1.sh
  linux/challenge-delete-and-move-files/verify2.sh
  linux/challenge-delete-and-move-files/verify3-1.sh
  linux/challenge-delete-and-move-files/verify3-2.sh
Labels: Test Completed, Minor Repair

#321 add challenge-error-and-exception-handling
  python/challenge-error-and-exception-handling/assets/automated_testing.py
  python/challenge-error-and-exception-handling/assets/custom_exceptions_and_logging.py
  python/challenge-error-and-exception-handling/assets/example.txt
  python/challenge-error-and-exception-handling/assets/graceful_error_recovery.py
  python/challenge-error-and-exception-handling/assets/step1_1_test.py
  python/challenge-error-and-exception-handling/assets/step1_2_test.py
  python/challenge-error-and-exception-handling/assets/step1_3_test.py
  python/challenge-error-and-exception-handling/assets/step1_4_test.py
  python/challenge-error-and-exception-handling/assets/step1_5_test.py
  python/challenge-error-and-exception-handling/assets/step1_6_test.py
  python/challenge-error-and-exception-handling/assets/step1_7_test.py
  python/challenge-error-and-exception-handling/assets/step2_1_test.py
  python/challenge-error-and-exception-handling/assets/step2_2_test.py
  python/challenge-error-and-exception-handling/assets/step2_3_test.py
  python/challenge-error-and-exception-handling/assets/step3_test.py
  python/challenge-error-and-exception-handling/finish.md
  python/challenge-error-and-exception-handling/index.json
  python/challenge-error-and-exception-handling/intro.md
  python/challenge-error-and-exception-handling/setup.sh
  python/challenge-error-and-exception-handling/solutions/automated_testing.py
  python/challenge-error-and-exception-handling/solutions/custom_exceptions_and_logging.py
  python/challenge-error-and-exception-handling/solutions/graceful_error_recovery.py
  python/challenge-error-and-exception-handling/step1.md
  python/challenge-error-and-exception-handling/step2.md
  python/challenge-error-and-exception-handling/step3.md
  python/challenge-error-and-exception-handling/verify1-1.sh
  python/challenge-error-and-exception-handling/verify1-2.sh
  python/challenge-error-and-exception-handling/verify1-3.sh
  python/challenge-error-and-exception-handling/verify1-4.sh
  python/challenge-error-and-exception-handling/verify1-5.sh
  python/challenge-error-and-exception-handling/verify1-6.sh
  python/challenge-error-and-exception-handling/verify1-7.sh
  python/challenge-error-and-exception-handling/verify2-1.sh
  python/challenge-error-and-exception-handling/verify2-2.sh
  python/challenge-error-and-exception-handling/verify2-3.sh
  python/challenge-error-and-exception-handling/verify3.sh
Labels: Test Completed, Minor Repair

#322 add python threading
  python/lab-easy-to-use-threading/assets/barrier_object.py
  python/lab-easy-to-use-threading/assets/create_thread.py
  python/lab-easy-to-use-threading/assets/daemon_thread_with_args.py
  python/lab-easy-to-use-threading/assets/daemon_thread_with_func.py
  python/lab-easy-to-use-threading/assets/event_object.py
  python/lab-easy-to-use-threading/assets/sync.py
  python/lab-easy-to-use-threading/assets/thread_pool_map.py
  python/lab-easy-to-use-threading/assets/thread_pool_range.py
  python/lab-easy-to-use-threading/assets/thread_subclass.py
  python/lab-easy-to-use-threading/assets/thread_with_args.py
  python/lab-easy-to-use-threading/assets/timer_object.py
  python/lab-easy-to-use-threading/finish.md
  python/lab-easy-to-use-threading/index.json
  python/lab-easy-to-use-threading/intro.md
  python/lab-easy-to-use-threading/setup.sh
  python/lab-easy-to-use-threading/step1.md
  python/lab-easy-to-use-threading/step2.md
  python/lab-easy-to-use-threading/step3.md
  python/lab-easy-to-use-threading/step4.md
  python/lab-easy-to-use-threading/step5.md
  python/lab-easy-to-use-threading/step6.md
  python/lab-easy-to-use-threading/step7.md
  python/lab-easy-to-use-threading/step8.md
  python/lab-easy-to-use-threading/verify1.sh
  python/lab-easy-to-use-threading/verify2.sh
  python/lab-easy-to-use-threading/verify3-1.sh
  python/lab-easy-to-use-threading/verify3-2.sh
  python/lab-easy-to-use-threading/verify4-1.sh
  python/lab-easy-to-use-threading/verify4-2.sh
  python/lab-easy-to-use-threading/verify5-1.sh
  python/lab-easy-to-use-threading/verify5-2.sh
  python/lab-easy-to-use-threading/verify6.sh
  python/lab-easy-to-use-threading/verify7.sh
  python/lab-easy-to-use-threading/verify8.sh
Labels: Test Completed, Minor Repair

#312 add lnmp lab
  linux/lab-linux-deploy-lnmp/assets/lab-linux-deploy-lnmp-1-1.png
  linux/lab-linux-deploy-lnmp/assets/lab-linux-deploy-lnmp-2-1.png
  linux/lab-linux-deploy-lnmp/assets/lab-linux-deploy-lnmp-3-1.png
  linux/lab-linux-deploy-lnmp/assets/lab-linux-deploy-lnmp-7-1.png
  linux/lab-linux-deploy-lnmp/finish.md
  linux/lab-linux-deploy-lnmp/index.json
  linux/lab-linux-deploy-lnmp/intro.md
  linux/lab-linux-deploy-lnmp/setup.sh
  linux/lab-linux-deploy-lnmp/step1.md
  linux/lab-linux-deploy-lnmp/step2.md
  linux/lab-linux-deploy-lnmp/step3.md
  linux/lab-linux-deploy-lnmp/step4.md
  linux/lab-linux-deploy-lnmp/step5.md
  linux/lab-linux-deploy-lnmp/step6.md
  linux/lab-linux-deploy-lnmp/step7.md
  linux/lab-linux-deploy-lnmp/verify1.sh
  linux/lab-linux-deploy-lnmp/verify2.sh
  linux/lab-linux-deploy-lnmp/verify3.sh
  linux/lab-linux-deploy-lnmp/verify4.sh
  linux/lab-linux-deploy-lnmp/verify5.sh
  linux/lab-linux-deploy-lnmp/verify6.sh
  linux/lab-linux-deploy-lnmp/verify7.sh
Labels: Test Completed, Minor Repair

#294 Lab typing module
  python/lab-typing-module/assets/callable.py
  python/lab-typing-module/assets/list_to_set.py
  python/lab-typing-module/assets/mypy.py
  python/lab-typing-module/assets/newtype.py
  python/lab-typing-module/assets/option_and_none_1.py
  python/lab-typing-module/assets/option_and_none_2.py
  python/lab-typing-module/assets/other_to_float.py
  python/lab-typing-module/assets/str_and_int_to_str.py
  python/lab-typing-module/assets/type_aliases.py
  python/lab-typing-module/assets/typeddict.py
  python/lab-typing-module/finish.md
  python/lab-typing-module/index.json
  python/lab-typing-module/intro.md
  python/lab-typing-module/setup.sh
  python/lab-typing-module/step1.md
  python/lab-typing-module/step2.md
  python/lab-typing-module/step3.md
  python/lab-typing-module/step4.md
  python/lab-typing-module/step5.md
  python/lab-typing-module/step6.md
  python/lab-typing-module/step7.md
  python/lab-typing-module/step8.md
  python/lab-typing-module/step9.md
  python/lab-typing-module/verify1-1.sh
  python/lab-typing-module/verify1-2.sh
  python/lab-typing-module/verify2.sh
  python/lab-typing-module/verify3.sh
  python/lab-typing-module/verify4.sh
  python/lab-typing-module/verify5.sh
  python/lab-typing-module/verify6.sh
  python/lab-typing-module/verify7.sh
  python/lab-typing-module/verify8.sh
  python/lab-typing-module/verify9-1.sh
  python/lab-typing-module/verify9-2.sh
Labels: Test Completed, Minor Repair

#288 add itertools module lab
  python/lab-itertools-module/assets/chain.py
  python/lab-itertools-module/assets/combinations.py
  python/lab-itertools-module/assets/count.py
  python/lab-itertools-module/assets/cr.py
  python/lab-itertools-module/assets/cycle.py
  python/lab-itertools-module/assets/permutations.py
  python/lab-itertools-module/assets/product.py
  python/lab-itertools-module/finish.md
  python/lab-itertools-module/index.json
  python/lab-itertools-module/intro.md
  python/lab-itertools-module/setup.sh
  python/lab-itertools-module/step1.md
  python/lab-itertools-module/step2.md
  python/lab-itertools-module/verify1-1.sh
  python/lab-itertools-module/verify1-2.sh
  python/lab-itertools-module/verify1-3.sh
  python/lab-itertools-module/verify2-1.sh
  python/lab-itertools-module/verify2-2.sh
  python/lab-itertools-module/verify2-3.sh
  python/lab-itertools-module/verify2-4.sh
Labels: Test Completed, Minor Repair

#253 Lab python multiprocessing
  python/lab-python-multiprocessing/assets/complex_square.py
  python/lab-python-multiprocessing/assets/complex_square_test.py
  python/lab-python-multiprocessing/assets/multiprocessing_queue.py
  python/lab-python-multiprocessing/assets/multiprocessing_queue_test.py
  python/lab-python-multiprocessing/assets/slow_square.py
  python/lab-python-multiprocessing/assets/slow_square_test.py
  python/lab-python-multiprocessing/assets/square.py
  python/lab-python-multiprocessing/assets/square_test.py
  python/lab-python-multiprocessing/finish.md
  python/lab-python-multiprocessing/index.json
  python/lab-python-multiprocessing/intro.md
  python/lab-python-multiprocessing/setup.sh
  python/lab-python-multiprocessing/step1.md
  python/lab-python-multiprocessing/step2.md
  python/lab-python-multiprocessing/step3.md
  python/lab-python-multiprocessing/step4.md
  python/lab-python-multiprocessing/verify1.sh
  python/lab-python-multiprocessing/verify2.sh
  python/lab-python-multiprocessing/verify3.sh
  python/lab-python-multiprocessing/verify4.sh
Labels: Test Completed, Major Repair

#162 add challenge-area-calculation
  .gitignore
  python/challenge-area-calculation/assets/area.py
  python/challenge-area-calculation/assets/area_test.py
  python/challenge-area-calculation/assets/shape.py
  python/challenge-area-calculation/assets/shape_test.py
  python/challenge-area-calculation/assets/subclass.py
  python/challenge-area-calculation/assets/subclass_test.py
  python/challenge-area-calculation/finish.md
  python/challenge-area-calculation/index.json
  python/challenge-area-calculation/intro.md
  python/challenge-area-calculation/setup.sh
  python/challenge-area-calculation/solutions/area.py
  python/challenge-area-calculation/solutions/shape.py
  python/challenge-area-calculation/solutions/solution.md
  python/challenge-area-calculation/solutions/subclass.py
  python/challenge-area-calculation/step1.md
  python/challenge-area-calculation/step2.md
  python/challenge-area-calculation/step3.md
  python/challenge-area-calculation/verify1.sh
  python/challenge-area-calculation/verify2.sh
  python/challenge-area-calculation/verify3.sh
Labels: Test Completed, Minor Repair

#164 Add challenge statistical fruits
  python/challenge-statistical-fruits/assets/basket_weight.py
  python/challenge-statistical-fruits/assets/basket_weight_test.py
  python/challenge-statistical-fruits/assets/put_fruits.py
  python/challenge-statistical-fruits/assets/put_fruits_test.py
  python/challenge-statistical-fruits/finish.md
  python/challenge-statistical-fruits/index.json
  python/challenge-statistical-fruits/intro.md
  python/challenge-statistical-fruits/setup.sh
  python/challenge-statistical-fruits/solutions/basket_weight.py
  python/challenge-statistical-fruits/solutions/put_fruits.py
  python/challenge-statistical-fruits/solutions/solution.md
  python/challenge-statistical-fruits/step1.md
  python/challenge-statistical-fruits/step2.md
  python/challenge-statistical-fruits/verify1.sh
  python/challenge-statistical-fruits/verify2.sh
Labels: Test Completed, Minor Repair

#188 add jenkins install and pipeline
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-1-2.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-1-3.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-1-4.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-1-5.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-1-6.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-2-1.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-2-2.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-2-3.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-2-4.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-2-5.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-3-1.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-3-2.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-3-3.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-4-1.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-4-2.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-4-3.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-4-4.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-5-1.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-5-2.png
  jenkins/challenge-install-create-pipeline/assets/challenge-install-create-pipeline-5-3.png
  jenkins/challenge-install-create-pipeline/finish.md
  jenkins/challenge-install-create-pipeline/index.json
  jenkins/challenge-install-create-pipeline/intro.md
  jenkins/challenge-install-create-pipeline/setup.sh
  jenkins/challenge-install-create-pipeline/solutions/step1-solution.md
  jenkins/challenge-install-create-pipeline/solutions/step2-solution.md
  jenkins/challenge-install-create-pipeline/solutions/step3-solution.md
  jenkins/challenge-install-create-pipeline/solutions/step4-solution.md
  jenkins/challenge-install-create-pipeline/solutions/step5-solution.md
  jenkins/challenge-install-create-pipeline/step1.md
  jenkins/challenge-install-create-pipeline/step2.md
  jenkins/challenge-install-create-pipeline/step3.md
  jenkins/challenge-install-create-pipeline/step4.md
  jenkins/challenge-install-create-pipeline/step5.md
  jenkins/challenge-install-create-pipeline/verify1-3.sh
  jenkins/challenge-install-create-pipeline/verify1-4.sh
  jenkins/challenge-install-create-pipeline/verify2-1.sh
  jenkins/challenge-install-create-pipeline/verify2-2.sh
  jenkins/challenge-install-create-pipeline/verify2-3.sh
  jenkins/challenge-install-create-pipeline/verify3-1.sh
  jenkins/challenge-install-create-pipeline/verify3-2.sh
Labels: Test Completed, Minor Repair

#180 add docker volume management
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-1-1.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-1-2.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-1-3.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-1-4.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-2-1.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-2-2.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-2-3.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-2-4.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-3-1.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-3-2.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-3-3.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-3-4.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-3-5.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-3-6.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-4-1.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-4-2.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-4-3.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-4-4.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-4-5.png
  docker/challenge-docker-volume-management/assets/challenge-docker-volume-management-4-6.png
  docker/challenge-docker-volume-management/finish.md
  docker/challenge-docker-volume-management/index.json
  docker/challenge-docker-volume-management/intro.md
  docker/challenge-docker-volume-management/setup.sh
  docker/challenge-docker-volume-management/solutions/solution-asset.md
  docker/challenge-docker-volume-management/solutions/step1-solution.md
  docker/challenge-docker-volume-management/solutions/step2-solution.md
  docker/challenge-docker-volume-management/solutions/step3-solution.md
  docker/challenge-docker-volume-management/solutions/step4-solution.md
  docker/challenge-docker-volume-management/step1.md
  docker/challenge-docker-volume-management/step2.md
  docker/challenge-docker-volume-management/step3.md
  docker/challenge-docker-volume-management/step4.md
  docker/challenge-docker-volume-management/verify1-1.sh
  docker/challenge-docker-volume-management/verify1-2.sh
  docker/challenge-docker-volume-management/verify2-1.sh
  docker/challenge-docker-volume-management/verify2-2.sh
  docker/challenge-docker-volume-management/verify2-3.sh
  docker/challenge-docker-volume-management/verify3-1.sh
  docker/challenge-docker-volume-management/verify3-2.sh
  docker/challenge-docker-volume-management/verify3-3.sh
  docker/challenge-docker-volume-management/verify4-1.sh
  docker/challenge-docker-volume-management/verify4-2.sh
  docker/challenge-docker-volume-management/verify4-3.sh
Labels: Test Completed, Minor Repair

#186 add docker image and registry
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-1-1.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-1-2.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-1-3.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-1-4.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-1-5.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-2-1.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-2-2.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-2-3.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-2-4.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-2-5.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-2-6.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-3-1.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-3-2.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-3-3.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-3-4.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-3-5.png
  docker/challenge-docker-image-and-registry/assets/challenge-docker-image-and-registry-3-6.png
  docker/challenge-docker-image-and-registry/finish.md
  docker/challenge-docker-image-and-registry/index.json
  docker/challenge-docker-image-and-registry/intro.md
  docker/challenge-docker-image-and-registry/setup.sh
  docker/challenge-docker-image-and-registry/solutions/step1-solution.md
  docker/challenge-docker-image-and-registry/solutions/step2-solution.md
  docker/challenge-docker-image-and-registry/solutions/step3-solution.md
  docker/challenge-docker-image-and-registry/step1.md
  docker/challenge-docker-image-and-registry/step2.md
  docker/challenge-docker-image-and-registry/step3.md
  docker/challenge-docker-image-and-registry/verify1-1.sh
  docker/challenge-docker-image-and-registry/verify2-1.sh
  docker/challenge-docker-image-and-registry/verify2-2.sh
  docker/challenge-docker-image-and-registry/verify2-3.sh
  docker/challenge-docker-image-and-registry/verify3-1.sh
  docker/challenge-docker-image-and-registry/verify3-2.sh
  docker/challenge-docker-image-and-registry/verify3-3.sh
Labels: Test Completed, Minor Repair

#165 Add challenge build fake person
  python/challenge-build-fake-person/assets/fake_person.py
  python/challenge-build-fake-person/assets/fake_person_test.py
  python/challenge-build-fake-person/assets/install.bash
  python/challenge-build-fake-person/assets/install_test.py
  python/challenge-build-fake-person/assets/person.py
  python/challenge-build-fake-person/assets/person_test.py
  python/challenge-build-fake-person/finish.md
  python/challenge-build-fake-person/index.json
  python/challenge-build-fake-person/intro.md
  python/challenge-build-fake-person/setup.sh
  python/challenge-build-fake-person/solutions/fake_person.py
  python/challenge-build-fake-person/solutions/install.bash
  python/challenge-build-fake-person/solutions/person.py
  python/challenge-build-fake-person/solutions/solution.md
  python/challenge-build-fake-person/step1.md
  python/challenge-build-fake-person/step2.md
  python/challenge-build-fake-person/step3.md
  python/challenge-build-fake-person/verify1.sh
  python/challenge-build-fake-person/verify2.sh
  python/challenge-build-fake-person/verify3.sh
Labels: Test Completed, Major Repair

#113 add kubernetes advance scheduler
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-1-1.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-1-2.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-1-3.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-1-4.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-2-1.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-2-2.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-2-3.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-3-1.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-3-2.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-3-3.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-3-4.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-3-5.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-4-1.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-4-2.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-4-3.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-4-4.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-5-1.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-5-2.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-5-3.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-6-1.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-6-2.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-6-3.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-6-4.png
  kubernetes/challenge-kubernetes-advance-scheduler/assets/challenge-kubernetes-advance-scheduler-6-5.png
  kubernetes/challenge-kubernetes-advance-scheduler/finish.md
  kubernetes/challenge-kubernetes-advance-scheduler/index.json
  kubernetes/challenge-kubernetes-advance-scheduler/intro.md
  kubernetes/challenge-kubernetes-advance-scheduler/setup.sh
  kubernetes/challenge-kubernetes-advance-scheduler/solutions/solution-asset.md
  kubernetes/challenge-kubernetes-advance-scheduler/solutions/step1-solution.md
  kubernetes/challenge-kubernetes-advance-scheduler/solutions/step2-solution.md
  kubernetes/challenge-kubernetes-advance-scheduler/solutions/step3-solution.md
  kubernetes/challenge-kubernetes-advance-scheduler/solutions/step4-solution.md
  kubernetes/challenge-kubernetes-advance-scheduler/solutions/step5-solution.md
  kubernetes/challenge-kubernetes-advance-scheduler/solutions/step6-solution.md
  kubernetes/challenge-kubernetes-advance-scheduler/step1.md
  kubernetes/challenge-kubernetes-advance-scheduler/step2.md
  kubernetes/challenge-kubernetes-advance-scheduler/step3.md
  kubernetes/challenge-kubernetes-advance-scheduler/step4.md
  kubernetes/challenge-kubernetes-advance-scheduler/step5.md
  kubernetes/challenge-kubernetes-advance-scheduler/step6.md
  kubernetes/challenge-kubernetes-advance-scheduler/verify1-1.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify1-2.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify1-3.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify1-4.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify2-1.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify2-2.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify2-3.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify3-1.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify3-2.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify3-3.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify4-1.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify4-2.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify4-3.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify5-1.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify5-2.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify6-1.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify6-2.sh
  kubernetes/challenge-kubernetes-advance-scheduler/verify6-3.sh
Labels: Test Completed, Minor Repair

#252 Challenge python multiprocessing
  python/challenge-python-multiprocessing/assets/multiprocessing_queue.py
  python/challenge-python-multiprocessing/assets/multiprocessing_queue_test.py
  python/challenge-python-multiprocessing/assets/slow_square.py
  python/challenge-python-multiprocessing/assets/slow_square_test.py
  python/challenge-python-multiprocessing/assets/square.py
  python/challenge-python-multiprocessing/assets/square_multiprocessing.py
  python/challenge-python-multiprocessing/assets/square_multiprocessing_test.py
  python/challenge-python-multiprocessing/assets/square_test.py
  python/challenge-python-multiprocessing/finish.md
  python/challenge-python-multiprocessing/index.json
  python/challenge-python-multiprocessing/intro.md
  python/challenge-python-multiprocessing/setup.sh
  python/challenge-python-multiprocessing/solutions/multiprocessing_queue.py
  python/challenge-python-multiprocessing/solutions/slow_square.py
  python/challenge-python-multiprocessing/solutions/square.py
  python/challenge-python-multiprocessing/solutions/square_multiprocessing.py
  python/challenge-python-multiprocessing/step1.md
  python/challenge-python-multiprocessing/step2.md
  python/challenge-python-multiprocessing/step3.md
  python/challenge-python-multiprocessing/step4.md
  python/challenge-python-multiprocessing/verify1.sh
  python/challenge-python-multiprocessing/verify2.sh
  python/challenge-python-multiprocessing/verify3.sh
  python/challenge-python-multiprocessing/verify4.sh
Labels: Test Completed, Major Repair

#244 add challenge-the-powerful-numpy-einsum-function
  numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test1.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/hadamard_product_test2.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/matmul.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/matmul_test1.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/matmul_test2.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/tensor_contract.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/tensor_contract_test1.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/tensor_contract_test2.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/trace_of_matrix.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/trace_of_matrix_test1.py
  numpy/challenge-the-powerful-numpy-einsum-function/assets/trace_of_matrix_test2.py
  numpy/challenge-the-powerful-numpy-einsum-function/finish.md
  numpy/challenge-the-powerful-numpy-einsum-function/index.json
  numpy/challenge-the-powerful-numpy-einsum-function/intro.md
  numpy/challenge-the-powerful-numpy-einsum-function/setup.sh
  numpy/challenge-the-powerful-numpy-einsum-function/solutions/hadamard_product.py
  numpy/challenge-the-powerful-numpy-einsum-function/solutions/matmul.py
  numpy/challenge-the-powerful-numpy-einsum-function/solutions/tensor_contract.py
  numpy/challenge-the-powerful-numpy-einsum-function/solutions/trace_of_matrix.py
  numpy/challenge-the-powerful-numpy-einsum-function/step1.md
  numpy/challenge-the-powerful-numpy-einsum-function/step2.md
  numpy/challenge-the-powerful-numpy-einsum-function/step3.md
  numpy/challenge-the-powerful-numpy-einsum-function/step4.md
  numpy/challenge-the-powerful-numpy-einsum-function/verify1-0.sh
  numpy/challenge-the-powerful-numpy-einsum-function/verify1-1.sh
  numpy/challenge-the-powerful-numpy-einsum-function/verify2-0.sh
  numpy/challenge-the-powerful-numpy-einsum-function/verify2-1.sh
  numpy/challenge-the-powerful-numpy-einsum-function/verify3-0.sh
  numpy/challenge-the-powerful-numpy-einsum-function/verify3-1.sh
  numpy/challenge-the-powerful-numpy-einsum-function/verify4-0.sh
  numpy/challenge-the-powerful-numpy-einsum-function/verify4-1.sh
Labels: Test Completed, Major Repair

#330 update solution
  linux/challenge-linux-backup-log-file/solutions/solution-step1.md
  linux/challenge-linux-backup-log-file/solutions/solution-step2.md
  linux/challenge-linux-backup-log-file/solutions/solution-step3.md
  linux/challenge-linux-backup-log-file/solutions/solution-step4.md
Labels: Test Completed

#111 add kubernetes resource monitoring
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-1-1.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-1-2.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-2-1.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-2-2.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-3-1.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-3-2.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-3-3.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-4-1.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-4-2.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-4-3.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-4-4.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-5-1.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-5-2.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-6-1.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-6-2.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-6-3.png
  kubernetes/challenge-kubernetes-resource-monitoring/assets/challenge-kubernetes-resource-monitoring-6-4.png
  kubernetes/challenge-kubernetes-resource-monitoring/finish.md
  kubernetes/challenge-kubernetes-resource-monitoring/index.json
  kubernetes/challenge-kubernetes-resource-monitoring/intro.md
  kubernetes/challenge-kubernetes-resource-monitoring/setup.sh
  kubernetes/challenge-kubernetes-resource-monitoring/solutions/step1-solution.md
  kubernetes/challenge-kubernetes-resource-monitoring/solutions/step2-solution.md
  kubernetes/challenge-kubernetes-resource-monitoring/solutions/step3-solution.md
  kubernetes/challenge-kubernetes-resource-monitoring/solutions/step4-solution.md
  kubernetes/challenge-kubernetes-resource-monitoring/solutions/step5-solution.md
  kubernetes/challenge-kubernetes-resource-monitoring/solutions/step6-solution.md
  kubernetes/challenge-kubernetes-resource-monitoring/step1.md
  kubernetes/challenge-kubernetes-resource-monitoring/step2.md
  kubernetes/challenge-kubernetes-resource-monitoring/step3.md
  kubernetes/challenge-kubernetes-resource-monitoring/step4.md
  kubernetes/challenge-kubernetes-resource-monitoring/step5.md
  kubernetes/challenge-kubernetes-resource-monitoring/step6.md
  kubernetes/challenge-kubernetes-resource-monitoring/verify1-1.sh
  kubernetes/challenge-kubernetes-resource-monitoring/verify1-2.sh
  kubernetes/challenge-kubernetes-resource-monitoring/verify2-1.sh
  kubernetes/challenge-kubernetes-resource-monitoring/verify2-2.sh
  kubernetes/challenge-kubernetes-resource-monitoring/verify3-1.sh
  kubernetes/challenge-kubernetes-resource-monitoring/verify3-2.sh
  kubernetes/challenge-kubernetes-resource-monitoring/verify4-1.sh
  kubernetes/challenge-kubernetes-resource-monitoring/verify5-1.sh
  kubernetes/challenge-kubernetes-resource-monitoring/verify5-2.sh
Labels: Test Completed, Minor Repair

#112 add kubernetes deployment management
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-1-1.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-1-2.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-1-3.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-1-4.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-1-5.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-2-1.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-2-2.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-3-1.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-3-2.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-3-3.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-3-4.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-4-1.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-4-2.png
  kubernetes/challenge-kubernetes-deployment-management/assets/challenge-kubernetes-deployment-management-4-3.png
  kubernetes/challenge-kubernetes-deployment-management/finish.md
  kubernetes/challenge-kubernetes-deployment-management/index.json
  kubernetes/challenge-kubernetes-deployment-management/intro.md
  kubernetes/challenge-kubernetes-deployment-management/setup.sh
  kubernetes/challenge-kubernetes-deployment-management/solutions/step1-solution.md
  kubernetes/challenge-kubernetes-deployment-management/solutions/step2-solution.md
  kubernetes/challenge-kubernetes-deployment-management/solutions/step3-solution.md
  kubernetes/challenge-kubernetes-deployment-management/solutions/step4-solution.md
  kubernetes/challenge-kubernetes-deployment-management/step1.md
  kubernetes/challenge-kubernetes-deployment-management/step2.md
  kubernetes/challenge-kubernetes-deployment-management/step3.md
  kubernetes/challenge-kubernetes-deployment-management/step4.md
  kubernetes/challenge-kubernetes-deployment-management/verify1-1.sh
  kubernetes/challenge-kubernetes-deployment-management/verify1-2.sh
  kubernetes/challenge-kubernetes-deployment-management/verify1-3.sh
  kubernetes/challenge-kubernetes-deployment-management/verify2-1.sh
  kubernetes/challenge-kubernetes-deployment-management/verify2-2.sh
  kubernetes/challenge-kubernetes-deployment-management/verify3-1.sh
  kubernetes/challenge-kubernetes-deployment-management/verify3-2.sh
  kubernetes/challenge-kubernetes-deployment-management/verify4-1.sh
  kubernetes/challenge-kubernetes-deployment-management/verify4-2.sh
Labels: Test Completed, Minor Repair

#280 add linux/challenge-mastering-text-manipulation
  linux/challenge-mastering-text-manipulation/finish.md
  linux/challenge-mastering-text-manipulation/index.json
  linux/challenge-mastering-text-manipulation/intro.md
  linux/challenge-mastering-text-manipulation/setup.sh
  linux/challenge-mastering-text-manipulation/solutions/solution-step1.md
  linux/challenge-mastering-text-manipulation/solutions/solution-step2.md
  linux/challenge-mastering-text-manipulation/solutions/solution-step3.md
  linux/challenge-mastering-text-manipulation/step1.md
  linux/challenge-mastering-text-manipulation/step2.md
  linux/challenge-mastering-text-manipulation/step3.md
  linux/challenge-mastering-text-manipulation/verify1-1.sh
  linux/challenge-mastering-text-manipulation/verify1-2.sh
  linux/challenge-mastering-text-manipulation/verify2-1.sh
  linux/challenge-mastering-text-manipulation/verify2-2.sh
  linux/challenge-mastering-text-manipulation/verify3-1.sh
  linux/challenge-mastering-text-manipulation/verify3-2.sh
Labels: Test Completed, Major Repair

#55 add challenge-file-properties
  linux/challenge-file-properties/assets/challenge-file-properties-1-1.png
  linux/challenge-file-properties/assets/challenge-file-properties-2-1.png
  linux/challenge-file-properties/assets/challenge-file-properties-3-1.png
  linux/challenge-file-properties/assets/challenge-file-properties-3-2.png
  linux/challenge-file-properties/assets/challenge-file-properties-3-3.png
  linux/challenge-file-properties/assets/challenge-file-properties-3-4.png
  linux/challenge-file-properties/assets/challenge-file-properties-4-1.png
  linux/challenge-file-properties/finish.md
  linux/challenge-file-properties/index.json
  linux/challenge-file-properties/intro.md
  linux/challenge-file-properties/solutions/SOLUTIONS.md
  linux/challenge-file-properties/step1.md
  linux/challenge-file-properties/step2.md
  linux/challenge-file-properties/step3.md
  linux/challenge-file-properties/step4.md
  linux/challenge-file-properties/verify1-1.sh
  linux/challenge-file-properties/verify1-2.sh
  linux/challenge-file-properties/verify2-1.sh
  linux/challenge-file-properties/verify2-2.sh
  linux/challenge-file-properties/verify3-1.sh
  linux/challenge-file-properties/verify3-2.sh
  linux/challenge-file-properties/verify4-1.sh
  linux/challenge-file-properties/verify4-2.sh
Labels: Test Completed, Minor Repair

#337 add challenge-simple-shopping-cart
  python/challenge-simple-shopping-cart/assets/shopping_cart.py
  python/challenge-simple-shopping-cart/assets/step1_test.py
  python/challenge-simple-shopping-cart/assets/step2_test.py
  python/challenge-simple-shopping-cart/assets/step3_test.py
  python/challenge-simple-shopping-cart/finish.md
  python/challenge-simple-shopping-cart/index.json
  python/challenge-simple-shopping-cart/intro.md
  python/challenge-simple-shopping-cart/setup.sh
  python/challenge-simple-shopping-cart/solutions/step1-solution.md
  python/challenge-simple-shopping-cart/solutions/step2-solution.md
  python/challenge-simple-shopping-cart/solutions/step3-solution.md
  python/challenge-simple-shopping-cart/step1.md
  python/challenge-simple-shopping-cart/step2.md
  python/challenge-simple-shopping-cart/step3.md
  python/challenge-simple-shopping-cart/verify1.sh
  python/challenge-simple-shopping-cart/verify2.sh
  python/challenge-simple-shopping-cart/verify3.sh
Labels: Test Completed

#163 Add challenge word solitaire
  python/challenge-word-solitaire/assets/solitaire.py
  python/challenge-word-solitaire/assets/solitaire_test.py
  python/challenge-word-solitaire/assets/split_sentence.py
  python/challenge-word-solitaire/assets/split_sentence_test.py
  python/challenge-word-solitaire/finish.md
  python/challenge-word-solitaire/index.json
  python/challenge-word-solitaire/intro.md
  python/challenge-word-solitaire/setup.sh
  python/challenge-word-solitaire/solutions/solitaire.py
  python/challenge-word-solitaire/solutions/solution.md
  python/challenge-word-solitaire/solutions/split_sentence.py
  python/challenge-word-solitaire/step1.md
  python/challenge-word-solitaire/step2.md
  python/challenge-word-solitaire/verify1.sh
  python/challenge-word-solitaire/verify2.sh
Labels: Test Completed, Minor Repair

#320 lab-variables-and-memory-addresses
  python/lab-variables-and-memory-addresses/finish.md
  python/lab-variables-and-memory-addresses/index.json
  python/lab-variables-and-memory-addresses/intro.md
  python/lab-variables-and-memory-addresses/setup.sh
  python/lab-variables-and-memory-addresses/step1.md
  python/lab-variables-and-memory-addresses/step2.md
  python/lab-variables-and-memory-addresses/step3.md
  python/lab-variables-and-memory-addresses/step4.md
  python/lab-variables-and-memory-addresses/verify1.sh
  python/lab-variables-and-memory-addresses/verify2-1.sh
  python/lab-variables-and-memory-addresses/verify2-2.sh
  python/lab-variables-and-memory-addresses/verify3.sh
  python/lab-variables-and-memory-addresses/verify4.sh
Labels: Test Completed, Major Repair

#190 Add challenge cancel file change
  linux/challenge-cancel-file-change/finish.md
  linux/challenge-cancel-file-change/index.json
  linux/challenge-cancel-file-change/intro.md
  linux/challenge-cancel-file-change/setup.sh
  linux/challenge-cancel-file-change/solutions/step1-solution.md
  linux/challenge-cancel-file-change/solutions/step2-solution.md
  linux/challenge-cancel-file-change/solutions/step3-solution.md
  linux/challenge-cancel-file-change/step1.md
  linux/challenge-cancel-file-change/step2.md
  linux/challenge-cancel-file-change/step3.md
  linux/challenge-cancel-file-change/verify1.sh
  linux/challenge-cancel-file-change/verify2.sh
  linux/challenge-cancel-file-change/verify3.sh
Labels: Test Completed, Major Repair

#194 Add challenge submit files
  linux/challenge-submit-files/finish.md
  linux/challenge-submit-files/index.json
  linux/challenge-submit-files/intro.md
  linux/challenge-submit-files/setup.sh
  linux/challenge-submit-files/solutions/step1-solution.md
  linux/challenge-submit-files/solutions/step2-solution.md
  linux/challenge-submit-files/solutions/step3-solution.md
  linux/challenge-submit-files/solutions/step4-solution.md
  linux/challenge-submit-files/step1.md
  linux/challenge-submit-files/step2.md
  linux/challenge-submit-files/step3.md
  linux/challenge-submit-files/step4.md
  linux/challenge-submit-files/verify1.sh
  linux/challenge-submit-files/verify2.sh
  linux/challenge-submit-files/verify3.sh
  linux/challenge-submit-files/verify4.sh
Labels: Test Completed, Minor Repair

#359 add challenge-customized-greetings
  python/challenge-customized-greetings/assets/greet.py
  python/challenge-customized-greetings/assets/greet_test.py
  python/challenge-customized-greetings/finish.md
  python/challenge-customized-greetings/index.json
  python/challenge-customized-greetings/intro.md
  python/challenge-customized-greetings/setup.sh
  python/challenge-customized-greetings/solutions/step1-solution.py
  python/challenge-customized-greetings/step1.md
  python/challenge-customized-greetings/verify1.sh
Labels: Test Completed, No Repair

#362 add lab python is operator
  python/lab-python-is-operator/finish.md
  python/lab-python-is-operator/index.json
  python/lab-python-is-operator/intro.md
  python/lab-python-is-operator/setup.sh
  python/lab-python-is-operator/step1.md
  python/lab-python-is-operator/step2.md
  python/lab-python-is-operator/step3.md
  python/lab-python-is-operator/step4.md
  python/lab-python-is-operator/verify1-0.sh
  python/lab-python-is-operator/verify1-1.sh
  python/lab-python-is-operator/verify2.sh
  python/lab-python-is-operator/verify3.sh
  python/lab-python-is-operator/verify4.sh
Labels: Test Completed, No Repair

#358 Add lab-collections-module
  python/lab-collections-module/assets/counter.py
  python/lab-collections-module/assets/default_dict1.py
  python/lab-collections-module/assets/default_dict2.py
  python/lab-collections-module/assets/default_dict3.py
  python/lab-collections-module/assets/deque.py
  python/lab-collections-module/assets/named_tuple.py
  python/lab-collections-module/assets/ordered_dict.py
  python/lab-collections-module/finish.md
  python/lab-collections-module/index.json
  python/lab-collections-module/intro.md
  python/lab-collections-module/setup.sh
  python/lab-collections-module/step1.md
  python/lab-collections-module/step2.md
  python/lab-collections-module/step3.md
  python/lab-collections-module/step4.md
  python/lab-collections-module/step5.md
  python/lab-collections-module/verify1-0.sh
  python/lab-collections-module/verify1-1.sh
  python/lab-collections-module/verify1-2.sh
  python/lab-collections-module/verify2-0.sh
  python/lab-collections-module/verify2-1.sh
  python/lab-collections-module/verify3-0.sh
  python/lab-collections-module/verify3-1.sh
  python/lab-collections-module/verify4-0.sh
  python/lab-collections-module/verify4-1.sh
  python/lab-collections-module/verify4-2.sh
  python/lab-collections-module/verify4-3.sh
  python/lab-collections-module/verify4-4.sh
  python/lab-collections-module/verify4-5.sh
  python/lab-collections-module/verify5-0.sh
  python/lab-collections-module/verify5-1.sh
Labels: Test Completed

#324 add lab-array-attributes-and-dtype
  python/lab-array-attributes-and-dtype/finish.md
  python/lab-array-attributes-and-dtype/index.json
  python/lab-array-attributes-and-dtype/intro.md
  python/lab-array-attributes-and-dtype/setup.sh
  python/lab-array-attributes-and-dtype/step1.md
  python/lab-array-attributes-and-dtype/step2.md
  python/lab-array-attributes-and-dtype/step3.md
  python/lab-array-attributes-and-dtype/verify1-1.sh
  python/lab-array-attributes-and-dtype/verify1-2.sh
  python/lab-array-attributes-and-dtype/verify2.sh
  python/lab-array-attributes-and-dtype/verify3.sh
Labels: Test Completed, Major Repair

#371 Add challenge-analyzing-disk-usage
  linux/challenge-analyzing-disk-usage/finish.md
  linux/challenge-analyzing-disk-usage/index.json
  linux/challenge-analyzing-disk-usage/intro.md
  linux/challenge-analyzing-disk-usage/setup.sh
  linux/challenge-analyzing-disk-usage/solutions/step1-solution.md
  linux/challenge-analyzing-disk-usage/solutions/step2-solution.md
  linux/challenge-analyzing-disk-usage/solutions/step3-solution.md
  linux/challenge-analyzing-disk-usage/step1.md
  linux/challenge-analyzing-disk-usage/step2.md
  linux/challenge-analyzing-disk-usage/step3.md
  linux/challenge-analyzing-disk-usage/verify1.sh
  linux/challenge-analyzing-disk-usage/verify2.sh
  linux/challenge-analyzing-disk-usage/verify3.sh
Labels: Test Completed, Major Repair

#350 add python/challenge-find-expressions
  python/challenge-find-expressions/assets/find_expressions.py
  python/challenge-find-expressions/assets/find_expressions_test.py
  python/challenge-find-expressions/finish.md
  python/challenge-find-expressions/index.json
  python/challenge-find-expressions/intro.md
  python/challenge-find-expressions/setup.sh
  python/challenge-find-expressions/solutions/find_expressions.py
  python/challenge-find-expressions/solutions/solution.md
  python/challenge-find-expressions/step1.md
  python/challenge-find-expressions/verify1.sh
Labels: Test Completed

#378 Add challenge-dictionary-key-value-swapper
  python/challenge-dictionary-key-value-swapper/assets/swap_dict.py
  python/challenge-dictionary-key-value-swapper/assets/test_swap_dict.py
  python/challenge-dictionary-key-value-swapper/finish.md
  python/challenge-dictionary-key-value-swapper/index.json
  python/challenge-dictionary-key-value-swapper/intro.md
  python/challenge-dictionary-key-value-swapper/setup.sh
  python/challenge-dictionary-key-value-swapper/solutions/swap_dict.py
  python/challenge-dictionary-key-value-swapper/step1.md
  python/challenge-dictionary-key-value-swapper/verify1.sh
Labels: Test Completed, No Repair

#411 add-challenge-sum-of-all-even-numbers
  python/challenge-sum-of-all-even-numbers/assets/even_sum.py
  python/challenge-sum-of-all-even-numbers/assets/even_sum_test.py
  python/challenge-sum-of-all-even-numbers/finish.md
  python/challenge-sum-of-all-even-numbers/index.json
  python/challenge-sum-of-all-even-numbers/intro.md
  python/challenge-sum-of-all-even-numbers/setup.sh
  python/challenge-sum-of-all-even-numbers/solutions/even_sum.py
  python/challenge-sum-of-all-even-numbers/solutions/step1-solution.md
  python/challenge-sum-of-all-even-numbers/step1.md
  python/challenge-sum-of-all-even-numbers/verify1.sh
Labels: Test Completed, No Repair

#396 Lab accessing and managing docker container
  docker/lab-accessing-and-managing-docker-container/assets/lab-accessing-and-managing-docker-container-1-1.png
  docker/lab-accessing-and-managing-docker-container/finish.md
  docker/lab-accessing-and-managing-docker-container/index.json
  docker/lab-accessing-and-managing-docker-container/intro.md
  docker/lab-accessing-and-managing-docker-container/setup.sh
  docker/lab-accessing-and-managing-docker-container/step1.md
  docker/lab-accessing-and-managing-docker-container/step2.md
  docker/lab-accessing-and-managing-docker-container/step3.md
  docker/lab-accessing-and-managing-docker-container/step4.md
  docker/lab-accessing-and-managing-docker-container/verify1-1.sh
  docker/lab-accessing-and-managing-docker-container/verify1-2.sh
  docker/lab-accessing-and-managing-docker-container/verify2.sh
  docker/lab-accessing-and-managing-docker-container/verify3-3.sh
  docker/lab-accessing-and-managing-docker-container/verify4.sh
Labels: Test Completed, Major Repair

#329 add challenge-linear-algebra-solving-with-numpy
  python/challenge-linear-algebra-solving-with-numpy/assets/determinant_matrix.py
  python/challenge-linear-algebra-solving-with-numpy/assets/determinant_matrix_test.py
  python/challenge-linear-algebra-solving-with-numpy/assets/eigenvector_eigenvalue.py
  python/challenge-linear-algebra-solving-with-numpy/assets/eigenvector_eigenvalue_test.py
  python/challenge-linear-algebra-solving-with-numpy/assets/invert_matrix.py
  python/challenge-linear-algebra-solving-with-numpy/assets/invert_matrix_test.py
  python/challenge-linear-algebra-solving-with-numpy/assets/matrix_rank.py
  python/challenge-linear-algebra-solving-with-numpy/assets/matrix_rank_test.py
  python/challenge-linear-algebra-solving-with-numpy/assets/solve_linear_equation.py
  python/challenge-linear-algebra-solving-with-numpy/assets/solve_linear_equation_test.py
  python/challenge-linear-algebra-solving-with-numpy/assets/svd_matrix.py
  python/challenge-linear-algebra-solving-with-numpy/assets/svd_matrix_test.py
  python/challenge-linear-algebra-solving-with-numpy/finish.md
  python/challenge-linear-algebra-solving-with-numpy/index.json
  python/challenge-linear-algebra-solving-with-numpy/intro.md
  python/challenge-linear-algebra-solving-with-numpy/setup.sh
  python/challenge-linear-algebra-solving-with-numpy/solutions/determinant_matrix.py
  python/challenge-linear-algebra-solving-with-numpy/solutions/eigenvector_eigenvalue.py
  python/challenge-linear-algebra-solving-with-numpy/solutions/invert_matrix.py
  python/challenge-linear-algebra-solving-with-numpy/solutions/matrix_rank.py
  python/challenge-linear-algebra-solving-with-numpy/solutions/solution.md
  python/challenge-linear-algebra-solving-with-numpy/solutions/solve_linear_equation.py
  python/challenge-linear-algebra-solving-with-numpy/solutions/svd_matrix.py
  python/challenge-linear-algebra-solving-with-numpy/step1.md
  python/challenge-linear-algebra-solving-with-numpy/step2.md
  python/challenge-linear-algebra-solving-with-numpy/step3.md
  python/challenge-linear-algebra-solving-with-numpy/step4.md
  python/challenge-linear-algebra-solving-with-numpy/step5.md
  python/challenge-linear-algebra-solving-with-numpy/step6.md
  python/challenge-linear-algebra-solving-with-numpy/verify1.sh
  python/challenge-linear-algebra-solving-with-numpy/verify2.sh
  python/challenge-linear-algebra-solving-with-numpy/verify3.sh
  python/challenge-linear-algebra-solving-with-numpy/verify4.sh
  python/challenge-linear-algebra-solving-with-numpy/verify5.sh
  python/challenge-linear-algebra-solving-with-numpy/verify6.sh
Labels: Test Completed, Major Repair

#388 Add lab-groups-of-linux
  linux/lab-what-are-the-groups-of-linux/finish.md
  linux/lab-what-are-the-groups-of-linux/index.json
  linux/lab-what-are-the-groups-of-linux/intro.md
  linux/lab-what-are-the-groups-of-linux/setup.sh
  linux/lab-what-are-the-groups-of-linux/step1.md
  linux/lab-what-are-the-groups-of-linux/step2.md
  linux/lab-what-are-the-groups-of-linux/step3.md
  linux/lab-what-are-the-groups-of-linux/verify1.sh
  linux/lab-what-are-the-groups-of-linux/verify2.sh
  linux/lab-what-are-the-groups-of-linux/verify3.sh
Labels: Test Completed, Minor Repair

#369 add challenge automate webpage opening
  python/challenge-automate-webpage-opening/assets/webbrowser_challenge.py
  python/challenge-automate-webpage-opening/finish.md
  python/challenge-automate-webpage-opening/index.json
  python/challenge-automate-webpage-opening/intro.md
  python/challenge-automate-webpage-opening/setup.sh
  python/challenge-automate-webpage-opening/solutions/step1-solution.md
  python/challenge-automate-webpage-opening/step1.md
  python/challenge-automate-webpage-opening/verify1.sh
Labels: Test Completed, Minor Repair

#403 Add challenge-find-the-flags
  linux/challenge-find-the-flags/finish.md
  linux/challenge-find-the-flags/index.json
  linux/challenge-find-the-flags/intro.md
  linux/challenge-find-the-flags/setup.sh
  linux/challenge-find-the-flags/solutions/step1-solution.md
  linux/challenge-find-the-flags/solutions/step2-solution.md
  linux/challenge-find-the-flags/solutions/step3-solution.md
  linux/challenge-find-the-flags/solutions/step4-solution.md
  linux/challenge-find-the-flags/step1.md
  linux/challenge-find-the-flags/step2.md
  linux/challenge-find-the-flags/step3.md
  linux/challenge-find-the-flags/step4.md
  linux/challenge-find-the-flags/verify1.sh
  linux/challenge-find-the-flags/verify2.sh
  linux/challenge-find-the-flags/verify3.sh
  linux/challenge-find-the-flags/verify4.sh
Labels: Test Completed, Major Repair

#438 Add challenge-file-viewing
  linux/challenge-file-viewing/finish.md
  linux/challenge-file-viewing/index.json
  linux/challenge-file-viewing/intro.md
  linux/challenge-file-viewing/setup.sh
  linux/challenge-file-viewing/solutions/step1-solution.md
  linux/challenge-file-viewing/solutions/step2-solution.md
  linux/challenge-file-viewing/solutions/step3-solution.md
  linux/challenge-file-viewing/solutions/step4-solution.md
  linux/challenge-file-viewing/solutions/step5-solution.md
  linux/challenge-file-viewing/step1.md
  linux/challenge-file-viewing/step2.md
  linux/challenge-file-viewing/step3.md
  linux/challenge-file-viewing/step4.md
  linux/challenge-file-viewing/step5.md
  linux/challenge-file-viewing/verify1.sh
  linux/challenge-file-viewing/verify2.sh
  linux/challenge-file-viewing/verify3.sh
  linux/challenge-file-viewing/verify4.sh
  linux/challenge-file-viewing/verify5.sh
Labels: Test Completed, No Repair

#441 Add challenge-stream-editor-sed
  linux/challenge-stream-editor-sed/finish.md
  linux/challenge-stream-editor-sed/index.json
  linux/challenge-stream-editor-sed/intro.md
  linux/challenge-stream-editor-sed/setup.sh
  linux/challenge-stream-editor-sed/solutions/step1-solution.md
  linux/challenge-stream-editor-sed/solutions/step2-solution.md
  linux/challenge-stream-editor-sed/solutions/step3-solution.md
  linux/challenge-stream-editor-sed/solutions/step4-solution.md
  linux/challenge-stream-editor-sed/step1.md
  linux/challenge-stream-editor-sed/step2.md
  linux/challenge-stream-editor-sed/step3.md
  linux/challenge-stream-editor-sed/step4.md
  linux/challenge-stream-editor-sed/verify1.sh
  linux/challenge-stream-editor-sed/verify2.sh
  linux/challenge-stream-editor-sed/verify3.sh
  linux/challenge-stream-editor-sed/verify4.sh
Labels: Test Completed, No Repair

#451 add challenge-jewelry-sales
  python/challenge-jewelry-sales/assets/jewelry_sales.py
  python/challenge-jewelry-sales/assets/jewelry_sales_unittest.py
  python/challenge-jewelry-sales/finish.md
  python/challenge-jewelry-sales/index.json
  python/challenge-jewelry-sales/intro.md
  python/challenge-jewelry-sales/setup.sh
  python/challenge-jewelry-sales/solutions/jewelry_sales.py
  python/challenge-jewelry-sales/step1.md
  python/challenge-jewelry-sales/verify1.sh
Labels: Test Completed, No Repair

#394 add: lab-docker-lifecycle-management
  docker/lab-docker-lifecycle-management/finish.md
  docker/lab-docker-lifecycle-management/index.json
  docker/lab-docker-lifecycle-management/intro.md
  docker/lab-docker-lifecycle-management/setup.sh
  docker/lab-docker-lifecycle-management/step1.md
  docker/lab-docker-lifecycle-management/step2.md
  docker/lab-docker-lifecycle-management/step3.md
  docker/lab-docker-lifecycle-management/step4.md
  docker/lab-docker-lifecycle-management/verify1-1.sh
  docker/lab-docker-lifecycle-management/verify1-2.sh
  docker/lab-docker-lifecycle-management/verify1-3.sh
  docker/lab-docker-lifecycle-management/verify2.sh
  docker/lab-docker-lifecycle-management/verify3-1.sh
  docker/lab-docker-lifecycle-management/verify3-2.sh
  docker/lab-docker-lifecycle-management/verify4-1.sh
  docker/lab-docker-lifecycle-management/verify4-2.sh
Labels: Test Completed, Minor Repair

#482 Add challenge log parsing(version2)
  python/challenge-log-parsing/assets/access.log
  python/challenge-log-parsing/assets/read_log.py
  python/challenge-log-parsing/assets/read_log_test.py
  python/challenge-log-parsing/assets/time_statistics.py
  python/challenge-log-parsing/assets/time_statistics_test.py
  python/challenge-log-parsing/assets/uri_count.py
  python/challenge-log-parsing/assets/uri_count_test.py
  python/challenge-log-parsing/finish.md
  python/challenge-log-parsing/index.json
  python/challenge-log-parsing/intro.md
  python/challenge-log-parsing/setup.sh
  python/challenge-log-parsing/solutions/read_log.py
  python/challenge-log-parsing/solutions/solution.md
  python/challenge-log-parsing/solutions/time_statistics.py
  python/challenge-log-parsing/solutions/uri_count.py
  python/challenge-log-parsing/step1.md
  python/challenge-log-parsing/step2.md
  python/challenge-log-parsing/step3.md
  python/challenge-log-parsing/verify1.sh
  python/challenge-log-parsing/verify2.sh
  python/challenge-log-parsing/verify3.sh
Labels: Test Completed

#467 Challenge voting system
  python/challenge-voting-system/assets/calculate_winner.py
  python/challenge-voting-system/assets/calculate_winner_test.py
  python/challenge-voting-system/finish.md
  python/challenge-voting-system/index.json
  python/challenge-voting-system/intro.md
  python/challenge-voting-system/setup.sh
  python/challenge-voting-system/solutions/calculate_winner.py
  python/challenge-voting-system/step1.md
  python/challenge-voting-system/verify1.sh
Labels: Test Completed

#468 Challenge printing a triangle
  python/challenge-printing-a-triangle/assets/print_triangle.py
  python/challenge-printing-a-triangle/assets/print_triangle_test.py
  python/challenge-printing-a-triangle/finish.md
  python/challenge-printing-a-triangle/index.json
  python/challenge-printing-a-triangle/intro.md
  python/challenge-printing-a-triangle/setup.sh
  python/challenge-printing-a-triangle/solutions/print_triangle.py
  python/challenge-printing-a-triangle/step1.md
  python/challenge-printing-a-triangle/verify1.sh
Labels: Test Completed, No Repair

#440 Add challenge basic python math operators
  python/challenge-basic-python-math-operators/assets/math_operations.py
  python/challenge-basic-python-math-operators/assets/math_operations_test.py
  python/challenge-basic-python-math-operators/finish.md
  python/challenge-basic-python-math-operators/index.json
  python/challenge-basic-python-math-operators/intro.md
  python/challenge-basic-python-math-operators/setup.sh
  python/challenge-basic-python-math-operators/solutions/math_operations.py
  python/challenge-basic-python-math-operators/step1.md
  python/challenge-basic-python-math-operators/verify1.sh
Labels: Test Completed, No Repair

#453 add-challenge-long-word-counter
  python/challenge-long-word-counter/assets/count_long_words.py
  python/challenge-long-word-counter/assets/count_long_words_test.py
  python/challenge-long-word-counter/finish.md
  python/challenge-long-word-counter/index.json
  python/challenge-long-word-counter/intro.md
  python/challenge-long-word-counter/setup.sh
  python/challenge-long-word-counter/solutions/count_long_words.py
  python/challenge-long-word-counter/step1.md
  python/challenge-long-word-counter/verify1.sh
Labels: Test Completed, No Repair

#431 Add challenge local and global scope
  python/challenge-local-and-global-scope/assets/step1.py
  python/challenge-local-and-global-scope/assets/step1_test.py
  python/challenge-local-and-global-scope/assets/step2.py
  python/challenge-local-and-global-scope/assets/step2_test.py
  python/challenge-local-and-global-scope/finish.md
  python/challenge-local-and-global-scope/index.json
  python/challenge-local-and-global-scope/intro.md
  python/challenge-local-and-global-scope/setup.sh
  python/challenge-local-and-global-scope/solutions/step1-solution.md
  python/challenge-local-and-global-scope/solutions/step1.py
  python/challenge-local-and-global-scope/solutions/step2-solution.md
  python/challenge-local-and-global-scope/solutions/step2.py
  python/challenge-local-and-global-scope/step1.md
  python/challenge-local-and-global-scope/step2.md
  python/challenge-local-and-global-scope/verify1.sh
  python/challenge-local-and-global-scope/verify2.sh
Labels: Test Completed, Minor Repair

#407 Challenge count duplicates
  python/challenge-count-duplicates/assets/count_duplicates.py
  python/challenge-count-duplicates/assets/count_duplicates_test.py
  python/challenge-count-duplicates/finish.md
  python/challenge-count-duplicates/index.json
  python/challenge-count-duplicates/intro.md
  python/challenge-count-duplicates/setup.sh
  python/challenge-count-duplicates/solutions/count_duplicates.py
  python/challenge-count-duplicates/step1.md
  python/challenge-count-duplicates/verify1.sh
Labels: Test Completed, Minor Repair

#473 Lab kubernetes proxy command
  kubernetes/lab-kubernetes-proxy-command/finish.md
  kubernetes/lab-kubernetes-proxy-command/index.json
  kubernetes/lab-kubernetes-proxy-command/intro.md
  kubernetes/lab-kubernetes-proxy-command/setup.sh
  kubernetes/lab-kubernetes-proxy-command/step1.md
  kubernetes/lab-kubernetes-proxy-command/step2.md
  kubernetes/lab-kubernetes-proxy-command/verify1.sh
  kubernetes/lab-kubernetes-proxy-command/verify2.sh
Labels: Test Completed

#464 Lab kubernetes logs command
  kubernetes/lab-kubernetes-logs-command/finish.md
  kubernetes/lab-kubernetes-logs-command/index.json
  kubernetes/lab-kubernetes-logs-command/intro.md
  kubernetes/lab-kubernetes-logs-command/setup.sh
  kubernetes/lab-kubernetes-logs-command/step1.md
  kubernetes/lab-kubernetes-logs-command/step2.md
  kubernetes/lab-kubernetes-logs-command/step3.md
  kubernetes/lab-kubernetes-logs-command/step4.md
  kubernetes/lab-kubernetes-logs-command/verify1-1.sh
  kubernetes/lab-kubernetes-logs-command/verify1-2.sh
  kubernetes/lab-kubernetes-logs-command/verify2-1.sh
  kubernetes/lab-kubernetes-logs-command/verify2-2.sh
  kubernetes/lab-kubernetes-logs-command/verify3-1.sh
  kubernetes/lab-kubernetes-logs-command/verify3-2.sh
  kubernetes/lab-kubernetes-logs-command/verify3-3.sh
  kubernetes/lab-kubernetes-logs-command/verify4-1.sh
  kubernetes/lab-kubernetes-logs-command/verify4-2.sh
Labels: Test Completed, Minor Repair

#463 Lab kubernetes describe command
  kubernetes/lab-kubernetes-describe-command/finish.md
  kubernetes/lab-kubernetes-describe-command/index.json
  kubernetes/lab-kubernetes-describe-command/intro.md
  kubernetes/lab-kubernetes-describe-command/setup.sh
  kubernetes/lab-kubernetes-describe-command/step1.md
  kubernetes/lab-kubernetes-describe-command/step2.md
  kubernetes/lab-kubernetes-describe-command/step3.md
  kubernetes/lab-kubernetes-describe-command/verify1-1.sh
  kubernetes/lab-kubernetes-describe-command/verify1-2.sh
  kubernetes/lab-kubernetes-describe-command/verify2-1.sh
  kubernetes/lab-kubernetes-describe-command/verify2-2.sh
  kubernetes/lab-kubernetes-describe-command/verify3-1.sh
  kubernetes/lab-kubernetes-describe-command/verify3-2.sh
Labels: Test Completed, Minor Repair

#393 Add lab managing data in containers
  docker/lab-managing-data-in-containers/assets/lab-managing-data-in-containers-1.png
  docker/lab-managing-data-in-containers/assets/lab-managing-data-in-containers-2-1.png
  docker/lab-managing-data-in-containers/assets/lab-managing-data-in-containers-2-2.png
  docker/lab-managing-data-in-containers/assets/lab-managing-data-in-containers-3.png
  docker/lab-managing-data-in-containers/assets/lab-managing-data-in-containers-4.png
  docker/lab-managing-data-in-containers/assets/lab-managing-data-in-containers-5-1.png
  docker/lab-managing-data-in-containers/assets/lab-managing-data-in-containers-5-2.png
  docker/lab-managing-data-in-containers/assets/lab-managing-data-in-containers-5-3.png
  docker/lab-managing-data-in-containers/assets/lab-managing-data-in-containers-5-4.png
  docker/lab-managing-data-in-containers/finish.md
  docker/lab-managing-data-in-containers/index.json
  docker/lab-managing-data-in-containers/intro.md
  docker/lab-managing-data-in-containers/setup.sh
  docker/lab-managing-data-in-containers/step1.md
  docker/lab-managing-data-in-containers/step2.md
  docker/lab-managing-data-in-containers/step3.md
  docker/lab-managing-data-in-containers/step4.md
  docker/lab-managing-data-in-containers/step5.md
  docker/lab-managing-data-in-containers/verify1.sh
  docker/lab-managing-data-in-containers/verify2.sh
  docker/lab-managing-data-in-containers/verify3.sh
  docker/lab-managing-data-in-containers/verify4.sh
  docker/lab-managing-data-in-containers/verify5.sh
Labels: Test Completed, Minor Repair

#452 Challenge leap year checker
  python/challenge-leap-year-checker/assets/is_leap_year.py
  python/challenge-leap-year-checker/assets/is_leap_year_test.py
  python/challenge-leap-year-checker/finish.md
  python/challenge-leap-year-checker/index.json
  python/challenge-leap-year-checker/intro.md
  python/challenge-leap-year-checker/setup.sh
  python/challenge-leap-year-checker/solutions/is_leap_year.py
  python/challenge-leap-year-checker/step1.md
  python/challenge-leap-year-checker/verify1.sh
Labels: Test Completed, Minor Repair

#455 Challenge finding the intersection of two lists
  python/challenge-finding-the-intersection-of-two-lists/assets/find_intersection.py
  python/challenge-finding-the-intersection-of-two-lists/assets/find_intersection_test.py
  python/challenge-finding-the-intersection-of-two-lists/finish.md
  python/challenge-finding-the-intersection-of-two-lists/index.json
  python/challenge-finding-the-intersection-of-two-lists/intro.md
  python/challenge-finding-the-intersection-of-two-lists/setup.sh
  python/challenge-finding-the-intersection-of-two-lists/solutions/find_intersection.py
  python/challenge-finding-the-intersection-of-two-lists/step1.md
  python/challenge-finding-the-intersection-of-two-lists/verify1.sh
Labels: Test Completed, Minor Repair

#443 add-challenge-recipe-recommendation
  python/challenge-recipe-recommendation/assets/recipe_recommendation.py
  python/challenge-recipe-recommendation/assets/recipe_recommendation_test.py
  python/challenge-recipe-recommendation/finish.md
  python/challenge-recipe-recommendation/index.json
  python/challenge-recipe-recommendation/intro.md
  python/challenge-recipe-recommendation/setup.sh
  python/challenge-recipe-recommendation/solutions/recipe_recommendation.py
  python/challenge-recipe-recommendation/step1.md
  python/challenge-recipe-recommendation/verify1.sh
Labels: Test Completed, No Repair

#480 Add lab docker multi stage build
  docker/lab-docker-multi-stage-build/assets/lab-docker-multi-stage-build-1-1.png
  docker/lab-docker-multi-stage-build/assets/lab-docker-multi-stage-build-1-2.png
  docker/lab-docker-multi-stage-build/assets/lab-docker-multi-stage-build-1-3.png
  docker/lab-docker-multi-stage-build/assets/lab-docker-multi-stage-build-2-1.png
  docker/lab-docker-multi-stage-build/assets/lab-docker-multi-stage-build-2-2.png
  docker/lab-docker-multi-stage-build/assets/lab-docker-multi-stage-build-2-3.png
  docker/lab-docker-multi-stage-build/assets/lab-docker-multi-stage-build-3-1.png
  docker/lab-docker-multi-stage-build/assets/lab-docker-multi-stage-build-3-2.png
  docker/lab-docker-multi-stage-build/assets/lab-docker-multi-stage-build-3-3.png
  docker/lab-docker-multi-stage-build/finish.md
  docker/lab-docker-multi-stage-build/index.json
  docker/lab-docker-multi-stage-build/intro.md
  docker/lab-docker-multi-stage-build/setup.sh
  docker/lab-docker-multi-stage-build/step1.md
  docker/lab-docker-multi-stage-build/step2.md
  docker/lab-docker-multi-stage-build/step3.md
  docker/lab-docker-multi-stage-build/verify1-1.sh
  docker/lab-docker-multi-stage-build/verify1-2.sh
  docker/lab-docker-multi-stage-build/verify2.sh
  docker/lab-docker-multi-stage-build/verify3.sh
Labels: Test Completed, Minor Repair

#457 Add lab custom docker images
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-1-1.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-1-2.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-1-3.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-1-4.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-1-5.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-1-6.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-1-7.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-2-1.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-2-2.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-2-3.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-2-4.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-2-5.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-3-1.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-3-2.png
  docker/lab-custom-docker-images/assets/lab-custom-docker-images-3-3.png
  docker/lab-custom-docker-images/finish.md
  docker/lab-custom-docker-images/index.json
  docker/lab-custom-docker-images/intro.md
  docker/lab-custom-docker-images/setup.sh
  docker/lab-custom-docker-images/step1.md
  docker/lab-custom-docker-images/step2.md
  docker/lab-custom-docker-images/step3.md
  docker/lab-custom-docker-images/verify1-1.sh
  docker/lab-custom-docker-images/verify1-2.sh
  docker/lab-custom-docker-images/verify1-3.sh
  docker/lab-custom-docker-images/verify1-4.sh
  docker/lab-custom-docker-images/verify2-1.sh
  docker/lab-custom-docker-images/verify2-2.sh
  docker/lab-custom-docker-images/verify2-3.sh
  docker/lab-custom-docker-images/verify2-4.sh
  docker/lab-custom-docker-images/verify3-1.sh
  docker/lab-custom-docker-images/verify3-2.sh
  docker/lab-custom-docker-images/verify3-3.sh
  docker/lab-custom-docker-images/verify3-4.sh
Labels: Test Completed, Minor Repair

#515 Add challenge-group-of-linux
  linux/challenge-group-of-linux/finish.md
  linux/challenge-group-of-linux/index.json
  linux/challenge-group-of-linux/intro.md
  linux/challenge-group-of-linux/setup.sh
  linux/challenge-group-of-linux/solutions/step1-solution.md
  linux/challenge-group-of-linux/solutions/step2-solution.md
  linux/challenge-group-of-linux/solutions/step3-solution.md
  linux/challenge-group-of-linux/step1.md
  linux/challenge-group-of-linux/step2.md
  linux/challenge-group-of-linux/step3.md
  linux/challenge-group-of-linux/verify1.sh
  linux/challenge-group-of-linux/verify2.sh
  linux/challenge-group-of-linux/verify3.sh
Labels: Test Completed

#516 Challenge school exam grader
  python/challenge-school-exam-grader/assets/grade_exam.py
  python/challenge-school-exam-grader/assets/grade_exam_test.py
  python/challenge-school-exam-grader/finish.md
  python/challenge-school-exam-grader/index.json
  python/challenge-school-exam-grader/intro.md
  python/challenge-school-exam-grader/setup.sh
  python/challenge-school-exam-grader/solutions/grade_exam.py
  python/challenge-school-exam-grader/step1.md
  python/challenge-school-exam-grader/verify1.sh
Labels: Test Completed, No Repair

#386 Add challenge-complete-a-json-parser
  python/challenge-complete-a-json-parser/assets/json_lib_test1.py
  python/challenge-complete-a-json-parser/assets/json_lib_test2.py
  python/challenge-complete-a-json-parser/assets/parse_json.py
  python/challenge-complete-a-json-parser/assets/parse_json_test.py
  python/challenge-complete-a-json-parser/assets/serialize_json.py
  python/challenge-complete-a-json-parser/assets/serialize_json_test.py
  python/challenge-complete-a-json-parser/finish.md
  python/challenge-complete-a-json-parser/index.json
  python/challenge-complete-a-json-parser/intro.md
  python/challenge-complete-a-json-parser/setup.sh
  python/challenge-complete-a-json-parser/solutions/parse_json.py
  python/challenge-complete-a-json-parser/solutions/serialize_json.py
  python/challenge-complete-a-json-parser/step1.md
  python/challenge-complete-a-json-parser/step2.md
  python/challenge-complete-a-json-parser/verify1.sh
  python/challenge-complete-a-json-parser/verify2.sh
  python/challenge-complete-a-json-parser/verify3.sh
  python/challenge-complete-a-json-parser/verify4.sh
Labels: Test Completed, Major Repair

#521 Lab kubernetes set command
  kubernetes/lab-kubernetes-set-command/finish.md
  kubernetes/lab-kubernetes-set-command/index.json
  kubernetes/lab-kubernetes-set-command/intro.md
  kubernetes/lab-kubernetes-set-command/setup.sh
  kubernetes/lab-kubernetes-set-command/step1.md
  kubernetes/lab-kubernetes-set-command/step2.md
  kubernetes/lab-kubernetes-set-command/verify1-1.sh
  kubernetes/lab-kubernetes-set-command/verify1-2.sh
  kubernetes/lab-kubernetes-set-command/verify1-3.sh
  kubernetes/lab-kubernetes-set-command/verify2-1.sh
  kubernetes/lab-kubernetes-set-command/verify2-2.sh
Labels: Test Completed, No Repair

#525 Add lab display cluster info
  kubernetes/lab-display-cluster-info/assets/lab-display-cluster-info-1.png
  kubernetes/lab-display-cluster-info/assets/lab-display-cluster-info-2.png
  kubernetes/lab-display-cluster-info/finish.md
  kubernetes/lab-display-cluster-info/index.json
  kubernetes/lab-display-cluster-info/intro.md
  kubernetes/lab-display-cluster-info/setup.sh
  kubernetes/lab-display-cluster-info/step1.md
  kubernetes/lab-display-cluster-info/step2.md
  kubernetes/lab-display-cluster-info/verify1.sh
  kubernetes/lab-display-cluster-info/verify2.sh
Labels: Test Completed, No Repair

#366 add challenge-set-intersection
  python/challenge-set-intersection/assets/set.py
  python/challenge-set-intersection/assets/set_test.py
  python/challenge-set-intersection/finish.md
  python/challenge-set-intersection/index.json
  python/challenge-set-intersection/intro.md
  python/challenge-set-intersection/setup.sh
  python/challenge-set-intersection/solutions/step1-solution.py
  python/challenge-set-intersection/step1.md
  python/challenge-set-intersection/verify1.sh
Labels: Test Completed, Minor Repair, Stale

#531 Add challenge-special-operations-with-files
  linux/challenge-special-operations-with-files/finish.md
  linux/challenge-special-operations-with-files/index.json
  linux/challenge-special-operations-with-files/intro.md
  linux/challenge-special-operations-with-files/setup.sh
  linux/challenge-special-operations-with-files/solutions/step1-solution.md
  linux/challenge-special-operations-with-files/solutions/step2-solution.md
  linux/challenge-special-operations-with-files/solutions/step3-solution.md
  linux/challenge-special-operations-with-files/step1.md
  linux/challenge-special-operations-with-files/step2.md
  linux/challenge-special-operations-with-files/step3.md
  linux/challenge-special-operations-with-files/verify1.sh
  linux/challenge-special-operations-with-files/verify2.sh
  linux/challenge-special-operations-with-files/verify3.sh
Labels: Test Completed, Minor Repair

#524 Add challenge-different-file-editing
  linux/challenge-different-file-editing/finish.md
  linux/challenge-different-file-editing/index.json
  linux/challenge-different-file-editing/intro.md
  linux/challenge-different-file-editing/setup.sh
  linux/challenge-different-file-editing/solutions/step1-solution.md
  linux/challenge-different-file-editing/solutions/step2-solution.md
  linux/challenge-different-file-editing/solutions/step3-solution.md
  linux/challenge-different-file-editing/step1.md
  linux/challenge-different-file-editing/step2.md
  linux/challenge-different-file-editing/step3.md
  linux/challenge-different-file-editing/verify1.sh
  linux/challenge-different-file-editing/verify2.sh
  linux/challenge-different-file-editing/verify3.sh
Labels: Test Completed, Minor Repair

#523 Add lab-git-branch-basic-operations
  linux/lab-git-branch-basic-operations/finish.md
  linux/lab-git-branch-basic-operations/index.json
  linux/lab-git-branch-basic-operations/intro.md
  linux/lab-git-branch-basic-operations/setup.sh
  linux/lab-git-branch-basic-operations/step1.md
  linux/lab-git-branch-basic-operations/step2.md
  linux/lab-git-branch-basic-operations/step3.md
  linux/lab-git-branch-basic-operations/step4.md
  linux/lab-git-branch-basic-operations/verify1.sh
  linux/lab-git-branch-basic-operations/verify2.sh
  linux/lab-git-branch-basic-operations/verify3.sh
  linux/lab-git-branch-basic-operations/verify4.sh
Labels: Test Completed, Minor Repair

#479 add opencv/lab-getting-started-with-images
  opencv/lab-getting-started-with-images/assets/Image.jpg
  opencv/lab-getting-started-with-images/finish.md
  opencv/lab-getting-started-with-images/index.json
  opencv/lab-getting-started-with-images/intro.md
  opencv/lab-getting-started-with-images/setup.sh
  opencv/lab-getting-started-with-images/step1.md
  opencv/lab-getting-started-with-images/step2.md
  opencv/lab-getting-started-with-images/step3.md
  opencv/lab-getting-started-with-images/step4.md
  opencv/lab-getting-started-with-images/verify1.sh
  opencv/lab-getting-started-with-images/verify2.sh
  opencv/lab-getting-started-with-images/verify3.sh
  opencv/lab-getting-started-with-images/verify4.sh
Labels: Test Completed, Major Repair

#518 Add lab docker network tutorial
  docker/lab-docker-network-tutorial/assets/lab-docker-network-tutorial-1.png
  docker/lab-docker-network-tutorial/assets/lab-docker-network-tutorial-3.png
  docker/lab-docker-network-tutorial/assets/lab-docker-network-tutorial-4.png
  docker/lab-docker-network-tutorial/assets/lab-docker-network-tutorial-5.png
  docker/lab-docker-network-tutorial/assets/lab-docker-network-tutorial-6.png
  docker/lab-docker-network-tutorial/finish.md
  docker/lab-docker-network-tutorial/index.json
  docker/lab-docker-network-tutorial/intro.md
  docker/lab-docker-network-tutorial/setup.sh
  docker/lab-docker-network-tutorial/step1.md
  docker/lab-docker-network-tutorial/step2.md
  docker/lab-docker-network-tutorial/step3.md
  docker/lab-docker-network-tutorial/step4.md
  docker/lab-docker-network-tutorial/step5.md
  docker/lab-docker-network-tutorial/step6.md
  docker/lab-docker-network-tutorial/verify1.sh
  docker/lab-docker-network-tutorial/verify2.sh
  docker/lab-docker-network-tutorial/verify3.sh
  docker/lab-docker-network-tutorial/verify4-1.sh
  docker/lab-docker-network-tutorial/verify4-2.sh
  docker/lab-docker-network-tutorial/verify4-3.sh
  docker/lab-docker-network-tutorial/verify5-1.sh
  docker/lab-docker-network-tutorial/verify5-2.sh
  docker/lab-docker-network-tutorial/verify6.sh
Labels: Test Completed, Minor Repair

#529 Add lab configuring apps with secrets
  kubernetes/lab-configuring-apps-with-secrets/assets/lab-configuring-apps-with-secrets-1.png
  kubernetes/lab-configuring-apps-with-secrets/assets/lab-configuring-apps-with-secrets-2.png
  kubernetes/lab-configuring-apps-with-secrets/assets/lab-configuring-apps-with-secrets-3.png
  kubernetes/lab-configuring-apps-with-secrets/assets/lab-configuring-apps-with-secrets-5.png
  kubernetes/lab-configuring-apps-with-secrets/finish.md
  kubernetes/lab-configuring-apps-with-secrets/index.json
  kubernetes/lab-configuring-apps-with-secrets/intro.md
  kubernetes/lab-configuring-apps-with-secrets/setup.sh
  kubernetes/lab-configuring-apps-with-secrets/step1.md
  kubernetes/lab-configuring-apps-with-secrets/step2.md
  kubernetes/lab-configuring-apps-with-secrets/step3.md
  kubernetes/lab-configuring-apps-with-secrets/step4.md
  kubernetes/lab-configuring-apps-with-secrets/step5.md
  kubernetes/lab-configuring-apps-with-secrets/verify1-1.sh
  kubernetes/lab-configuring-apps-with-secrets/verify1-2.sh
  kubernetes/lab-configuring-apps-with-secrets/verify1.sh
  kubernetes/lab-configuring-apps-with-secrets/verify2-1.sh
  kubernetes/lab-configuring-apps-with-secrets/verify2-2.sh
  kubernetes/lab-configuring-apps-with-secrets/verify2.sh
  kubernetes/lab-configuring-apps-with-secrets/verify3.sh
  kubernetes/lab-configuring-apps-with-secrets/verify4-1.sh
  kubernetes/lab-configuring-apps-with-secrets/verify4-2.sh
  kubernetes/lab-configuring-apps-with-secrets/verify4.sh
  kubernetes/lab-configuring-apps-with-secrets/verify5.sh
Labels: Test Completed, Minor Repair

#492 Lab kubernetes architecture
  kubernetes/lab-kubernetes-architecture/finish.md
  kubernetes/lab-kubernetes-architecture/index.json
  kubernetes/lab-kubernetes-architecture/intro.md
  kubernetes/lab-kubernetes-architecture/setup.sh
  kubernetes/lab-kubernetes-architecture/step1.md
  kubernetes/lab-kubernetes-architecture/step2.md
  kubernetes/lab-kubernetes-architecture/step3.md
  kubernetes/lab-kubernetes-architecture/step4.md
  kubernetes/lab-kubernetes-architecture/verify1.sh
  kubernetes/lab-kubernetes-architecture/verify2.sh
  kubernetes/lab-kubernetes-architecture/verify3-1.sh
  kubernetes/lab-kubernetes-architecture/verify3-2.sh
  kubernetes/lab-kubernetes-architecture/verify4-1.sh
  kubernetes/lab-kubernetes-architecture/verify4-2.sh
Labels: Test Completed, Minor Repair

#517 Lab kubernetes expose command
  kubernetes/lab-kubernetes-expose-command/finish.md
  kubernetes/lab-kubernetes-expose-command/index.json
  kubernetes/lab-kubernetes-expose-command/intro.md
  kubernetes/lab-kubernetes-expose-command/setup.sh
  kubernetes/lab-kubernetes-expose-command/step1.md
  kubernetes/lab-kubernetes-expose-command/step2.md
  kubernetes/lab-kubernetes-expose-command/verify1-1.sh
  kubernetes/lab-kubernetes-expose-command/verify1-2.sh
  kubernetes/lab-kubernetes-expose-command/verify1-3.sh
  kubernetes/lab-kubernetes-expose-command/verify2-1.sh
  kubernetes/lab-kubernetes-expose-command/verify2-2.sh
Labels: Test Completed, Minor Repair

#520 Lab running pod with daemonsets
  kubernetes/lab-running-pod-with-daemonsets/finish.md
  kubernetes/lab-running-pod-with-daemonsets/index.json
  kubernetes/lab-running-pod-with-daemonsets/intro.md
  kubernetes/lab-running-pod-with-daemonsets/setup.sh
  kubernetes/lab-running-pod-with-daemonsets/step1.md
  kubernetes/lab-running-pod-with-daemonsets/step2.md
  kubernetes/lab-running-pod-with-daemonsets/step3.md
  kubernetes/lab-running-pod-with-daemonsets/step4.md
  kubernetes/lab-running-pod-with-daemonsets/verify1-1.sh
  kubernetes/lab-running-pod-with-daemonsets/verify1-2.sh
  kubernetes/lab-running-pod-with-daemonsets/verify2-1.sh
  kubernetes/lab-running-pod-with-daemonsets/verify2-2.sh
  kubernetes/lab-running-pod-with-daemonsets/verify3-1.sh
  kubernetes/lab-running-pod-with-daemonsets/verify3-2.sh
  kubernetes/lab-running-pod-with-daemonsets/verify4-1.sh
  kubernetes/lab-running-pod-with-daemonsets/verify4-2.sh
Labels: Test Completed, Minor Repair

#527 Lab kubernetes run command
  kubernetes/lab-kubernetes-run-command/finish.md
  kubernetes/lab-kubernetes-run-command/index.json
  kubernetes/lab-kubernetes-run-command/intro.md
  kubernetes/lab-kubernetes-run-command/setup.sh
  kubernetes/lab-kubernetes-run-command/step1.md
  kubernetes/lab-kubernetes-run-command/step2.md
  kubernetes/lab-kubernetes-run-command/verify1-1.sh
  kubernetes/lab-kubernetes-run-command/verify1-2.sh
  kubernetes/lab-kubernetes-run-command/verify2-1.sh
  kubernetes/lab-kubernetes-run-command/verify2-2.sh
Labels: Test Completed, Minor Repair

#513 Challenge school enrollment system
  python/challenge-school-enrollment-system/assets/count_enrollment.py
  python/challenge-school-enrollment-system/assets/count_enrollment_test.py
  python/challenge-school-enrollment-system/finish.md
  python/challenge-school-enrollment-system/index.json
  python/challenge-school-enrollment-system/intro.md
  python/challenge-school-enrollment-system/setup.sh
  python/challenge-school-enrollment-system/solutions/count_enrollment.py
  python/challenge-school-enrollment-system/step1.md
  python/challenge-school-enrollment-system/verify1.sh
Labels: Test Completed, No Repair

#510 Challenge school grading system
  python/challenge-school-grading-system/assets/calculate_grade.py
  python/challenge-school-grading-system/assets/calculate_grade_test.py
  python/challenge-school-grading-system/finish.md
  python/challenge-school-grading-system/index.json
  python/challenge-school-grading-system/intro.md
  python/challenge-school-grading-system/setup.sh
  python/challenge-school-grading-system/solutions/calculate_grade.py
  python/challenge-school-grading-system/step1.md
  python/challenge-school-grading-system/verify1.sh
Labels: Test Completed, No Repair

#508 Challenge school attendance tracker
  python/challenge-school-attendance-tracker/assets/track_attendance.py
  python/challenge-school-attendance-tracker/assets/track_attendance_test.py
  python/challenge-school-attendance-tracker/finish.md
  python/challenge-school-attendance-tracker/index.json
  python/challenge-school-attendance-tracker/intro.md
  python/challenge-school-attendance-tracker/setup.sh
  python/challenge-school-attendance-tracker/solutions/track_attendance.py
  python/challenge-school-attendance-tracker/step1.md
  python/challenge-school-attendance-tracker/verify1.sh
Labels: Test Completed, No Repair

#509 Challenge bus capacity
  python/challenge-bus-capacity/assets/max_passengers.py
  python/challenge-bus-capacity/assets/max_passengers_test.py
  python/challenge-bus-capacity/finish.md
  python/challenge-bus-capacity/index.json
  python/challenge-bus-capacity/intro.md
  python/challenge-bus-capacity/setup.sh
  python/challenge-bus-capacity/solutions/max_passengers.py
  python/challenge-bus-capacity/step1.md
  python/challenge-bus-capacity/verify1.sh
Labels: Test Completed, No Repair

#475 Challenge personalized message
  python/challenge-personalized-message/assets/display_message.py
  python/challenge-personalized-message/assets/display_message_test.py
  python/challenge-personalized-message/finish.md
  python/challenge-personalized-message/index.json
  python/challenge-personalized-message/intro.md
  python/challenge-personalized-message/setup.sh
  python/challenge-personalized-message/solutions/display_message.py
  python/challenge-personalized-message/step1.md
  python/challenge-personalized-message/verify1.sh
Labels: Test Completed, No Repair

#469 Challenge printing multiplication table
  python/challenge-printing-multiplication-table/assets/print_multiplication_table.py
  python/challenge-printing-multiplication-table/assets/print_multiplication_table_test.py
  python/challenge-printing-multiplication-table/finish.md
  python/challenge-printing-multiplication-table/index.json
  python/challenge-printing-multiplication-table/intro.md
  python/challenge-printing-multiplication-table/setup.sh
  python/challenge-printing-multiplication-table/solutions/print_multiplication_table.py
  python/challenge-printing-multiplication-table/step1.md
  python/challenge-printing-multiplication-table/verify1.sh
Labels: Test Completed, No Repair

#444 add-challenge-movie-theater-tickets
  python/challenge-movie-theater-tickets/assets/step1.py
  python/challenge-movie-theater-tickets/assets/step1_test.py
  python/challenge-movie-theater-tickets/finish.md
  python/challenge-movie-theater-tickets/index.json
  python/challenge-movie-theater-tickets/intro.md
  python/challenge-movie-theater-tickets/setup.sh
  python/challenge-movie-theater-tickets/solutions/step1.py
  python/challenge-movie-theater-tickets/step1.md
  python/challenge-movie-theater-tickets/verify1.sh
Labels: Test Completed, Minor Repair

#483 Lab kubernetes exec command
  kubernetes/lab-kubernetes-exec-command/finish.md
  kubernetes/lab-kubernetes-exec-command/index.json
  kubernetes/lab-kubernetes-exec-command/intro.md
  kubernetes/lab-kubernetes-exec-command/setup.sh
  kubernetes/lab-kubernetes-exec-command/step1.md
  kubernetes/lab-kubernetes-exec-command/step2.md
  kubernetes/lab-kubernetes-exec-command/step3.md
  kubernetes/lab-kubernetes-exec-command/step4.md
  kubernetes/lab-kubernetes-exec-command/verify1-1.sh
  kubernetes/lab-kubernetes-exec-command/verify1-2.sh
  kubernetes/lab-kubernetes-exec-command/verify2-1.sh
  kubernetes/lab-kubernetes-exec-command/verify2-2.sh
  kubernetes/lab-kubernetes-exec-command/verify3.sh
  kubernetes/lab-kubernetes-exec-command/verify4-1.sh
  kubernetes/lab-kubernetes-exec-command/verify4-2.sh
Labels: Test Completed, Minor Repair

#493 Lab kubernetes create command
  kubernetes/lab-kubernetes-create-command/finish.md
  kubernetes/lab-kubernetes-create-command/index.json
  kubernetes/lab-kubernetes-create-command/intro.md
  kubernetes/lab-kubernetes-create-command/setup.sh
  kubernetes/lab-kubernetes-create-command/step1.md
  kubernetes/lab-kubernetes-create-command/step2.md
  kubernetes/lab-kubernetes-create-command/step3.md
  kubernetes/lab-kubernetes-create-command/step4.md
  kubernetes/lab-kubernetes-create-command/step5.md
  kubernetes/lab-kubernetes-create-command/verify1-1.sh
  kubernetes/lab-kubernetes-create-command/verify1-2.sh
  kubernetes/lab-kubernetes-create-command/verify2-1.sh
  kubernetes/lab-kubernetes-create-command/verify2-2.sh
  kubernetes/lab-kubernetes-create-command/verify3-1.sh
  kubernetes/lab-kubernetes-create-command/verify3-2.sh
  kubernetes/lab-kubernetes-create-command/verify4-1.sh
  kubernetes/lab-kubernetes-create-command/verify4-2.sh
  kubernetes/lab-kubernetes-create-command/verify5-1.sh
  kubernetes/lab-kubernetes-create-command/verify5-2.sh
Labels: Test Completed, No Repair

#246 Add challenge make numpy array your shape
  numpy/challenge-make-numpy-array-your-shape/assets/concatenate_arrays.py
  numpy/challenge-make-numpy-array-your-shape/assets/concatenate_arrays_test.py
  numpy/challenge-make-numpy-array-your-shape/assets/reshape_array.py
  numpy/challenge-make-numpy-array-your-shape/assets/reshape_array_test.py
  numpy/challenge-make-numpy-array-your-shape/assets/split_array.py
  numpy/challenge-make-numpy-array-your-shape/assets/split_array_test.py
  numpy/challenge-make-numpy-array-your-shape/assets/stack_arrays.py
  numpy/challenge-make-numpy-array-your-shape/assets/stack_arrays_test.py
  numpy/challenge-make-numpy-array-your-shape/finish.md
  numpy/challenge-make-numpy-array-your-shape/index.json
  numpy/challenge-make-numpy-array-your-shape/intro.md
  numpy/challenge-make-numpy-array-your-shape/setup.sh
  numpy/challenge-make-numpy-array-your-shape/solutions/concatenate_arrays.py
  numpy/challenge-make-numpy-array-your-shape/solutions/reshape_array.py
  numpy/challenge-make-numpy-array-your-shape/solutions/split_array.py
  numpy/challenge-make-numpy-array-your-shape/solutions/stack_arrays.py
  numpy/challenge-make-numpy-array-your-shape/step1.md
  numpy/challenge-make-numpy-array-your-shape/step2.md
  numpy/challenge-make-numpy-array-your-shape/step3.md
  numpy/challenge-make-numpy-array-your-shape/step4.md
  numpy/challenge-make-numpy-array-your-shape/verify1.sh
  numpy/challenge-make-numpy-array-your-shape/verify2.sh
  numpy/challenge-make-numpy-array-your-shape/verify3.sh
  numpy/challenge-make-numpy-array-your-shape/verify4.sh
Labels: Test Completed, Minor Repair

#433 add lab-webbrowser-package-basic
  python/lab-webbrowser-package-basic/assets/example.html
  python/lab-webbrowser-package-basic/finish.md
  python/lab-webbrowser-package-basic/index.json
  python/lab-webbrowser-package-basic/intro.md
  python/lab-webbrowser-package-basic/setup.sh
  python/lab-webbrowser-package-basic/step1.md
  python/lab-webbrowser-package-basic/step2.md
  python/lab-webbrowser-package-basic/step3.md
  python/lab-webbrowser-package-basic/step4.md
  python/lab-webbrowser-package-basic/verify1-1.sh
  python/lab-webbrowser-package-basic/verify1-2.sh
  python/lab-webbrowser-package-basic/verify2.sh
  python/lab-webbrowser-package-basic/verify3.sh
  python/lab-webbrowser-package-basic/verify4-1.sh
  python/lab-webbrowser-package-basic/verify4-2.sh
Labels: Test Completed

#349 add challenge-unleashing-the-power-of-decorators
  python/challenge-unleashing-the-power-of-decorators/assets/authenticate.py
  python/challenge-unleashing-the-power-of-decorators/assets/authenticate_test.py
  python/challenge-unleashing-the-power-of-decorators/assets/log_it.py
  python/challenge-unleashing-the-power-of-decorators/assets/log_it_test.py
  python/challenge-unleashing-the-power-of-decorators/assets/time_it.py
  python/challenge-unleashing-the-power-of-decorators/assets/time_it_test.py
  python/challenge-unleashing-the-power-of-decorators/finish.md
  python/challenge-unleashing-the-power-of-decorators/index.json
  python/challenge-unleashing-the-power-of-decorators/intro.md
  python/challenge-unleashing-the-power-of-decorators/setup.sh
  python/challenge-unleashing-the-power-of-decorators/solutions/step1-solution.md
  python/challenge-unleashing-the-power-of-decorators/solutions/step2-solution.md
  python/challenge-unleashing-the-power-of-decorators/solutions/step3-solution.md
  python/challenge-unleashing-the-power-of-decorators/step1.md
  python/challenge-unleashing-the-power-of-decorators/step2.md
  python/challenge-unleashing-the-power-of-decorators/step3.md
  python/challenge-unleashing-the-power-of-decorators/verify1.sh
  python/challenge-unleashing-the-power-of-decorators/verify2.sh
  python/challenge-unleashing-the-power-of-decorators/verify3.sh
Labels: Test Completed, Minor Repair, Stale

#556 Challenge warehouse inventory
  python/challenge-warehouse-inventory/assets/update_inventory.py
  python/challenge-warehouse-inventory/assets/update_inventory_test.py
  python/challenge-warehouse-inventory/finish.md
  python/challenge-warehouse-inventory/index.json
  python/challenge-warehouse-inventory/intro.md
  python/challenge-warehouse-inventory/setup.sh
  python/challenge-warehouse-inventory/solutions/update_inventory.py
  python/challenge-warehouse-inventory/step1.md
  python/challenge-warehouse-inventory/verify1.sh
Labels: Test Completed, No Repair

#557 Challenge embassy visitors
  python/challenge-embassy-visitors/assets/record_visitor.py
  python/challenge-embassy-visitors/assets/record_visitor_test.py
  python/challenge-embassy-visitors/finish.md
  python/challenge-embassy-visitors/index.json
  python/challenge-embassy-visitors/intro.md
  python/challenge-embassy-visitors/setup.sh
  python/challenge-embassy-visitors/solutions/record_visitor.py
  python/challenge-embassy-visitors/step1.md
  python/challenge-embassy-visitors/verify1.sh
Labels: Test Completed, No Repair

#559 Challenge postal service
  python/challenge-postal-service/assets/generate_postal_codes.py
  python/challenge-postal-service/assets/generate_postal_codes_test.py
  python/challenge-postal-service/finish.md
  python/challenge-postal-service/index.json
  python/challenge-postal-service/intro.md
  python/challenge-postal-service/setup.sh
  python/challenge-postal-service/solutions/generate_postal_codes.py
  python/challenge-postal-service/step1.md
  python/challenge-postal-service/verify1.sh
Labels: Test Completed, No Repair

#560 Challenge hiking trail challenge
  python/challenge-hiking-trail-challenge/assets/hiking_tracker.py
  python/challenge-hiking-trail-challenge/assets/hiking_tracker_test.py
  python/challenge-hiking-trail-challenge/finish.md
  python/challenge-hiking-trail-challenge/index.json
  python/challenge-hiking-trail-challenge/intro.md
  python/challenge-hiking-trail-challenge/setup.sh
  python/challenge-hiking-trail-challenge/solutions/hiking_tracker.py
  python/challenge-hiking-trail-challenge/step1.md
  python/challenge-hiking-trail-challenge/verify1.sh
Labels: Test Completed, No Repair

#564 Challenge fire station alert system
  python/challenge-fire-station-alert-system/assets/fire_emergencies.py
  python/challenge-fire-station-alert-system/assets/fire_emergencies_test.py
  python/challenge-fire-station-alert-system/finish.md
  python/challenge-fire-station-alert-system/index.json
  python/challenge-fire-station-alert-system/intro.md
  python/challenge-fire-station-alert-system/setup.sh
  python/challenge-fire-station-alert-system/solutions/fire_emergencies.py
  python/challenge-fire-station-alert-system/step1.md
  python/challenge-fire-station-alert-system/verify1.sh
Labels: Test Completed, No Repair

#565 Challenge processing time calculator
  python/challenge-processing-time-calculator/assets/calculate_processing_time.py
  python/challenge-processing-time-calculator/assets/calculate_processing_time_test.py
  python/challenge-processing-time-calculator/finish.md
  python/challenge-processing-time-calculator/index.json
  python/challenge-processing-time-calculator/intro.md
  python/challenge-processing-time-calculator/setup.sh
  python/challenge-processing-time-calculator/solutions/calculate_processing_time.py
  python/challenge-processing-time-calculator/step1.md
  python/challenge-processing-time-calculator/verify1.sh
Labels: Test Completed, No Repair

#561 Challenge government office
  python/challenge-government-office/assets/search_document.py
  python/challenge-government-office/assets/search_document_test.py
  python/challenge-government-office/finish.md
  python/challenge-government-office/index.json
  python/challenge-government-office/intro.md
  python/challenge-government-office/setup.sh
  python/challenge-government-office/solutions/search_document.py
  python/challenge-government-office/step1.md
  python/challenge-government-office/verify1.sh
Labels: Test Completed, No Repair

#530 add-challenge-numpy-array-operation
  numpy/challenge-numpy-array-operation/assets/calculate_average_purchases.py
  numpy/challenge-numpy-array-operation/assets/calculate_average_purchases_test.py
  numpy/challenge-numpy-array-operation/assets/calculate_purchase_totals.py
  numpy/challenge-numpy-array-operation/assets/calculate_purchase_totals_test.py
  numpy/challenge-numpy-array-operation/assets/calculate_revenue_totals.py
  numpy/challenge-numpy-array-operation/assets/calculate_revenue_totals_test.py
  numpy/challenge-numpy-array-operation/assets/customer_stats.py
  numpy/challenge-numpy-array-operation/assets/customer_stats_test.py
  numpy/challenge-numpy-array-operation/assets/round_values.py
  numpy/challenge-numpy-array-operation/assets/round_values_test.py
  numpy/challenge-numpy-array-operation/finish.md
  numpy/challenge-numpy-array-operation/index.json
  numpy/challenge-numpy-array-operation/intro.md
  numpy/challenge-numpy-array-operation/setup.sh
  numpy/challenge-numpy-array-operation/solutions/calculate_average_purchases.py
  numpy/challenge-numpy-array-operation/solutions/calculate_purchase_totals.py
  numpy/challenge-numpy-array-operation/solutions/calculate_revenue_totals.py
  numpy/challenge-numpy-array-operation/solutions/customer_stats.py
  numpy/challenge-numpy-array-operation/solutions/round_values.py
  numpy/challenge-numpy-array-operation/step1.md
  numpy/challenge-numpy-array-operation/step2.md
  numpy/challenge-numpy-array-operation/step3.md
  numpy/challenge-numpy-array-operation/step4.md
  numpy/challenge-numpy-array-operation/step5.md
  numpy/challenge-numpy-array-operation/step6.md
  numpy/challenge-numpy-array-operation/verify1.sh
  numpy/challenge-numpy-array-operation/verify2.sh
  numpy/challenge-numpy-array-operation/verify3.sh
  numpy/challenge-numpy-array-operation/verify4.sh
  numpy/challenge-numpy-array-operation/verify5.sh
  numpy/challenge-numpy-array-operation/verify6.sh
Labels: Test Completed, Minor Repair

#563 Add lab-git-config-management
  linux/lab-git-config-management/finish.md
  linux/lab-git-config-management/index.json
  linux/lab-git-config-management/intro.md
  linux/lab-git-config-management/setup.sh
  linux/lab-git-config-management/step1.md
  linux/lab-git-config-management/step2.md
  linux/lab-git-config-management/step3.md
  linux/lab-git-config-management/verify1.sh
  linux/lab-git-config-management/verify2.sh
  linux/lab-git-config-management/verify3.sh
Labels: Test Completed, No Repair

#511 Add challenge-who-am-i
  linux/challenge-who-am-i/finish.md
  linux/challenge-who-am-i/index.json
  linux/challenge-who-am-i/intro.md
  linux/challenge-who-am-i/setup.sh
  linux/challenge-who-am-i/solutions/step1-solution.md
  linux/challenge-who-am-i/solutions/step2-solution.md
  linux/challenge-who-am-i/step1.md
  linux/challenge-who-am-i/step2.md
  linux/challenge-who-am-i/verify1.sh
  linux/challenge-who-am-i/verify2.sh
Labels: Test Completed, Minor Repair

#528 Add challenge-file-printing
  linux/challenge-file-printing/finish.md
  linux/challenge-file-printing/index.json
  linux/challenge-file-printing/intro.md
  linux/challenge-file-printing/setup.sh
  linux/challenge-file-printing/solutions/step1-solution.md
  linux/challenge-file-printing/solutions/step2-solution.md
  linux/challenge-file-printing/solutions/step3-solution.md
  linux/challenge-file-printing/step1.md
  linux/challenge-file-printing/step2.md
  linux/challenge-file-printing/step3.md
  linux/challenge-file-printing/verify1.sh
  linux/challenge-file-printing/verify2.sh
  linux/challenge-file-printing/verify3.sh
Labels: Test Completed, Minor Repair

#536 Add challenge numpy dot product
  numpy/challenge-numpy-dot-product/assets/calculate_covariance_matrix.py
  numpy/challenge-numpy-dot-product/assets/calculate_covariance_matrix_test.py
  numpy/challenge-numpy-dot-product/finish.md
  numpy/challenge-numpy-dot-product/index.json
  numpy/challenge-numpy-dot-product/intro.md
  numpy/challenge-numpy-dot-product/setup.sh
  numpy/challenge-numpy-dot-product/solutions/calculate_covariance_matrix.py
  numpy/challenge-numpy-dot-product/step1.md
  numpy/challenge-numpy-dot-product/verify1.sh
Labels: Test Completed, No Repair

#579 challenge-math-expression-evaluator
  python/challenge-math-expression-evaluator/assets/advanced_functionality.py
  python/challenge-math-expression-evaluator/assets/advanced_functionality_test.py
  python/challenge-math-expression-evaluator/assets/basic_functionality.py
  python/challenge-math-expression-evaluator/assets/basic_functionality_test.py
  python/challenge-math-expression-evaluator/assets/eval_test1.py
  python/challenge-math-expression-evaluator/assets/eval_test2.py
  python/challenge-math-expression-evaluator/finish.md
  python/challenge-math-expression-evaluator/index.json
  python/challenge-math-expression-evaluator/intro.md
  python/challenge-math-expression-evaluator/setup.sh
  python/challenge-math-expression-evaluator/solutions/advanced_functionality.py
  python/challenge-math-expression-evaluator/solutions/basic_functionality.py
  python/challenge-math-expression-evaluator/step1.md
  python/challenge-math-expression-evaluator/step2.md
  python/challenge-math-expression-evaluator/verify1.sh
  python/challenge-math-expression-evaluator/verify2.sh
  python/challenge-math-expression-evaluator/verify3.sh
  python/challenge-math-expression-evaluator/verify4.sh
Labels: Test Completed, Minor Repair

#572 Add challenge-play-images-with-color-spaces
  python/challenge-play-images-with-color-spaces/assets/convert_color_space.py
  python/challenge-play-images-with-color-spaces/assets/convert_color_space_test.py
  python/challenge-play-images-with-color-spaces/assets/detect_color.py
  python/challenge-play-images-with-color-spaces/assets/detect_color_test.py
  python/challenge-play-images-with-color-spaces/assets/images/img1.jpg
  python/challenge-play-images-with-color-spaces/assets/img_test.jpg
  python/challenge-play-images-with-color-spaces/finish.md
  python/challenge-play-images-with-color-spaces/index.json
  python/challenge-play-images-with-color-spaces/intro.md
  python/challenge-play-images-with-color-spaces/setup.sh
  python/challenge-play-images-with-color-spaces/solutions/convert_color_space.py
  python/challenge-play-images-with-color-spaces/solutions/detect_color.py
  python/challenge-play-images-with-color-spaces/step1.md
  python/challenge-play-images-with-color-spaces/step2.md
  python/challenge-play-images-with-color-spaces/verify1.sh
  python/challenge-play-images-with-color-spaces/verify2.sh
Labels: Minor Repair

#586 Add Challenge prime sum below 100
  python/challenge-prime-sum-below-100/assets/PrimeTotal.py
  python/challenge-prime-sum-below-100/finish.md
  python/challenge-prime-sum-below-100/index.json
  python/challenge-prime-sum-below-100/intro.md
  python/challenge-prime-sum-below-100/setup.sh
  python/challenge-prime-sum-below-100/solutions/PrimeTotal.py
  python/challenge-prime-sum-below-100/step1.md
  python/challenge-prime-sum-below-100/verify1.sh
Labels: Test Completed, No Repair

#580 Challenge body mass index calculator
  python/challenge-body-mass-index-calculator/assets/calculate_bmi.py
  python/challenge-body-mass-index-calculator/assets/calculate_bmi_test.py
  python/challenge-body-mass-index-calculator/finish.md
  python/challenge-body-mass-index-calculator/index.json
  python/challenge-body-mass-index-calculator/intro.md
  python/challenge-body-mass-index-calculator/setup.sh
  python/challenge-body-mass-index-calculator/solutions/calculate_bmi.py
  python/challenge-body-mass-index-calculator/step1.md
  python/challenge-body-mass-index-calculator/verify1.sh
Labels: Test Completed, No Repair

#587 Challenge hotel room availability checker
  python/challenge-hotel-room-availability-checker/assets/check_room_availability.py
  python/challenge-hotel-room-availability-checker/assets/check_room_availability_test.py
  python/challenge-hotel-room-availability-checker/finish.md
  python/challenge-hotel-room-availability-checker/index.json
  python/challenge-hotel-room-availability-checker/intro.md
  python/challenge-hotel-room-availability-checker/setup.sh
  python/challenge-hotel-room-availability-checker/solutions/check_room_availability.py
  python/challenge-hotel-room-availability-checker/step1.md
  python/challenge-hotel-room-availability-checker/verify1.sh
Labels: Test Completed, No Repair

#611 add challenge building a simple calculator
  python/challenge-building-a-simple-calculator/assets/display_result_test.py
  python/challenge-building-a-simple-calculator/assets/get_user_input_test.py
  python/challenge-building-a-simple-calculator/assets/implement_calculator.py
  python/challenge-building-a-simple-calculator/assets/perform_calculation_test.py
  python/challenge-building-a-simple-calculator/assets/simple_calculator.py
  python/challenge-building-a-simple-calculator/assets/validate_user_input_test.py
  python/challenge-building-a-simple-calculator/finish.md
  python/challenge-building-a-simple-calculator/index.json
  python/challenge-building-a-simple-calculator/intro.md
  python/challenge-building-a-simple-calculator/setup.sh
  python/challenge-building-a-simple-calculator/solutions/display_result.py
  python/challenge-building-a-simple-calculator/solutions/get_user_input.py
  python/challenge-building-a-simple-calculator/solutions/perform_calculation.py
  python/challenge-building-a-simple-calculator/solutions/validate_user_input.py
  python/challenge-building-a-simple-calculator/step1.md
  python/challenge-building-a-simple-calculator/step2.md
  python/challenge-building-a-simple-calculator/step3.md
  python/challenge-building-a-simple-calculator/step4.md
  python/challenge-building-a-simple-calculator/verify1.sh
  python/challenge-building-a-simple-calculator/verify2.sh
  python/challenge-building-a-simple-calculator/verify3.sh
  python/challenge-building-a-simple-calculator/verify4.sh
Labels: Test Completed, No Repair

#504 add-challenge-numpy-array-datatype-converter
  numpy/challenge-numpy-array-datatype-converter/assets/convert_to_dtype.py
  numpy/challenge-numpy-array-datatype-converter/assets/convert_to_dtype_test.py
  numpy/challenge-numpy-array-datatype-converter/finish.md
  numpy/challenge-numpy-array-datatype-converter/index.json
  numpy/challenge-numpy-array-datatype-converter/intro.md
  numpy/challenge-numpy-array-datatype-converter/setup.sh
  numpy/challenge-numpy-array-datatype-converter/solutions/convert_to_dtype.py
  numpy/challenge-numpy-array-datatype-converter/step1.md
  numpy/challenge-numpy-array-datatype-converter/verify1.sh
Labels: Test Completed, Minor Repair

#450 add-challenge-elapsed-time-calculator
  python/challenge-elapsed-time-calculator/assets/elapsed_time.py
  python/challenge-elapsed-time-calculator/assets/elapsed_time_test.py
  python/challenge-elapsed-time-calculator/finish.md
  python/challenge-elapsed-time-calculator/index.json
  python/challenge-elapsed-time-calculator/intro.md
  python/challenge-elapsed-time-calculator/setup.sh
  python/challenge-elapsed-time-calculator/solutions/elapsed_time.py
  python/challenge-elapsed-time-calculator/step1.md
  python/challenge-elapsed-time-calculator/verify1.sh
Labels: Test Completed, Minor Repair

#449 add-challenge-temperature-converter
  python/challenge-temperature-converter/assets/temperature_converter.py
  python/challenge-temperature-converter/assets/temperature_converter_test.py
  python/challenge-temperature-converter/finish.md
  python/challenge-temperature-converter/index.json
  python/challenge-temperature-converter/intro.md
  python/challenge-temperature-converter/setup.sh
  python/challenge-temperature-converter/solutions/temperature_converter.py
  python/challenge-temperature-converter/step1.md
  python/challenge-temperature-converter/verify1.sh
Labels: Test Completed, Minor Repair

#447 Add challenge grocery list generator
  python/challenge-grocery-list-generator/assets/grocery_list_generator.py
  python/challenge-grocery-list-generator/assets/grocery_list_generator_test.py
  python/challenge-grocery-list-generator/finish.md
  python/challenge-grocery-list-generator/index.json
  python/challenge-grocery-list-generator/intro.md
  python/challenge-grocery-list-generator/setup.sh
  python/challenge-grocery-list-generator/solutions/grocery_list_generator.py
  python/challenge-grocery-list-generator/step1.md
  python/challenge-grocery-list-generator/verify1.sh
Labels: Test Completed, Minor Repair

#601 Add lab kubernetes taint command
  kubernetes/lab-kubernetes-taint-command/finish.md
  kubernetes/lab-kubernetes-taint-command/index.json
  kubernetes/lab-kubernetes-taint-command/intro.md
  kubernetes/lab-kubernetes-taint-command/setup.sh
  kubernetes/lab-kubernetes-taint-command/step1.md
  kubernetes/lab-kubernetes-taint-command/step2.md
  kubernetes/lab-kubernetes-taint-command/step3.md
  kubernetes/lab-kubernetes-taint-command/verify1-1.sh
  kubernetes/lab-kubernetes-taint-command/verify1-2.sh
  kubernetes/lab-kubernetes-taint-command/verify2.sh
  kubernetes/lab-kubernetes-taint-command/verify3-1.sh
  kubernetes/lab-kubernetes-taint-command/verify3-2.sh
Labels: Test Completed, Minor Repair

#558 Add lab kubernetes client and server version
  kubernetes/lab-kubernetes-client-and-server-version/assets/lab-kubernetes-client-and-server-version-1.png
  kubernetes/lab-kubernetes-client-and-server-version/assets/lab-kubernetes-client-and-server-version-2.png
  kubernetes/lab-kubernetes-client-and-server-version/assets/lab-kubernetes-client-and-server-version-3.png
  kubernetes/lab-kubernetes-client-and-server-version/assets/lab-kubernetes-client-and-server-version-4.png
  kubernetes/lab-kubernetes-client-and-server-version/finish.md
  kubernetes/lab-kubernetes-client-and-server-version/index.json
  kubernetes/lab-kubernetes-client-and-server-version/intro.md
  kubernetes/lab-kubernetes-client-and-server-version/setup.sh
  kubernetes/lab-kubernetes-client-and-server-version/step1.md
  kubernetes/lab-kubernetes-client-and-server-version/step2.md
  kubernetes/lab-kubernetes-client-and-server-version/step3.md
  kubernetes/lab-kubernetes-client-and-server-version/step4.md
  kubernetes/lab-kubernetes-client-and-server-version/verify1.sh
  kubernetes/lab-kubernetes-client-and-server-version/verify2.sh
  kubernetes/lab-kubernetes-client-and-server-version/verify3.sh
  kubernetes/lab-kubernetes-client-and-server-version/verify4.sh
Labels: Test Completed, Minor Repair

#592 Add lab isolating workloads with namespaces
  kubernetes/lab-isolating-workloads-with-namespaces/finish.md
  kubernetes/lab-isolating-workloads-with-namespaces/index.json
  kubernetes/lab-isolating-workloads-with-namespaces/intro.md
  kubernetes/lab-isolating-workloads-with-namespaces/setup.sh
  kubernetes/lab-isolating-workloads-with-namespaces/step1.md
  kubernetes/lab-isolating-workloads-with-namespaces/step2.md
  kubernetes/lab-isolating-workloads-with-namespaces/step3.md
  kubernetes/lab-isolating-workloads-with-namespaces/step4.md
  kubernetes/lab-isolating-workloads-with-namespaces/step5.md
  kubernetes/lab-isolating-workloads-with-namespaces/verify1-1.sh
  kubernetes/lab-isolating-workloads-with-namespaces/verify1-2.sh
  kubernetes/lab-isolating-workloads-with-namespaces/verify2-1.sh
  kubernetes/lab-isolating-workloads-with-namespaces/verify2-2.sh
  kubernetes/lab-isolating-workloads-with-namespaces/verify3-1.sh
  kubernetes/lab-isolating-workloads-with-namespaces/verify3-2.sh
  kubernetes/lab-isolating-workloads-with-namespaces/verify4-1.sh
  kubernetes/lab-isolating-workloads-with-namespaces/verify4-2.sh
  kubernetes/lab-isolating-workloads-with-namespaces/verify5-1.sh
  kubernetes/lab-isolating-workloads-with-namespaces/verify5-2.sh
Labels: Test Completed, No Repair

#594 Add lab role based access control on kubernetes
  kubernetes/lab-role-based-access-control-on-kubernetes/finish.md
  kubernetes/lab-role-based-access-control-on-kubernetes/index.json
  kubernetes/lab-role-based-access-control-on-kubernetes/intro.md
  kubernetes/lab-role-based-access-control-on-kubernetes/setup.sh
  kubernetes/lab-role-based-access-control-on-kubernetes/step1.md
  kubernetes/lab-role-based-access-control-on-kubernetes/step2.md
  kubernetes/lab-role-based-access-control-on-kubernetes/step3.md
  kubernetes/lab-role-based-access-control-on-kubernetes/step4.md
  kubernetes/lab-role-based-access-control-on-kubernetes/step5.md
  kubernetes/lab-role-based-access-control-on-kubernetes/step6.md
  kubernetes/lab-role-based-access-control-on-kubernetes/step7.md
  kubernetes/lab-role-based-access-control-on-kubernetes/verify1.sh
  kubernetes/lab-role-based-access-control-on-kubernetes/verify2.sh
  kubernetes/lab-role-based-access-control-on-kubernetes/verify3.sh
  kubernetes/lab-role-based-access-control-on-kubernetes/verify4-1.sh
  kubernetes/lab-role-based-access-control-on-kubernetes/verify4-2.sh
  kubernetes/lab-role-based-access-control-on-kubernetes/verify5.sh
  kubernetes/lab-role-based-access-control-on-kubernetes/verify6.sh
  kubernetes/lab-role-based-access-control-on-kubernetes/verify7-1.sh
  kubernetes/lab-role-based-access-control-on-kubernetes/verify7-2.sh
Labels: Test Completed, No Repair

#590 Add lab use statefulsets controller
  kubernetes/lab-use-statefulsets-controller/finish.md
  kubernetes/lab-use-statefulsets-controller/index.json
  kubernetes/lab-use-statefulsets-controller/intro.md
  kubernetes/lab-use-statefulsets-controller/setup.sh
  kubernetes/lab-use-statefulsets-controller/step1.md
  kubernetes/lab-use-statefulsets-controller/step2.md
  kubernetes/lab-use-statefulsets-controller/step3.md
  kubernetes/lab-use-statefulsets-controller/step4.md
  kubernetes/lab-use-statefulsets-controller/step5.md
  kubernetes/lab-use-statefulsets-controller/verify1-1.sh
  kubernetes/lab-use-statefulsets-controller/verify1-2.sh
  kubernetes/lab-use-statefulsets-controller/verify2-1.sh
  kubernetes/lab-use-statefulsets-controller/verify2-2.sh
  kubernetes/lab-use-statefulsets-controller/verify2-3.sh
  kubernetes/lab-use-statefulsets-controller/verify3-1.sh
  kubernetes/lab-use-statefulsets-controller/verify3-2.sh
  kubernetes/lab-use-statefulsets-controller/verify4-1.sh
  kubernetes/lab-use-statefulsets-controller/verify4-2.sh
  kubernetes/lab-use-statefulsets-controller/verify5.sh
Labels: Test Completed, No Repair

#538 Lab cordon and uncordon command
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/finish.md
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/index.json
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/intro.md
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/setup.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/step1.md
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/step2.md
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/step3.md
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/step4.md
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify1-1.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify1-2.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify1-3.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify2.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify3-1.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify3-2.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify3-3.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify3-4.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify4-1.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify4-2.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify4-3.sh
  kubernetes/lab-kubernetes-cordon-and-uncordon-command/verify4-4.sh
Labels: Test Completed, Minor Repair

#537 Lab Scaling and Managing Pods with Deployments
  kubernetes/lab-scaling-and-managing-pods-with-deployments/finish.md
  kubernetes/lab-scaling-and-managing-pods-with-deployments/index.json
  kubernetes/lab-scaling-and-managing-pods-with-deployments/intro.md
  kubernetes/lab-scaling-and-managing-pods-with-deployments/setup.sh
  kubernetes/lab-scaling-and-managing-pods-with-deployments/step1.md
  kubernetes/lab-scaling-and-managing-pods-with-deployments/step2.md
  kubernetes/lab-scaling-and-managing-pods-with-deployments/step3.md
  kubernetes/lab-scaling-and-managing-pods-with-deployments/step4.md
  kubernetes/lab-scaling-and-managing-pods-with-deployments/step5.md
  kubernetes/lab-scaling-and-managing-pods-with-deployments/verify1-1.sh
  kubernetes/lab-scaling-and-managing-pods-with-deployments/verify1-2.sh
  kubernetes/lab-scaling-and-managing-pods-with-deployments/verify1-3.sh
  kubernetes/lab-scaling-and-managing-pods-with-deployments/verify2-1.sh
  kubernetes/lab-scaling-and-managing-pods-with-deployments/verify3-1.sh
  kubernetes/lab-scaling-and-managing-pods-with-deployments/verify3-2.sh
  kubernetes/lab-scaling-and-managing-pods-with-deployments/verify4-1.sh
  kubernetes/lab-scaling-and-managing-pods-with-deployments/verify5.sh
Labels: Test Completed, Minor Repair

#612 challenge-morphological-transformations
  opencv/challenge-morphological-transformations/assets/apply_dilation_and_erosion.py
  opencv/challenge-morphological-transformations/assets/apply_dilation_and_erosion_test.py
  opencv/challenge-morphological-transformations/assets/apply_morphological_gradient.py
  opencv/challenge-morphological-transformations/assets/apply_morphological_gradient_test.py
  opencv/challenge-morphological-transformations/assets/apply_opening_and_closing.py
  opencv/challenge-morphological-transformations/assets/apply_opening_and_closing_test.py
  opencv/challenge-morphological-transformations/assets/example_image.jpg
  opencv/challenge-morphological-transformations/assets/example_image2.jpg
  opencv/challenge-morphological-transformations/assets/example_image3.jpg
  opencv/challenge-morphological-transformations/assets/example_image4.jpg
  opencv/challenge-morphological-transformations/assets/generate_binary_image.py
  opencv/challenge-morphological-transformations/assets/generate_binary_image_test.py
  opencv/challenge-morphological-transformations/assets/img_test.jpg
  opencv/challenge-morphological-transformations/finish.md
  opencv/challenge-morphological-transformations/index.json
  opencv/challenge-morphological-transformations/intro.md
  opencv/challenge-morphological-transformations/setup.sh
  opencv/challenge-morphological-transformations/solutions/apply_dilation_and_erosion.py
  opencv/challenge-morphological-transformations/solutions/apply_morphological_gradient.py
  opencv/challenge-morphological-transformations/solutions/apply_opening_and_closing.py
  opencv/challenge-morphological-transformations/solutions/generate_binary_image.py
  opencv/challenge-morphological-transformations/step1.md
  opencv/challenge-morphological-transformations/step2.md
  opencv/challenge-morphological-transformations/step3.md
  opencv/challenge-morphological-transformations/step4.md
  opencv/challenge-morphological-transformations/verify1.sh
  opencv/challenge-morphological-transformations/verify2.sh
  opencv/challenge-morphological-transformations/verify3.sh
  opencv/challenge-morphological-transformations/verify4.sh
Labels: Test Completed, Minor Repair

#610 Add lab kubernetes annotate command
  kubernetes/lab-kubernetes-annotate-command/finish.md
  kubernetes/lab-kubernetes-annotate-command/index.json
  kubernetes/lab-kubernetes-annotate-command/intro.md
  kubernetes/lab-kubernetes-annotate-command/setup.sh
  kubernetes/lab-kubernetes-annotate-command/step1.md
  kubernetes/lab-kubernetes-annotate-command/step2.md
  kubernetes/lab-kubernetes-annotate-command/step3.md
  kubernetes/lab-kubernetes-annotate-command/step4.md
  kubernetes/lab-kubernetes-annotate-command/step5.md
  kubernetes/lab-kubernetes-annotate-command/verify1-1.sh
  kubernetes/lab-kubernetes-annotate-command/verify1-2.sh
  kubernetes/lab-kubernetes-annotate-command/verify1-3.sh
  kubernetes/lab-kubernetes-annotate-command/verify1-4.sh
  kubernetes/lab-kubernetes-annotate-command/verify2-1.sh
  kubernetes/lab-kubernetes-annotate-command/verify2-2.sh
  kubernetes/lab-kubernetes-annotate-command/verify3-1.sh
  kubernetes/lab-kubernetes-annotate-command/verify3-2.sh
  kubernetes/lab-kubernetes-annotate-command/verify4-1.sh
  kubernetes/lab-kubernetes-annotate-command/verify4-2.sh
  kubernetes/lab-kubernetes-annotate-command/verify5-1.sh
  kubernetes/lab-kubernetes-annotate-command/verify5-2.sh
  kubernetes/lab-kubernetes-annotate-command/verify5-3.sh
  kubernetes/lab-kubernetes-annotate-command/verify5-4.sh
Labels: Test Completed, No Repair

#600 challenge-template-matching-and-drawing-results
  opencv/challenge-template-matching-and-drawing-results/assets/draw_rectangles_around_matches.py
  opencv/challenge-template-matching-and-drawing-results/assets/gray_test_source2.jpg
  opencv/challenge-template-matching-and-drawing-results/assets/gray_test_template2.jpg
  opencv/challenge-template-matching-and-drawing-results/assets/load_and_convert_images.py
  opencv/challenge-template-matching-and-drawing-results/assets/perform_template_matching.py
  opencv/challenge-template-matching-and-drawing-results/assets/test_draw_rectangles_around_matches.py
  opencv/challenge-template-matching-and-drawing-results/assets/test_load_and_convert_images.py
  opencv/challenge-template-matching-and-drawing-results/assets/test_perform_template_matching.py
  opencv/challenge-template-matching-and-drawing-results/assets/test_source.jpg
  opencv/challenge-template-matching-and-drawing-results/assets/test_source2.jpg
  opencv/challenge-template-matching-and-drawing-results/assets/test_template.jpg
  opencv/challenge-template-matching-and-drawing-results/assets/test_template2.jpg
  opencv/challenge-template-matching-and-drawing-results/finish.md
  opencv/challenge-template-matching-and-drawing-results/index.json
  opencv/challenge-template-matching-and-drawing-results/intro.md
  opencv/challenge-template-matching-and-drawing-results/setup.sh
  opencv/challenge-template-matching-and-drawing-results/solutions/draw_rectangles_around_matches.py
  opencv/challenge-template-matching-and-drawing-results/solutions/load_and_convert_images.py
  opencv/challenge-template-matching-and-drawing-results/solutions/perform_template_matching.py
  opencv/challenge-template-matching-and-drawing-results/step1.md
  opencv/challenge-template-matching-and-drawing-results/step2.md
  opencv/challenge-template-matching-and-drawing-results/step3.md
  opencv/challenge-template-matching-and-drawing-results/verify1.sh
  opencv/challenge-template-matching-and-drawing-results/verify2.sh
  opencv/challenge-template-matching-and-drawing-results/verify3.sh
Labels: Test Completed, Minor Repair

#578 Add lab storing application data with persistentvolumes
  kubernetes/lab-storing-application-data-with-persistentvolumes/assets/lab-storing-application-data-with-persistentvolumes-5.png
  kubernetes/lab-storing-application-data-with-persistentvolumes/finish.md
  kubernetes/lab-storing-application-data-with-persistentvolumes/index.json
  kubernetes/lab-storing-application-data-with-persistentvolumes/intro.md
  kubernetes/lab-storing-application-data-with-persistentvolumes/setup.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/step1.md
  kubernetes/lab-storing-application-data-with-persistentvolumes/step2.md
  kubernetes/lab-storing-application-data-with-persistentvolumes/step3.md
  kubernetes/lab-storing-application-data-with-persistentvolumes/step4.md
  kubernetes/lab-storing-application-data-with-persistentvolumes/step5.md
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify1.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify2.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify3.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify4-1.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify4-2.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify4-3.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify4-4.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify4-5.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify5-1.sh
  kubernetes/lab-storing-application-data-with-persistentvolumes/verify5-2.sh
Labels: Test Completed, Minor Repair

#570 Add challenge-count-the-vowels
  python/challenge-count-the-vowels/assets/count_the_vowels_test.py
  python/challenge-count-the-vowels/assets/count_vowels.py
  python/challenge-count-the-vowels/finish.md
  python/challenge-count-the-vowels/index.json
  python/challenge-count-the-vowels/intro.md
  python/challenge-count-the-vowels/setup.sh
  python/challenge-count-the-vowels/solutions/step1-solution.md
  python/challenge-count-the-vowels/step1.md
  python/challenge-count-the-vowels/verify1.sh
Labels: Test Completed, Minor Repair

#547 Lab configuring apps with configmaps
  kubernetes/lab-configuring-apps-with-configmaps/finish.md
  kubernetes/lab-configuring-apps-with-configmaps/index.json
  kubernetes/lab-configuring-apps-with-configmaps/intro.md
  kubernetes/lab-configuring-apps-with-configmaps/setup.sh
  kubernetes/lab-configuring-apps-with-configmaps/step1.md
  kubernetes/lab-configuring-apps-with-configmaps/step2.md
  kubernetes/lab-configuring-apps-with-configmaps/step3.md
  kubernetes/lab-configuring-apps-with-configmaps/step4.md
  kubernetes/lab-configuring-apps-with-configmaps/step5.md
  kubernetes/lab-configuring-apps-with-configmaps/verify1-1.sh
  kubernetes/lab-configuring-apps-with-configmaps/verify1-2.sh
  kubernetes/lab-configuring-apps-with-configmaps/verify2-1.sh
  kubernetes/lab-configuring-apps-with-configmaps/verify2-2.sh
  kubernetes/lab-configuring-apps-with-configmaps/verify3-1.sh
  kubernetes/lab-configuring-apps-with-configmaps/verify3-2.sh
  kubernetes/lab-configuring-apps-with-configmaps/verify4-1.sh
  kubernetes/lab-configuring-apps-with-configmaps/verify4-2.sh
  kubernetes/lab-configuring-apps-with-configmaps/verify5-1.sh
Labels: Test Completed, Minor Repair

#607 add: lab-examine-nodes-with-kubectl
  kubernetes/lab-examine-nodes-with-kubectl/finish.md
  kubernetes/lab-examine-nodes-with-kubectl/index.json
  kubernetes/lab-examine-nodes-with-kubectl/intro.md
  kubernetes/lab-examine-nodes-with-kubectl/setup.sh
  kubernetes/lab-examine-nodes-with-kubectl/step1.md
  kubernetes/lab-examine-nodes-with-kubectl/step2.md
  kubernetes/lab-examine-nodes-with-kubectl/step3.md
  kubernetes/lab-examine-nodes-with-kubectl/step4.md
  kubernetes/lab-examine-nodes-with-kubectl/step5.md
  kubernetes/lab-examine-nodes-with-kubectl/step6.md
  kubernetes/lab-examine-nodes-with-kubectl/verify1-1.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify1-2.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify2-1.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify2-2.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify2-3.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify3-1.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify3-2.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify4.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify5.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify6-1.sh
  kubernetes/lab-examine-nodes-with-kubectl/verify6-2.sh
Labels: Test Completed, No Repair

#562 Add lab modify kubeconfig files
  kubernetes/lab-modify-kubeconfig-files/assets/lab-modify-kubeconfig-files-2.png
  kubernetes/lab-modify-kubeconfig-files/assets/lab-modify-kubeconfig-files-3.png
  kubernetes/lab-modify-kubeconfig-files/assets/lab-modify-kubeconfig-files-4.png
  kubernetes/lab-modify-kubeconfig-files/assets/lab-modify-kubeconfig-files-5.png
  kubernetes/lab-modify-kubeconfig-files/finish.md
  kubernetes/lab-modify-kubeconfig-files/index.json
  kubernetes/lab-modify-kubeconfig-files/intro.md
  kubernetes/lab-modify-kubeconfig-files/setup.sh
  kubernetes/lab-modify-kubeconfig-files/step1.md
  kubernetes/lab-modify-kubeconfig-files/step2.md
  kubernetes/lab-modify-kubeconfig-files/step3.md
  kubernetes/lab-modify-kubeconfig-files/step4.md
  kubernetes/lab-modify-kubeconfig-files/step5.md
  kubernetes/lab-modify-kubeconfig-files/verify1.sh
  kubernetes/lab-modify-kubeconfig-files/verify2.sh
  kubernetes/lab-modify-kubeconfig-files/verify3.sh
  kubernetes/lab-modify-kubeconfig-files/verify4.sh
  kubernetes/lab-modify-kubeconfig-files/verify5.sh
Labels: Test Completed, Minor Repair

#574 Lab Run Pods with Jobs and CronJobs
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/finish.md
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/index.json
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/intro.md
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/setup.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/step1.md
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/step2.md
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/step3.md
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify1-1.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify1-2.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify1-3.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify1-4.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify2-1.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify2-2.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify2-3.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify2-4.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify3-1.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify3-2.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify3-3.sh
  kubernetes/lab-run-pods-with-jobs-and-cronjobs/verify3-4.sh
Labels: Test Completed, Minor Repair

#573 Lab kubernetes display resource usage
  kubernetes/lab-kubernetes-display-resource-usage/finish.md
  kubernetes/lab-kubernetes-display-resource-usage/index.json
  kubernetes/lab-kubernetes-display-resource-usage/intro.md
  kubernetes/lab-kubernetes-display-resource-usage/setup.sh
  kubernetes/lab-kubernetes-display-resource-usage/step1.md
  kubernetes/lab-kubernetes-display-resource-usage/step2.md
  kubernetes/lab-kubernetes-display-resource-usage/step3.md
  kubernetes/lab-kubernetes-display-resource-usage/verify1-1.sh
  kubernetes/lab-kubernetes-display-resource-usage/verify1-2.sh
  kubernetes/lab-kubernetes-display-resource-usage/verify2-1.sh
  kubernetes/lab-kubernetes-display-resource-usage/verify2-2.sh
  kubernetes/lab-kubernetes-display-resource-usage/verify3-1.sh
  kubernetes/lab-kubernetes-display-resource-usage/verify3-2.sh
  kubernetes/lab-kubernetes-display-resource-usage/verify3-3.sh
Labels: Test Completed, Minor Repair

#575 Lab containerprobe in kubernetes
  kubernetes/lab-containerprobe-in-kubernetes/finish.md
  kubernetes/lab-containerprobe-in-kubernetes/index.json
  kubernetes/lab-containerprobe-in-kubernetes/intro.md
  kubernetes/lab-containerprobe-in-kubernetes/setup.sh
  kubernetes/lab-containerprobe-in-kubernetes/step1.md
  kubernetes/lab-containerprobe-in-kubernetes/step2.md
  kubernetes/lab-containerprobe-in-kubernetes/step3.md
  kubernetes/lab-containerprobe-in-kubernetes/step4.md
  kubernetes/lab-containerprobe-in-kubernetes/step5.md
  kubernetes/lab-containerprobe-in-kubernetes/verify1-1.sh
  kubernetes/lab-containerprobe-in-kubernetes/verify1-2.sh
  kubernetes/lab-containerprobe-in-kubernetes/verify2-1.sh
  kubernetes/lab-containerprobe-in-kubernetes/verify2-2.sh
  kubernetes/lab-containerprobe-in-kubernetes/verify3-1.sh
  kubernetes/lab-containerprobe-in-kubernetes/verify3-2.sh
  kubernetes/lab-containerprobe-in-kubernetes/verify4-1.sh
  kubernetes/lab-containerprobe-in-kubernetes/verify4-2.sh
  kubernetes/lab-containerprobe-in-kubernetes/verify5-2.sh
Labels: Test Completed, Minor Repair

#481 add python/challenge-get-local-time
  python/challenge-get-local-time/assets/get_local_time.py
  python/challenge-get-local-time/assets/get_local_time_test.py
  python/challenge-get-local-time/finish.md
  python/challenge-get-local-time/index.json
  python/challenge-get-local-time/intro.md
  python/challenge-get-local-time/setup.sh
  python/challenge-get-local-time/solutions/get_local_time.py
  python/challenge-get-local-time/solutions/step1-solution.md
  python/challenge-get-local-time/step1.md
  python/challenge-get-local-time/verify1.sh
Labels: Test Completed, Minor Repair
